godotengine/godot-cpp

.gitattributes, .gitignore, SConstruct
These changes seem to allow us to compile this on mac os x provided Godot was compiled using 64bit.
There are still a few things wrong, I managed to compile core **with** use_llvm=yes but only bindings **without**.
The problem is that the godot executable name is suffixed with .llvm which is not correct on Mac OS X.
Ergo:
```
scons p=osx use_llvm=yes
scons p=osx target=bindings generate_bindings=yes
```
But I'm off to bed :)
=> Getting this to compile on mac os x

SConstruct
This ensures that environment variables are kept when on windows meaning you can run it with any version of VS, so long as you are in a VS prompt or have run the vcvars.bat file for your architecture
=> Keep environment variables on windows

SConstruct
This adds MSVC compiler flags to enable the DEBUG/NDEBUG defines, enable exceptions, turn on optimizations for Release builds, and link to the correct runtime library
=> Add compiler flags for windows

binding_generator.py, include/core/AABB.hpp, include/core/CoreTypes.hpp, include/core/Defs.hpp, include/core/Godot.hpp, include/core/GodotGlobal.hpp, include/core/NodePath.hpp, include/core/String.hpp, include/core/Transform.hpp, include/core/Variant.hpp, src/core/AABB.cpp, src/core/GodotGlobal.cpp, src/core/NodePath.cpp, src/core/String.cpp, src/core/Transform.cpp, src/core/Variant.cpp
Bunch of fixes so this all compiles again.
There is an issue with a function in tile_map and one in tile_set that gives a Vector2false error. This is an issue in the bindings in Godot that needs to be fixed in Godot itself.
To get around this for now you can manually edit the .hpp files and remove the defaults on the parameters.
=> Update bindings to use new Api extensions and rename Rect3->AABB

include/core/PoolArrays.hpp, src/core/PoolArrays.cpp
Same story as Array and Dictionary, without them we get double-delete crashes.
The same is apparently needed for Read and Write access too, but a Godot core addition may be required before: https://github.com/godotengine/godot/issues/15824
=> Added missing copy constructors and assign operators to PoolVectors

binding_generator.py, include/core/Ref.hpp
Now it seems to work again with no leaks.
Fixes https://github.com/GodotNativeTools/godot-cpp/issues/78
=> Rewrite Ref<T> to behave like Godot again

binding_generator.py, include/core/Ref.hpp
Fixes https://github.com/GodotNativeTools/godot-cpp/issues/85
=> Fix Ref leak when using Godot getters

README.md, SConstruct
Got trouble on mac os x trying to generate bindings from official Godot 3 binary. 
1.  Readme is wrong about godot_bin_path param (related issue https://github.com/GodotNativeTools/godot-cpp/issues/74 ). Fixed it.
2. User on mac os has only read rights inside application directory. So I explicitly generate bindings.json inside build process CWD.
=> Small fixes for build process

Makefile, README.md, SConstruct
Hola!
PRs for examples are coming tomorrow.
Best :smiley:
=> Added crosscompiling for linux-windows; Added makefile

README.md, binding_generator.py, include/core/Array.hpp, include/core/Defs.hpp, include/core/Dictionary.hpp, include/core/Godot.hpp
Implements changes mentioned in #106 
This PR modifies the `register_signal` function to use C++11 variadic templates to streamline the case when signals take arguments. It also adds a new `emit_signal` method to `GodotScript` that is similarly variadic, which proxies to the `Object::emit_signals` function.
Specifically:
- Adds helper template functions to construct a `Dictionary` (really any `foo[key] = value` container, although we expect the container to be ordered for this use case) from a template parameter pack.
- Adds a helper template function to construct an `Array` (really any object with an `append` method) from a template parameter pack.
- Modifies the `register_signal` function to use variadic templates instead of taking a Dictionary explicitly **[WARNING: this will break …
=> Adds variadic template functions for register_signal and emit_signal

SConstruct
The arch argument now will work on MSVC, I've tested it with MSVC 2017 and both bits=32 and bits=64 worked correctly.
=> Fix compile issues on Windows

include/core/PoolArrays.hpp, src/core/PoolArrays.cpp
This is needed since that operator returns a local copy, not
an lvalue. Attempting to write to the return value of these operators
wouldn't change the array element. PoolVectors need locking when
writing, so this operator can't return a writable reference.
To update a Pool*Array, use the `set()` method which locks and unlocks
the array. For multiple writes, use the `write()` method which returns
a locked writable view, and unlocks when it goes out of scope.
=> Mark all Pool*Array::operator[] as const

SConstruct
Just to follow the same logic that with linux/windows.
=> On OS X append .osx.64 to the result_name var on SConstruct

README.md
Fixes the instructions to say generate_bindings instead of regenerate_bindings, which should resolve issue #136
=> (README) Fix misleading typo regarding generate_bindings

include/core/Defs.hpp, include/core/String.hpp, src/core/Color.cpp, src/core/String.cpp
As discussed on IRC this days:
- Fix a bug where calling String::split[_floats] would crash the engine (wrong pointer cast)
- Add String::split_ints function which is missing
- Update the WARN/ERR macros to be more compatible with Godot modules (possibly, in the future, __FUNCTION__, __FILE__, and so on, will be printed too to mimic modules behaviour).
I'll leave the ADD_SIGNAL macro for another PR I still fear it's a bit hacky, and I'll like to do more tests before
=> Fix String::split[_floats] crashes, better error macros

.gitignore, include/gen/.gitignore, src/gen/.gitignore
Removed gen folder from .gitignore in the root and added .gitignore files in the gen folders. This ensures the gen folders are part of our repository and get created when the repository is cloned but none of the generated files are added to the repository.
=> Change gitignore so we get our gen folders

binding_generator.py
Ran into this when I was calling ArrayMesh::surface_get_material
This can return a NULL pointer when no material has been assigned to the surface.
When godot_nativescript_get_instance_binding_data is subsequently called to retrieve binding information things go pretty bad because this method assumes a valid pointer.
I've added a some code so check if we have a valid pointer and only call godot_nativescript_get_instance_binding_data if we do, else just return NULL.
=> Preventing crash when function returned null ptr

SConstruct
- The SCons option system is now used for validation
- An help message can now be displayed using `scons -h`
- New `use_mingw` option to compile using MinGW on Windows
- Removed `arch` in favor of `bits`
- Renamed `headers` to `headers_dir`
- Built libraries now contain the target in the file name
Help message preview:
```
❯ scons -h
scons: Reading SConscript files ...
scons: done reading SConscript files.
platform: Target platform (linux|osx|windows)
default: linux
actual: linux
bits: Target platform bits (default|32|64)
default: default
actual: default
use_llvm: Use the LLVM compiler - only effective when targeting Linux (yes|no)
default: False
actual: False
use_mingw: Use the MinGW compiler - only effective on Windows (yes|no)
default: False
actual: False
target: Compilation target …
```
=> Improve the build system

SConstruct
Now accepts both linux and x11 as the linux platform properties and gives an error if an incorrect value for platform is given.
=> Improved platform checks

include/core/Defs.hpp
`cannot pass non-trivial object of type 'godot::String' to variadic function; expected type from format string was 'char *' [-Wnon-pod-varargs]`
=> Fix compile error of 'WARN_PRINT' and 'ERR_PRINT'.

src/core/Vector3.cpp
`distance_to` was returning `length_squared` and `distance_squared_to` was return `length`. 
Just a simple fix
=> Fix Vector3.distance_to

SConstruct
Currently when I build godot-cpp with bits=32 it actually produces 64 bits objs. After this PR it works fine for me.
Fixes #177
=> Fix Windows 32 bits builds producing 64 bits code

binding_generator.py
For example `Texture::draw` method
```c++
void draw(const RID canvas_item, const Vector2 position, const Color modulate = Color(1,1,1,1), const bool transpose = false, const Ref<Texture> normal_map = nullptr) const;
```
is crashing if no `normal_map` is specified, because of null pointer dereferencing in the generated wrapper
```c++
void ___godot_icall_void_RID_Vector2_Color_bool_Object(godot_method_bind *mb, const Object *inst, const RID& arg0, const Vector2& arg1, const Color& arg2, const bool arg3, const Object *arg4) {
const void *args[] = {
(void *) &arg0,
(void *) &arg1,
(void *) &arg2,
(void *) &arg3,
(void *) arg4->_owner,
};
godot::api->godot_method_bind_ptrcall(mb, inst->_owner, args, nullptr);
}
```
This PR adds pointer check, and passes nulls directly to `ptrcall` in this …
=> Fix passing NULL pointers as arguments via ptrcall

src/core/Variant.cpp
=> Fix NULL pointer dereferencing on uninstantiated Ref<T>() conversion to Variant

include/core/GodotGlobal.hpp, include/core/GodotProfiling.hpp, src/core/GodotGlobal.cpp
This can be added now that https://github.com/godotengine/godot/pull/21229 was merged.
Note: To make functions send profiling data to godot use `GODOT_PROFILING_FUNCTION` (`DEBUG_ENABLED` must be declared on the SConstruct) on each function, like this:
```
void Player::TestFunctions() {
GODOT_PROFILING_FUNCTION
// actual code after GODOT_PROFILING_FUNCTION
}
```
=> Profiling support

include/core/Godot.hpp
Fix casting custom subclass to the base class via `cast_to`.
`_TagDB::register_type` was using same typeid for class and base, and it was doing nothing (there's `if (type_tag == base_type_tag) return;` check in the beginning of `register_type` function.
Issue example:
```c++
class A : public Resource {
GODOT_CLASS(A, Resource);
...
}
class B : public A {
GODOT_SUBCLASS(B, A);
...
}
....
void func(Object *p_ref) { //p_ref is B class
Resource* a = cast_to<Resource>(p_ref); //this cast was failing (fixed by this PR)
A* a = cast_to<A>(p_ref); //this cast was failing (fixed by this PR)
B* b = cast_to<B>(p_ref); //this cast was ok
}
```
=> Fix tags/cast_to for custom subclasses.

binding_generator.py
Resolves issue #228. Note: this issue isn't specific to Windows.
The fix added the 'typename' keyword to the escape list, so that things compile fine. Compiled godot-cpp, rebuilt gdnative examples against that and run fine.
=> escape 'typename' keyword, which is causing errors when generating bindings

LICENSE.md
Follow-up to https://github.com/GodotNativeTools/godot_headers/pull/40.
=> Use Markdown format for the license

README.md
Git submodules are a little tricky to use, but are the default
way to go when adding a github project as a dependency in C++.
Add instructions on how to add godot-cpp as a dependency when
working from an existing repository.
=> Add instructions to use submodules

SConstruct
`TAGET_ARCH` is set only on windows platforms and the build fails on osx if the `bits` option is not passed explicitly as follow.
```
scons p=osx bits=64 generate_bindings=yes
```
The docs should be updated accordingly or `SConstruct` changed to use 64bits by default on osx.
=> Set default arch to 64bits for osx platform

LICENSE.md, src/core/String.cpp
Added @Acclution s fix so that things compile and raised an issue for @karroffel to look at that some more.
Brought this in sync with our 3.1 godot_headers branch
=> Synced with Godot 3.1 stable

SConstruct, include/core/Basis.hpp, include/core/Vector2.hpp, include/core/Vector3.hpp, src/core/Basis.cpp, src/core/Vector2.cpp, src/core/Vector3.cpp
Per https://github.com/godotengine/godot/issues/14553:
Godot stores Basis in row-major layout for more change for efficiently
taking advantage of SIMD instructions, but in scripts Basis looks like and
is accessible in a column-major format.
This change modifies the C++ binding so that from the script's perspective
Basis does look like if it was column-major while retaining a row-major
in-memory representation. This is achieved using a set of helper template
classes which allow accessing individual columns whose components are
non-continues in memory as if it was a Vector3 type. This ensures script
interface compatibility without needing to transpose the Basis every time
it is passed over the script-engine boundary.
Also made most of the Vecto2 and Vector3 class interfaces inlined in the …
=> Make Basis look column-major while retaining a row-major representation

CMakeLists.txt
This allows creating a project as so:
```
add_subdirectory(godot-cpp)
project(project-name)
add_library(project-name SHARED src/init.cpp)
target_link_libraries(project-name godot-cpp)
```
=> changes to cmake file so it can be used as a subdirectory

include/core/Basis.hpp, include/core/Transform.hpp, src/core/Transform.cpp
The [] operator of Basis was returning a reference to a temporary, so fixed it.
There was no * operator in Transform equivalent to the xform function, which is
not in line with GDScript behavior.
Also fixed remaining cases where Transform relied on the old behavior of the
[] operator of Basis (i.e. that it returns the row, not the column).
=> Fix bug in Basis [] operator and add missing Transform-Vector3 * operator

include/core/Godot.hpp
bruvzg's original comment with the patch is here:
https://github.com/GodotNativeTools/godot-cpp/issues/237#issuecomment-465170294
I am using this and it works, even though I don't fully understand why it does.
Fixes #237.
=> Fix registering properties of reference-types by applying bruvzg's patch

.travis.yml, misc/travis/clang-format.sh
This ensures the repository is always in a buildable state, while also checking for code style violations.
`clang-format.sh` was taken from https://github.com/godotengine/godot/blob/c50ab02e4ceb1517f3a87a7bac82967ba1e6e2a9/misc/travis/clang-format.sh.
=> Set up Travis CI

SConstruct
Add `host_platform` checks and MinGW-w64 prefixes for archive tools and linker.
=> Fix MinGW-w64 cross-compilation on macOS.

src/core/Quat.cpp
Just a small fix of the way Quaternion multiplication is implemented.
Modified code was copied directly from the Godot master branch.
=> Fixed wrong implementation of Quat multiplication

include/core/Array.hpp, include/core/Defs.hpp
Changed error message macros to actually use Godot's error reporting
facilities instead of outputting straight to stderr. This enables
GDNative errors to actually show up inside the editor.
Messages and set of available macros now also better matches that of
the engine itself.
=> Error message improvements

SConstruct
As noticed there: https://github.com/GodotNativeTools/godot-cpp/pull/261
Tested successfully with [MSYS2](https://www.msys2.org/) (`pacman -S mingw-w64-x86_64-gcc python2 scons`) with the following command:
```
scons platform=windows generate_bindings=yes use_mingw=1 bits=64
```
=> Add MSYS/MinGW compiling support on Windows

include/core/Array.hpp, include/core/Basis.hpp, include/core/Color.hpp, include/core/GodotGlobal.hpp, include/core/NodePath.hpp, include/core/Quat.hpp, include/core/String.hpp, src/core/Array.cpp, src/core/Basis.cpp, src/core/Color.cpp, src/core/GodotGlobal.cpp, src/core/NodePath.cpp, src/core/Quat.cpp, src/core/String.cpp
Updated version of https://github.com/GodotNativeTools/godot-cpp/pull/216
=> Add missing class methods

include/core/GodotGlobal.hpp, src/core/GodotGlobal.cpp
We were only capturing the core struct pointer and nativescript struct pointers.
Added all the others we currently support.
=> Store all main entry points to the currently available APIs

src/core/GodotGlobal.cpp
Moved register types and init into our library initialization code. For singleton libraries it is not guaranteed nativescript_init gets called before we start using classes within Godot.
As a result this leads to crashes when trying to instantiate objects before this code is executed.
=> Call register types and init earlier

README.md, SConstruct
This PR adds the ability to compile for the various Android architectures using the Android NDK toolchain. The following Scons options have been added:
- `android_arch`: The target Android architecture to compile for. Allowed values: `armv7, arm64v8, x86, x86_64`
- `android_api_level`: The Android API level to target (defaults to `18` for 32-bit architectures, `21` for 64-bit)
- `ANDROID_NDK_ROOT`: The path to an Android NDK installation on your machine. By default, fetches from the system's environment variables.
The only requirement is that the user download the [Android NDK](https://developer.android.com/ndk/downloads).
This branch has been tested on Windows, Linux and OSX using my [nightly CI build](https://travis-ci.com/TGRCdev/gdsqlite-native) of Godot's [SQLite …
=> Godot-cpp compile for Android

src/core/Variant.cpp
Previously, Variants were unpacked like this:  
```cpp
Variant::operator PoolVector2Array() const {
godot_pool_vector2_array s = godot::api->godot_variant_as_pool_vector2_array(&_godot_variant);
return *(PoolVector2Array *)&s;
}
```
The cast implicitly calls the C++ type's copy constructor. (You can find it in the gdb disassembly.) This increases the ref-count *twice* instead of just once through `godot_variant_as_*`. For PoolArrays, it caused an error message on exiting Godot:  
```
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
At: core/pool_vector.cpp:69.
```
All of the ref-counted, RAII-managed core types are affected. The fix is to use a local variable and return it instead of casting.
=> Fix leaks caused by implicitly-called copy constructors

include/core/Defs.hpp
Was causing failed builds when used outside of the godot namespace.
=> Add godot namespace to references in Defs macros.

src/core/String.cpp
Fixes godotengine/godot#32502.
`new_string` was adding a reference to `this` without removing it.
It looks like #307 also fixes this leak by cleaning up the way the underlying `godot_string` is accessed. Not sure if there's a reason it wasn't merged 2 months ago, but if the cleaner style is preferred, that one should be merged instead.
=> Fix String::operator+ memory leak

include/core/Vector2.hpp
It seems like everything was implemented for supporting the bounce function, in:
**Godot itself:**
- Entry exists in 'modules/gdnative/gdnative/vector2.cpp'
- Entry exists in 'modules/gdnative/gdnative_api.json'
- Entry exists in 'modules/gdnative/include/gdnative/vector2.h'
**Godot Headers:**
- Entry exists 'gdnative/vector2.h'
However, the thing that was missing was to have an actual function in 'include/core/Vector2.hpp'
I added this (just a copy from Godot's bounce-function) as it was requested by #347
Some questions:
- Why are some functions defined in the header file (include/core/Vector2.hpp) and not in the source file (src/core/Vector2.cpp)?
- Should the Vector2-files in Godot-cpp be updated to include all of the missing functionalities?
=> Added bounce to vector2.hpp

SConstruct
Fixed issue so that `scons platform=windows use_mingw=yes` uses mingw instead of MSVC.
Ref: https://github.com/GodotNativeTools/godot-cpp/issues/337 
Note: vim removed some white spaces, the main change is from line 217
=> windows use_mingw build fix

SConstruct
Adds ability to compile `godot-cpp` for the iOS devices (armv7, armv8) and simulator (x86_64).
Currently, Godot export seems to ignore gdnative libs for the iOS, but adding appropriate static libs to the exported xcode project manually works OK (at least in the simulator).
Following Scons options have been added:
* `ios_arch` = `arm64`(default), `armv7`, `x86_64` target architecture
* `IPHONEPATH` = toolchain path (default value should work for normal xcode installation), SDK path is detected via `xcrun` utility.
*[gdtl](https://github.com/bruvzg/godot_tl) gdnative demo project running in simulator:*
=> Add iOS build support.

src/core/GodotGlobal.cpp
A initialization bug was causing the registration to occur prior to a key required field being set (see https://github.com/GodotNativeTools/godot-cpp/issues/394#issuecomment-613636985 for more details).
Fixes #394
=> Fix godot-cpp types registration

include/core/Defs.hpp
Should fix https://github.com/GodotNativeTools/godot-cpp/issues/376.
The place is similar to Godot, which adds it as part of `platform_config.h`.
=> Fix alloca() not being included on some platforms

.travis.yml
Could likely use `pip` instead of relying on unreliable SourceForge, but it's a good first step anyway.
=> Travis: Use SCons 3.1.2 on Windows

include/core/Godot.hpp
This is a new take that can replace https://github.com/GodotNativeTools/godot-cpp/pull/401 and #346 (it goes a long way at this point).
Should fix #397, #343, #215, maybe also #362.
PR #350 is no longer needed, as well as https://github.com/godotengine/godot/pull/33532 and https://github.com/GodotNativeTools/godot_headers/pull/60, so it should also be easier to merge.
PR #346 might also be no longer needed, if it's about the same issue? Though I don't really understand the change it does.
To understand what's going on and why this is yet another PR, I wrote a summary here: https://github.com/godotengine/godot/pull/33532#issuecomment-636268406
This PR avoids the *original source* of the leak by directly creating the new instance, without going through reference initialization (which is …
=> Rework the way custom class instances are created from C++

include/core/Array.hpp, include/core/Dictionary.hpp, src/core/Variant.cpp
#355 fixed a leak caused by copy constructors. However, for Array and Dictionary, the fix now calls default constructors that allocate memory for an empty array/dictionary, again resulting in a leak. The other types fixed by #355 aren't affected - their default constructors do nothing.
The only way I can think of to convert a `godot_array` to a `godot::Array` *without* calling either constructor is to add a new `Array(godot_array a)` constructor to do the conversion. This way is clean and safe, but exposes part of the C API to C++. If we want to avoid that, maybe we can find a better way.
=> Add C conversion constructors and fix new leak

include/core/Godot.hpp
Adds register_class_method, a variant of register_method where the user can
specify a derived class to register the method for.
Usage:
```
register_class_method<DerivedClass>("_process", &BaseClass::_process);
```
Would address #303. Might address #256.
=> Allow registering base class methods for derived classes

binding_generator.py
Fixes https://github.com/godotengine/godot-cpp/issues/432
=> Don't use Ref<T> in Object.hpp

include/core/Vector2.hpp, include/core/Vector3.hpp
I'm not sure if the functions should be `inline` or not, and where they should go (in the hpp or in the cpp files), so let me know if there are issues.
Fixes #422
=> Add missing move_toward to Vector2 and Vector3

include/core/String.hpp, src/core/String.cpp
The member _godot_string should never be straight out overwritten ever without
first destroying the underlying string object's memory. This change solves the
problem through the introduction of a new private constructor to create String
objects with a pre-existing godot_string handle.
=> Fixed memory leak with String objects

src/core/String.cpp
Criated the String::operator+=(const wchar_t), that as marked as @Todo.
=> Create an operator

include/core/Defs.hpp
MinGW was previously trying to include `alloca.h`, which was causing compilation to fail on both Windows and Linux. This should stop that from happening. (Fixes #414)
=> Fix alloca.h error in Defs.h

binding_generator.py, include/core/Godot.hpp
This PR changes how `Object::cast_to<T>(o)` checks o's type when T is an engine class.
`TagDB` would fail on instances of non-exposed types like `BulletPhysicsDirectSpaceState`. Instead, engine types are now type-checked by the engine's own `cast_to` implementation, which doesn't require GDNative to have type tag/parent info about internal types. NativeScripts continue to be checked with `TagDB`.
Related to #175, godotengine/godot#28195, and godotengine/godot#28574, but they were actually fixed already. This only fixes casts affected by the same issue.
(Depends on godotengine/godot#34688 and updated godot_headers.)
=> Fix `cast_to` for non-exposed engine types

SConstruct, binding_generator.py
Some teammates and I have gotten a bit tired of having to use `cast_to` every time `get_node` is used, and while we've been using a macro to make it a bit less verbose, we wanted a more tidy solution. So I decided to try implementing a template version of `get_node` similar to the `GetNode` generic function that's in the C# API.
This allows the following to be written:
```cpp
Sprite* sprite = cast_to<Sprite>(get_node("Sprite")); // old
Sprite* sprite = get_node<Sprite>("Sprite"); // new
```
This is achieved in a similar way to how `Object::cast_to` is generated, by simply adding a new section in the bindings generator file. To get around name clashing, I also renamed the original `get_node` to `get_node_internal`, but it still calls "get_node" in the Godot bindings, so it should work the …
=> Add option to generate template version of Node::get_node

include/core/Vector2.hpp, include/core/Vector3.hpp
Fixes Vector 2 and 3 bounce and reflect methods to match gdscript
```c++
//C++
Vector3 v = Vector3(0.003606, -0.081427, -0.045547);
Vector3 n = Vector3(0, -1, 0);
Vector3 b = v.bounce(n);
Vector3 r = v.reflect(n);
Vector2 v2 = Vector2(0.003606, -0.081427);
Vector2 n2 = Vector2(0, -1);
Vector2 b2 = v2.bounce(n2);
Vector2 r2 = v2.reflect(n2);
Godot::print("V3Bounce");
Godot::print(b);
Godot::print("V3Reflect");
Godot::print(r);
Godot::print("V2Bounce");
Godot::print(b2);
Godot::print("V2Reflect");
Godot::print(r2);
```
```GDScript
#GDScript
var v = Vector3(0.003606, -0.081427, -0.045547)
var n = Vector3(0, -1, 0)
var b = v.bounce(n)
var r = v.reflect(n)
print("V3Bounce")
print(b)
print("V3Reflect")
print(r)
var v2 = Vector2(0.003606, -0.081427)
var n2 = Vector2(0, -1)
var b2 = v2.bounce(n2) …
```
=> Fix Vector's Bounce Reflect

SConstruct
Fixes https://github.com/GodotNativeTools/godot-cpp/issues/381
I went for a slightly different fix than mentionned in the issue:
now the default value of `bits` is dynamically chosen to be `32` or `64` based on auto-detection.
This fix is slightly compatibility breaking, as you won't be able to specify `bits = default`. Let me know if you prefer to preserve this ability.
=> Fix default value of `bits` misnaming resulting library

include/core/RID.hpp, src/core/RID.cpp
I think this was an oversight, it wasnt supposed to be called `get_rid`
=> Rename `RID::get_rid()` => `get_id()` to match Godot

SConstruct
`-g` is a compiler option that adds debugging information, which can be very heavy in our case due to the many classes we generate.  This is fine for debugging, but in release it should not be present.
This PR removes this flag from `target=release` builds so it's only used with `target=debug`.
Should fix https://github.com/godotengine/godot-cpp/issues/300
=> Don't generate debugging symbols in release builds

binding_generator.py, include/core/Godot.hpp
So far, if you make a custom class, you had to use the `GODOT_CLASS` macro on top of it. But then if you make a custom class inheriting another custom class, you had to use `GODOT_SUBCLASS`.
This PR removes the difference, now you should be able to use `GODOT_CLASS` for any custom class.
`GODOT_SUBCLASS` remains defined for compatibility.
=> Remove the need to use GODOT_SUBCLASS

include/core/Vector3.hpp
It(Vector3 slide) wasn't the same before (same as godot implementation) and resulted in weird behavior, its better now.
=> Added some missing Vector3 functions and Fixed Vector3 slide

SConstruct
Adds an option to set the macOS deployment target
e.g. `scons platform=osx macos_deployment_target=10.11 target=release`
This is required to build for older macOS machines.
=> Add macos_deployment_target SConstruct option.

include/core/Ref.hpp
`Ref<T>` now uses `Object::cast_to`, which should be safer. The previous cast could cause undefined behavior if the types were incompatible, now it should return null, which can be checked with `.is_valid()` or `is_null()`.
I also attempted to add a `static_assert` to enforce `T` to derive from `Reference`, however this would force any mention of `Ref<T>` to also `#include` the definition of `T`, which might not be desirable when forward-declarations are used to speed up compilation (as bindings are currently generated), so I haven't included it.
Should fix https://github.com/godotengine/godot-cpp/issues/76
=> Use safer casts in Ref<T>

include/core/Basis.hpp, include/core/Quat.hpp, include/core/Transform.hpp, include/core/Transform2D.hpp, include/core/Vector2.hpp, include/core/Vector3.hpp, src/core/Basis.cpp, src/core/Quat.cpp, src/core/Transform.cpp, src/core/Transform2D.cpp, src/core/Vector2.cpp, src/core/Vector3.cpp
Adds missing constants like `Vector3_LEFT`, `Basis_IDENTITY` or `Vector2::AXIS_X`.
~~Some use an `_` because C++ did not allow me to place a constant inside the definition of the type of that constant.~~
Updated: now constants are declared in the classes, and defined in the cpp files. This is not exactly the same as a constexpr since the value is now defined inside the library with an actual address instead of being header-only and inline, but it's likely not a big deal.
Should fix https://github.com/godotengine/godot-cpp/issues/467
=> Added missing constants to Vector2, Vector3, Basis and Quat

include/core/Godot.hpp
`p` is unused, but cannot be `/*commented*/` because it triggers different warnings again in user code. This parameter is required for template matching to work. It's a nasty syntax.
It might need a per-compiler macro of some sort prepended to the argument, but I have no idea how to approach this so for now I'll revert it.
Edit: changed to a `(void) p;`
=> Revert comment in the middle of function pointer in Godot.hpp

include/core/CameraMatrix.hpp, src/core/CameraMatrix.cpp
Redundant math function definitions in CameraMatrix has been replaced by the ones in Math.hpp
=> Replaced static math functions in CameraMatrix by Math usage

.github/workflows/ci.yml
MacOS 11.0 seems to be unavailable at the moment: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-software
=> Fix MacOS CI using an available runner

SConstruct
This should fix MinGW builds on the CI: https://github.com/Zylann/cpp_bindings/runs/1802898864?check_suite_focus=true
Also should likely fix #361, see https://github.com/godotengine/godot-cpp/issues/361#issuecomment-607516261
~~Mac OS is still lost in limbo.~~
Mac OS needs to use a different runner: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-software
=> Dont carry MSVC stuff to MinGW builds

SConstruct
Added a `ios_simulator` flag for SConstruct which should allow building for arm64 simulator.
=> iOS arm64 simulator support.

LICENSE.md
=> Update copyright statement to 'Godot Engine contributors'

SConstruct
This PR adds a primitive check to figure out if bindings should be generated or not.
It checks if `src/gen/Object.cpp` exists. If it isn't found, then bindings will get generated.
The `generate_bindings` option is an enumeration that can be given the following values:
- `true`, or `yes`: will generate bindings
- `no`: will not generate bindings
- `auto`: will detect presence of bindings. This is now the default value, so less users will forget to do this step.
This check does not detect if bindings should be re-generated. So if you update the library with Git for example, you still have to tell it explicitely, or clear the generated folder before building.
=> Generate bindings if they are not found

SConstruct
I added freebsd specific configuration in order to fix build issues on freebsd related to these issues
#312 
#442 
I added it as a separate target instead of just renaming it to linux in case a project is meant to be for both linux and freebsd to differentiate the linux and freebsd binary names (as from what i remember they aren't compatible)
=> Added freebsd specific configuration to SConstruct

CMakeLists.txt, binding_generator.py
This is a resubmission of an old Pull Request that stagnated (because of some mysterious Travis error):
https://github.com/GodotNativeTools/godot-cpp/pull/368
The code was rebased to the latest master
----
I needed to fix the file generation in the `CMakeLists.txt` for my own project.
The file generation currently regenerates sources and headers every time any `CMakeLists.txt` is modified and it takes a long time to recompile. With my modification the generation happens only when necessary.
Another thing I needed to modify is that the generation of any intermediate file should go into the build folder, not into the source folder. For this I needed to modify the `binding_generator.py`.
If you need me to modify/improve anything of this pull request don't hesitate to ask.
=> Fixed cmake source file generation

src/core/Vector2.cpp, src/core/Vector3.cpp
Fixes #549 by populating `Vector2::ONE`, `Vector2::INF`, and `Vector3::ONE`.
=> Populates incorrect constants for Vector2 and 3 types.

binding_generator.py
On Windows, paths are mixed by os.path.join with different slash directions. This should generally be fine but when using the print function we print "C:\\\\mypath/myfile.cpp" as "C:\\mypath/myfile.cpp" which is unescaped on the backward slash. To fix this I propose to replace "\\\\" with "/" just before printing it out for CMake usage. I would suggest using pathlib but it is not included by default on python versions <= 3.3 which may still be an issue.
=> Fix CMake generation on Windows

.gitignore, SConstruct
Related to godotengine/godot#48320 for recent emscripten support.
EDIT: Also add byte-code files to `.gitignore`
=> Fix JavaScript library suffix.

.github/workflows/ci.yml, SConstruct
New "macos_arch" to specify the desired arch, and "macos_sdk_path" to override the default SDK path.
=> Add OSX arm64 build target.

include/core/Defs.hpp
These values were removed by https://github.com/godotengine/godot/pull/14000.
=> Remove extraneous Error enum values that were removed in Godot 3.0

binding_generator.py
Like done for the other pool array types.
Fixes godotengine/godot#50554 .
=> Fix binding when default parameter is a PoolByteArray.

binding_generator.py
Prefix parameters named `enum` with an underscore like all the other reserved keywords.
=> Escape parameters named `enum`.

.github/workflows/ci.yml
Also cleanup needlessly specific dependencies.
The Ubuntu 16.04 runner has been removed by GitHub Actions so CI was failing.
--
This makes the Linux artifact incompatible with distros (well glibc versions) older than Ubuntu 18.04, but that's probably not too bad.
The better approach would be to use Godot's own Linux buildroot SDK which is built against a very old glibc, yet using all the latest and greatest toolchains: https://downloads.tuxfamily.org/godotengine/toolchains/linux/
=> CI: Update Linux runner to Ubuntu 18.04

SConstruct
Was always `.64`, it's now `.arm64` for M1.
=> Fix OSX library name for arm64.

src/core/CameraMatrix.cpp
Clang 11 fails to build godot-cpp over Wabsolute-value. Fixing to use `std::abs(float)`.
```
sam@sam:~/work/spacebandit/libgai$ clang-11 --version
Ubuntu clang version 11.0.0-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
-- Version: 6.2.2
-- Build type: Release
-- CXX_STANDARD: 11
-- Required features: cxx_variadic_templates
-- Generating Bindings
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sam/work/spacebandit/libgai/work
Consolidate compiler generated dependencies of target fmt
[  0%] Built target fmt
Consolidate compiler generated dependencies of target libgai-test
[  2%] Built target libgai-test
Consolidate compiler generated dependencies of target godot-cpp
[  2%] Building CXX object …
```
=> Fix clang 11 build failure over Wabsolute-value

include/core/String.hpp, src/core/String.cpp
`String::begins_with()` and `String::ends_with()` currently take a non-const `String&` argument. This looks like a mistake since the underlying C bindings expect const strings.
Currently this code does not compile since the string literal can't bind to a non-const reference:
```c++
String test;
test.ends_with("doesn't compile");
```
=> Fix argument constness in String::begins_with, String::ends_with

include/core/Godot.hpp
In the current master of this repo, this works on Linux but fails to compile on Windows (ambiguous with `class... Args`).
```cpp
godot::register_signal<HUD>("start_game");
```
The only way I can figure out to get something that compiles everywhere is this, which is sub-optimal:
```cpp
godot::register_signal<HUD>("start_game", godot::Dictionary());
```
This PR adds an explicit no-arg version of register signal:
```cpp
template <class T>
void register_signal(String name) {
static_assert(T::___CLASS_IS_SCRIPT, "This function must only be used on custom classes");
godot_signal signal = {};
signal.name = *(godot_string *)&name;
godot::nativescript_api->godot_nativescript_register_signal(godot::_RegisterState::nativescript_handle,
T::___get_class_name(), &signal);
}
```
So that we can do this …
=> Add ability to easily register signals with no arguments

include/core/Godot.hpp, include/core/Variant.hpp, src/core/Variant.cpp
Every source file that includes iostream leaves behind some code for it in the object file.
See this example:
test.cpp
```cpp
#include <iostream>
```
`clang -S -O3 -emit-llvm -o test.ll test.cpp`
```llvm
; ModuleID = 'test.cpp'
source_filename = "test.cpp"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
%"class.std::ios_base::Init" = type { i8 }
@_ZStL8__ioinit = internal global %"class.std::ios_base::Init" zeroinitializer, align 1
@__dso_handle = external hidden global i8
@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__sub_I_test.cpp, i8* null }]
declare dso_local void @_ZNSt8ios_base4InitC1Ev(%"class.std::ios_base::Init"* …
```
=> Stop including iostream in Variant.hpp (to produce slightly smaller binaries)

SConstruct
This adds android toolchain components, according to [this documentation](https://developer.android.com/ndk/guides/other_build_systems).
Closed #330 in favor of this one.
=> Fix: add missing toolchain elements for android

binding_generator.py
Fixes build error with `3.x` headers due to a default argument being an empty NodePath (`""`).
Before:
```
include/gen/SoftBody.hpp
109:    void set_point_pinned(const int64_t point_index, const bool pinned, const NodePath attachment_path = );
```
After:
```
include/gen/SoftBody.hpp
109:    void set_point_pinned(const int64_t point_index, const bool pinned, const NodePath attachment_path = "");
```
=> bindgen: Properly escape NodePath in default args

.github/workflows/ci.yml
It can't pass and fixing it in the heavily WIP extensions implementation
would be a hassle, it's better to readd tests once things are working.
=> CI: Disable test build to prepare for 4.0 extensions merge

binding_generator.py
Minor style improvement, follows up #27. Was suggested by @vnen.
=> Use default destructor for Object

include/godot_cpp/core/method_ptrcall.hpp
As introduced in godot for virtual methods.
Custom structs are not yet supported.
=> Add pointers support for virtual methods.

include/godot_cpp/classes/ref.hpp, test/demo/main.gd, test/src/example.cpp, test/src/example.h
Added PtrToArg and GetTypeInfo adapted from Godot.
Also adds a test for it.
Note: Returning references from godot-cpp seem to always require an extra referencing. My guess it that when returning it to godot it gets passed as an object, and that Godot does not create it's internal `Ref` in time. The instance seem to be destroyed when expected with the extra `reference()` before return.
Fixes #628 .
=>  Add Ref<T> binding support.

test/SConstruct, test/demo/example.gdextension
I've changed the `SConstruct` file for the demo so that building release and debug builds now puts that in the name of the DLL. I also added platform and bits so that the naming is in line with `godot-cpp`.
This allows us to deploy both debug and release builds. I've updated the `.gdextension` file accordingly, it seems to be loading the correct one in the editor but I haven't check the export yet and that probably will need some upstream fixes.
Because the platform is now in the name of the dll I've removed the folders here, seemed overkill.
Finally I've moved a few things to the top of the file so that you can copy this `SConstruct` for your own project and edit two or three entries and it will work. I figured people would appreciate that especially if we continue building out our test …
=> test: Setup for building both debug and release build

.github/workflows/ci.yml, SConstruct
This is more of the work by @bruvzg in #529 .
My other two PRs combined were not the same, as they did not add the possibility to create a `universal` binary (i.e. a library containing both x64 and arm64 binaries).
This PR adds it and make the universal build the default and the only one in CI.
I'm sorry for the big mess :disappointed: (I'll try to backport to the 3.3 branch once confrimed).
=> [OSX] Add OSX universal build support.

.github/workflows/ci.yml, SConstruct
`3.x` port of #634 .
Small differences:
- Default arch is still `x86_64`, binary suffix is kept as `.64`  for compatibility(?).
- The `x86_64` build is kept in CI (as it works with the `test`, and I'm not sure it's safe to update the `gdnlib` in this branch).
=> [3.x] [OSX] Add universal build support.

CMakeLists.txt
* Attach debug flags to the target and mark as `PUBLIC`. This will allow all
projects that use bindings not to add the same defines manually.
* Use generator-expressions to support multiconfig generators (such as
MSVC).
* Remove explicit `NDEBUG` and `_DEBUG` flags, CMake handles it
automatically.
=> Rework debug flags for CMake

CMakeLists.txt
In [df9164b9bd7b4505a9918212e39451b75a38a7d7](https://github.com/godotengine/godot-cpp/commit/df9164b9bd7b4505a9918212e39451b75a38a7d7) TYPED_METHOD_BIND definition was added to scons project configuration. 
Without it windows method binding fail on compilation
=> Synced windows compile definitions with scons configuration

binding_generator.py, src/variant/packed_arrays.cpp, test/demo/main.gd, test/src/example.cpp, test/src/example.h
Resubmit of GDExceptions array index operators
=> Implement index operators for Arrays

binding_generator.py, src/variant/packed_arrays.cpp, test/demo/main.gd, test/demo/main.tscn, test/src/example.cpp, test/src/example.h
Requires https://github.com/godotengine/godot/pull/55247
Implement accessing dictionary through index. The test case in our test project works but fails on returning the dictionary which is a different issue. The problem here is that `return dict` will do a swap with a temporary dictionary object. This object does not instance a Godot object and the error happens on trying to free this non-existent object. We can see in the log that the dictionary was returned correctly:
```
USER ERROR: Condition "!_p" is true.
at: Dictionary::_unref (core\variant\dictionary.cpp:244) - Condition "!_p" is true.
test dictionary {foo:bar, hello:world}
```
CI will fail until `godot-headers` is updated.
=> Implementing dictionary operators

SConstruct
Follow-up to https://github.com/godotengine/godot/pull/55203.
```
❯ scons example=no  
scons: Reading SConscript files ...
WARNING: Unknown SCons variables were passed and will be ignored:
example=no
scons: done reading SConscript files.
scons: Building targets ...
```
=> Print a warning with unknown SCons variables to ease troubleshooting

src/variant/variant.cpp
I am not sure about what I am doing, but this at least avoids a crash in my case.
The crash used to happen when generating the docs, while I had one of my extension's class property referencing another class (extending Resource): 
```
ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "magica_voxel_data", PROPERTY_HINT_RESOURCE_TYPE, "MagicaVoxelData"), "set_magica_voxel_data", "get_magica_voxel_data");
```
I suppose this fix does not really fix the underlying problem, but it avoids a crash. Which is likely a first good step IMO.
=> Avoid crash in Variant constructor from nullptr Object*

src/core/Variant.cpp
This is to prevent memory leaks in the present implementation of Variant operator= in GDNative (see #647, #643)
*Bugsquad edit:*
- Fixes #643
- Fixes #647
=> Call Variant destructor in operator= to prevent a memory leak

SConstruct, binding_generator.py, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/memory.hpp, src/classes/wrapped.cpp, src/godot.cpp
This requires **https://github.com/godotengine/godot/pull/55470** to work.
First, the Godot object creation is the first step executed when creating an extension instance. This is done by making the default constructor call the parent one in the initialization list. The topmost Wrapped constructor thus call the Godot object creation as soon as possible (using `classdb_construct_object`). 
As we want to keep the possibility to create a default Constructor in a custom class (those using the `GDCLASS` macro), I could not pass the final `p_godot_class` parameter to the `Wrapped(const char *p_godot_class)` constructor with the actual class name. Instead, the name of the first class built-in to Godot is passed. This is thus enough to construct the Godot object, but not to finalize the …
=> Make extension instances create the corresponding godot object in their constructor

CMakeLists.txt
If CMake finds additional copies of python on a system it may choose python 2. This change ensures that at least python 3 is chosen.
=> Require at least Python 3

include/godot_cpp/core/object.hpp
The namespace references are inconsistent and effects code that uses explicit namespaces
=> Fix namespace to be consistent with the previous ADD functions

include/godot_cpp/classes/wrapped.hpp, src/classes/wrapped.cpp
This used to cause errors to be printed out, such as:
```
Class 'Image' has no native extension.
Class 'ImageTexture' has no native extension.
...
```
This happened for all objects created from a Godot built-in class. In such cases, we are not supposed to set the `_extension` and `_extension_instance` properties of the associated Godot `Object`, which `object_set_instance` does.
For this, I renamed `_get_class` to `_get_extension_class`, which will return `nullptr` for all built-in classes, and the extension class name for extension-only classes.
Also, I remove `CHECK_CLASS_CONSTRUCTOR`, it is unused since my recent constructor rework.
=> Fix object_set_instance being wrongly called for built-in wrapped classes

CMakeLists.txt
Backport of #675. This is required to get CLion to compile CMakeLists properly on my mac. I think it's very much worth having it in 3.x too.
=> [3.x] In CMakeLists, use the new FindPython3 instead of FindPython

.github/workflows/ci.yml, SConstruct, test/SConstruct
In this PR:
- Add SCons support for building library on Android/iOS.
- Projects can now be built by including the library and using its env so you don't have to worry about platform and toolchain setup.
Convert the project test file to work use the env from the libary.
Build the test with:
```bash
scons
```
Or, if you prefer building the library separately:
```
scons build_library=no
```
Follow up on what I proposed in #635
=> Android/iOS build, Scons boilerplate for building projects.

SConstruct
Follow up on #636 which resulted in the test library being produced with the wrong name (missing dot).
=> [Build] Fix exposed suffix, remove unused option.

binding_generator.py, include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/char_string.hpp, include/godot_cpp/variant/color.hpp, include/godot_cpp/variant/plane.hpp, include/godot_cpp/variant/quaternion.hpp, include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/rect2i.hpp, include/godot_cpp/variant/transform2d.hpp, include/godot_cpp/variant/transform3d.hpp, include/godot_cpp/variant/variant.hpp, include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, src/core/method_bind.cpp, src/variant/char_string.cpp, src/variant/packed_arrays.cpp, src/variant/variant.cpp
- Adds `ptr()` / `ptrw()` to the arrays, and renames existing `ptr` to `_native_ptr` to avoid conflict.
- Adds `ptr()` / `ptrw()`, `parse_utf*` and `utf*` methods to the `String`.
- Adds missing implementations of `length()` and `get_data()` methods of `Char*String`.
=> Add `ptr()` / `ptrw()` to the arrays, add missing `String` methods, add missing `CharString` method implementations.

binding_generator.py
Adds `GDVIRTUAL_NATIVE_PTR` and `VARIANT_ENUM_CAST` binder for the generated headers, this allows to bind/override methods with `NativePtr` and `enum` type arguments / returns.
=> Add Variant binders for the generated classes, structs and global enums

SConstruct
Fixes `error: invalid argument '-std=c++17' not allowed with 'C'` errors with `C` or `Objective-C` files added to the plug-in environment.
=> Use C++17 flag only for C++ files.

include/godot_cpp/core/error_macros.hpp, src/core/error_macros.cpp
Allows using `String` type messages (for easier error message formatting) in the `ERR_` macros.
=> Add ERR_ macros variants using `String` messages.

include/godot_cpp/variant/vector2.hpp, src/variant/vector2.cpp, src/variant/vector3.cpp
The definition is simply missing.
=> Add missing Vector3::operator Vector3i definition

include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/rect2i.hpp, include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, src/variant/rect2.cpp, src/variant/rect2i.cpp, src/variant/vector2.cpp, src/variant/vector2i.cpp, src/variant/vector3.cpp, src/variant/vector3i.cpp
Adds operators to convert from int vector types to float vector types
as done in the upstream engine implementations.
Follow-up to https://github.com/godotengine/godot/pull/58321 and other recent upstream PRs, and #688.
**Note:** When we're closer to the 4.0-stable release upstream, we should do a comparative review of core types implemented here and upstream - there might have been a number of fixes upstream since this was implemented, and not all of them found their way back to this repo.
=> Use forward declares for vector math types

include/godot_cpp/classes/wrapped.hpp
Fixes #694
Note: the binding generator already does this: https://github.com/godotengine/godot-cpp/blob/4d9fe6dfaaee892e9b369093c20df9fe1a2ef767/binding_generator.py#L925
=> Fix GDCLASS when inherited class is in another namespace

SConstruct, binding_generator.py, test/SConstruct
This PR runs `black --line-length 120` on these files in the 3.x branch. 3.4 version: #711 master version: #712
I don't actually know what line length we prefer, but the default value of `80` breaks up the `opts.Add(EnumVariable(` lines, which makes it look way less readable in my opinion.
=> [3.x] Run black format on SConstruct files and bindings generator

SConstruct, binding_generator.py, test/SConstruct
This PR runs `black --line-length 120` on these files in the master branch. 3.x version: #710 3.4 version: #711
=> [master] Run black format on SConstruct files and bindings generator

SConstruct, binding_generator.py, test/SConstruct
This PR runs `black --line-length 120` on these files in the 3.4 branch. 3.x version: #710 master version: #712
I don't actually know what line length we prefer, but the default value of `80` breaks up the `opts.Add(EnumVariable(` lines, which makes it look way less readable in my opinion.
=> [3.4] Run black format on SConstruct files and bindings generator

include/godot_cpp/core/method_bind.hpp
This aims to fix #718. Hopefully it is the correct approach.
=> Fixed crash on release builds due to missing argument type information

.github/workflows/ci.yml
Scoop install is being problematic since their 0.1.0 release.
It gives this error:
```
Run Invoke-Expression (New-Object System.Net.WebClient).DownloadString('get.scoop.sh')
Initializing...
Running the installer as administrator is disabled by default, use -RunAsAdmin parameter if you know what you are doing.
Abort.
Error: Process completed with exit code 1.
```
Couldn't find how to work it around.
=> CI: Install MinGW via `egor-tensin/setup-mingw`

binding_generator.py
Fixes return and temporary variable types used for `ptrcall` according to conversions defined here: https://github.com/godotengine/godot-cpp/blob/7fa81e798bffe5bc5e2ff71f50372d25533e4463/include/godot_cpp/core/method_ptrcall.hpp#L116-L127
Prevents stack corruption in the methods like `int Node::get_child_count(bool p_include_internal) const`, which are using 32-bit int return.
=> Fix return type encoding for ptrcall.

.gitmodules, godot-headers/README.md, godot-headers/godot/gdnative_interface.h
With the new GDExtension API, the headers are just two files, one of
which is generated and needs to always be kept in sync with the Godot
engine version.
So there's little practical use for using godot-headers as a submodule
anymore, and it only makes godot-cpp updates more cumbersome.
Custom headers (i.e. a custom API JSON) can still be used by passing
the `headers_dir` SCons option.
=> Remove godot-headers submodule, copy files directly

godot-headers/godot/gdnative_interface.h, include/godot_cpp/core/class_db.hpp
Fix build after https://github.com/godotengine/godot/pull/58972.
Note: Also requires `godot-headers` sync to work. I guess it worth waiting for https://github.com/godotengine/godot/pull/59140, which will also require headers sync (but should not break anything else).
=> Fix build after "Discern between VIRTUAL and ABSTRACT class bindings".

binding_generator.py
Followup to https://github.com/godotengine/godot-cpp/pull/729, I have missed the branch for `void` return.
=> Fix generating static methods without return value.

include/godot_cpp/variant/color.hpp
Counterpart to https://github.com/godotengine/godot/pull/60199.
Also syncs the extension API with that PR.
=> Color: Rename to_srgb/to_linear to include base color space

.github/workflows/ci.yml
Those CI steps were removed in #691 (included in the matrix) but were brought back by a merge commit attached to #683 .
=> [CI] Remove duplicate builds.

SConstruct, binding_generator.py
Using a scons Builder we now regenerate the bindings automatically when the Godot API json or header has changed.
The option to force bindings regeneration (generate_bindings=yes) is retained.
=> [Scons] Use dependency to track bindings generation.

godot-headers/godot/gdnative_interface.h, include/godot_cpp/godot.hpp, src/godot.cpp, test/src/register_types.cpp, test/src/register_types.h
Follow-up for https://github.com/godotengine/godot/pull/60723
- Changes initializers / terminators to the single function to match new init style and allow using the same code for built-in modules and extensions.
- Syncs headers.
=> Change registered initializers / terminators to the single function with level argument.

SConstruct
If you build javascript target in windows command line, the arguments will not be in POSIX style which is needed for Emscripten. I fixed it
=> Build javascript target on windows host

include/godot_cpp/core/binder_common.hpp, include/godot_cpp/core/method_bind.hpp
This fixes issue #753. The value of `GetTypeInfo::VARIANT_TYPE` is normally a member of the enum `GDNativeVariantType` but in some cases, like with the macro `VARIANT_ENUM_CAST()` it's a member of `Variant::Type` and compilation fails. These enums are completely equivalent except for the names (`NIL` vs `GDNATIVE_VARIANT_TYPE_NIL`) so casting between them is safe.
With this fix user defined enums compile and are treated as `int`s in GDScript, which is expected behavior without `PROPERTY_HINT_ENUM`.
=> Cast `GetTypeInfo::VARIANT_TYPE` to `GDNativeVariantType`

.github/workflows/ci.yml, README.md, SConstruct, binding_generator.py, test/demo/example.gdextension, test/demo/icon.png.import, test/demo/main.gd, test/demo/main.tscn, test/demo/project.godot
This PR is the `master` / 4.x version of #714, and is similar to [55778](https://github.com/godotengine/godot/pull/55778) in the engine repo.
In the current master branch of godot-cpp, we have several arguments for specifying the architecture: `bits`, `ios_arch`, `macos_arch`, and `android_arch`. This is a bit of a mess, so this PR replaces all of these with a single unified `arch`.
The list of valid architectures is `["", "universal", "x86_32", "x86_64", "arm32", "arm64", "rv64", "ppc32", "ppc64", "wasm32"]`. The names were chosen to be explicit such that each architecture always includes the bitness in the name (except universal, which contains multiple architectures).
If `""`, then it will automatically determine the architecture. It will use universal for macOS and iOS, arm64 for …
=> Unify bits, android_arch, macos_arch ios_arch into arch, support non-x86 Linux

.github/workflows/ci.yml, SConstruct, test/SConstruct, test/gdexample.gdnlib
=> [3.x] Scons boilerplate for building projects. Android, iOS builds.

src/core/Rect2.cpp
Was relying on comparison with 1e20 which cannot be represented as float, causing some epsilon to always be returned and compilers complaining when using -Werror.
Basically porting https://github.com/godotengine/godot/pull/15091 to godot-cpp.
Fixes #775
=> Fix Rect2::distance_to not returning 0

SConstruct, test/demo/example.gdextension, tools/android.py, tools/ios.py, tools/ios_osxcross.py, tools/javascript.py, tools/linux.py, tools/my_spawn.py, tools/osx.py, tools/osxcross.py, tools/windows.py
In this PR:
- Fix `test` gdextension file missing windows 32 bits.
- Move toolchains logic to tools folder.
- Add OSXCross support for `osx` and `ios`.
- Add min ios version override.
=> [SCons] Move toolchains logic to tools folder, various improvements.

include/godot_cpp/core/method_bind.hpp
When `get_argument_info_func` is called in [godot/core/extension/native_extension.cpp](https://github.com/godotengine/godot/blob/f41cb30f9b7fe46a014162aba9c0e9a9697343d2/core/extension/native_extension.cpp#L55-L66) with `p_arg == -1`, which is the index of the argument to get the type info for, in this case the return value, the ``GDNativePropertyInfo`` struct variable ``pinfo`` will never be filled with the type info and the struct members will stay uninitialized. This happens here:
https://github.com/godotengine/godot-cpp/blob/eaaf941c10fca3ef8e69574a9c256369b31f5b92/include/godot_cpp/core/method_bind.hpp#L601-L605
Sometimes the editor still runs, but looking at the documentation of an example class, the static method without return value shows a missing return type, which should be …
=> Fix crash when using static methods without return value due to uninitialized GDNativePropertyInfo struct members

.github/workflows/ci.yml, SConstruct, tools/linux.py, tools/windows.py
Fixes #779.
Closes #780.
Minimum SCons version is set to 4.0 .
=> [SCons] Fix msvc, linux-clang, add version check.

tools/windows.py
Visual C++ has a clang-based driver, available through the
clang-cl wrapper (which provides the same interface as
cl) - this generates objects binary-compatible with the
default (traditional) driver, and can then be linked in
the normal way. As such, this patch simply configures for
MSVCC and then overwrites the cl compiler with clang-cl
in the environment.
Clang gives (subjectively) much more understandable compiler warnings
and errors than MSVCC, which was my motivation for switching.
Test-Information:
Builds for me with VS2022, and my gdextension library
builds and links.
=> Add clang-cl support

.github/workflows/ci.yml, SConstruct
This doesn't change the behavior when `--jobs`/`-j` is specified as a
command-line argument or in `SCONSFLAGS`.
The SCons hack used to know if `num_jobs` was set by the user is derived
from the MongoDB setup.
We use `os.cpu_count()` for portability (available since Python 3.4).
With 4 CPUs or less, we use the max. With more than 4 we use max - 1 to
preserve some bandwidth for the user's other programs.
Equivalent to upstream Godot https://github.com/godotengine/godot/pull/63087.
Should speed up macOS builds by using 3 cores by default (and dehardcodes `-j4` in the Makefile).
=> SCons: Default `num_jobs` to max CPUs minus 1 if not specified

CMakeLists.txt
Use CMAKE_CURRENT_SOURCE_DIR to generate the binary in the current CMake directory instead of building it at the top level of the source tree
=> Generate binary in the current CMake source dir

CMakeLists.txt
The repository's CMakeLists.txt file was not reliably giving a library file of the name structure `godot-cpp.<platform>.<build_type>.<system_bits>`. Tested on Windows using MSVC and CMake v3.19, which gave me the mysterious file: `godot-cpp.windows..32.lib`, which is missing the `build_type` entirely and detected 32-bit despite being on a 64-bit machine.
While I'm unsure why `CMAKE_SIZEOF_VOID_P` was resolving as 4 on my 64-bit machine, I figured it would be nice to be able to explicitly specify the architecture like you can in the SConstruct file (with `bits=64`). Additionally, the statement `CMAKE_BUILD_TYPE STREQUAL ""` evaluates to false when `CMAKE_BUILD_TYPE` is not defined.
With both of these updates, you should be able to replicate (using an out-of-source build on Windows as an …
=> Fix default library filename generation in CMakeLists.txt

include/godot_cpp/core/object.hpp
As ``Objec::cast_to`` is merely a dynamic_cast, it shouldn't fail on ``nullptr``. As the provided argument gets dereferenced right away, we have to make the initial check. As I'm fairly new to the godot scene, I do not have much insights into the code base. Perhaps there is a more elegant solution to the problem, but I won't find it right now.
Nevertheless, this fix also fixes calls to ``Node::get_node<T>`` when no ``Node`` with the given name can be found (and probably even more other parts).
=> Object::cast_to checks provided object for nullptr

include/godot_cpp/classes/ref.hpp, include/godot_cpp/core/method_ptrcall.hpp
Object pointer arguments for virtual function callbacks are not correctly converted by the `PtrToArg` template in godot-cpp. It is missing one level of pointer indirection, passing the void* wrapper directly to the `gdnative_object_get_instance_binding` implementation, which expects a `Object*`.
This patch adds the additional pointer dereference, which brings it in line with the core Godot `PtrToArg` template.
This fixes #651
=> Fixed pointer indirection in the PtrToArg template for Object arguments.

include/godot_cpp/classes/wrapped.hpp
This is an attempt to make the lifecycle of wrapped objects clearer.
Godot keeps track of bindings' userdata for each object it creates.
This allows allocating the memory of the wrapper only once per object even if that object is passed multiple times between binding code and godot code.
The binding information is composed of multiple functions, this includes a callback for when the userdata is to be allocated (called once) and for when the userdata is to be deallocated (again, called once).
When allocating data with "memnew" we set the object bindings during the postinitialize phase, but surely we shouldn't do that when allocating the userdata as a result of bindings callback themselves.
Additionally, since we let Godot handle (and track) raw memory allocation and de-allocation, we need …
=> Fix "_instance_bindings != nullptr" for Wrapped objects.

tools/windows.py
Previously, Windows builds were being produced without debug
information, leading to somewhat unhelpful backtraces etc.
without symbols.
This builds the symbols in (only for debug builds - I've
deliberately not touched release builds here) so gdextension
bugs are a little more tractable.
Test-Information:
Have been running this patch for weeks, and getting useful
traces out on the commandline, and useful debugging from
debuggers.
=> Add debug information to Windows builds

include/godot_cpp/classes/wrapped.hpp
The unqualified ClassDB friending was causing (at least for me on
VS2022) an implicit forward declaration of ClassDB in the namespace
of my class, instead of using the godot namespaced one. By qualifying
the namespace, this compiles for me.
Test-Information:
My project builds now.
=> Allow GDCLASS in own namespaces

godot-headers/godot/gdnative_interface.h, include/godot_cpp/core/class_db.hpp
A sister commit to https://github.com/godotengine/godot/pull/64334.
=> Add support for `property_*_revert` methods

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/defs.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/core/object.hpp, include/godot_cpp/core/property_info.hpp, test/demo/main.gd, test/demo/main.tscn, test/src/example.cpp, test/src/example.h
Adds support for implementing custom `_notification`, `_set`, `_get`, `_get_property_list` `_property_can_revert`, `_property_get_revert`, and `_to_string` methods in the GDExtension classes, adds tests for these methods to the demo project (as well as minimal class example, without these methods to ensure all of them are optional).
Supersede #815
Depends on https://github.com/godotengine/godot/pull/64721 (without it, demo will crash if opened in the editor, since engine pass `String` argument instead of `StringName`).
=> Add support for implementing special virtual methods.

binding_generator.py
Fix for forward declaration of structs that exists in "native_structures" and earlier was declared as structs to prevent linking errors on MSVC
=> Native structures forward declaration

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/error_macros.hpp, include/godot_cpp/core/memory.hpp
The `GDCLASS` macro should not assume to be called inside the `godot` namespace and should thus prefix function calls for that namespace with `::godot::` to ensure proper namespace referencing.
I suggest we also split the "internal" stuff (used by generated bindings) from `wrapped.hpp` into a separate `wrapped_internal.hpp` file to further convey the idea that `GDCLASS` is for users, but direct access to `Wrapped` and the `GDNATIVE_CLASS` macro are for internal use.
=> Ensure GDCLASS can be used outside the godot namespace.

binding_generator.py
This fixes a bug where constants were not generating. Fixes #827
=> Generate constants in the bindings generator

.github/workflows/ci.yml, .gitignore
This PR does three small things:
* Update the CI to use Godot 3.5-stable instead of Godot 3.4-stable.
* Update the static checks CI to have a 📊 emoji.
* Update the .gitignore to ignore master's `gen/` folder (to avoid those files showing up when switching branches).
=> Upgrade 3.x CI to Godot 3.5-stable

.github/workflows/ci.yml, .gitignore
This PR does two small things:
* Update the .gitignore to ignore 3.x's generated folders (to avoid those files showing up when switching branches).
* Update the static checks CI to have a 📊 emoji, and make Windows/Linux builds have 🏁 and 🐧 emojis.
=> Add Godot 3.x ignores to the .gitignore file in master

.github/workflows/ci.yml, binding_generator.py, misc/scripts/check_get_file_list.py
Adds a CI static check for it.
Was also the cause of intermittent CI failures, affecting both CMake and SCons since they both rely on `get_file_list`.
=> Fix get_file_list not returning all generated files.

CMakeLists.txt, include/godot_cpp/core/math.hpp, include/godot_cpp/templates/hashfuncs.hpp, test/CMakeLists.txt, test/src/register_types.cpp, test/src/tests.h, tools/windows.py
Including hashfuncs (or any `hash_*` template) was broken and causing build error due to missing functions.
```
In file included from /media/SSD/Code/git/godot-cpp-dev/include/godot_cpp/templates/hash_map.hpp:36,
from src/tests.h:35,
from src/register_types.cpp:40:
/media/SSD/Code/git/godot-cpp-dev/include/godot_cpp/templates/hashfuncs.hpp: In static member function 'static uint32_t godot::HashMapHasherDefault::hash(const godot::Vector4i&)':
/media/SSD/Code/git/godot-cpp-dev/include/godot_cpp/templates/hashfuncs.hpp:211:16: error: 'hash_murmur3_one_32' was not declared in this scope; did you mean 'hash_djb2_one_32'?
211 |   uint32_t h = hash_murmur3_one_32(p_vec.x);
|                ^~~~~~~~~~~~~~~~~~~
|                hash_djb2_one_32 …
```
=> Update hashfuncs, add some missing math funcs.

include/godot_cpp/templates/self_list.hpp, test/src/tests.h
Adds the (tiny template) `SelfList` data structure from Godot core ([core/templates/self_list.h](https://github.com/godotengine/godot/blob/master/core/templates/self_list.h)).
I'm trying to make a physics server by partly mimicking Godot Physics, which uses this data structure. It could be useful to others for the same reason.
=> Add SelfList template

godot-headers/godot/gdnative_interface.h, src/variant/variant.cpp
For https://github.com/godotengine/godot/pull/65325.
Some of the methods in Variant are specialized for animation use, so they are ported as static methods of Animation.
=> Move some methods to Animation from Variant

include/godot_cpp/classes/ref.hpp, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/core/property_info.hpp, include/godot_cpp/core/type_info.hpp, src/core/class_db.cpp, test/src/example.cpp, test/src/example.h
Improves ability to dynamically define properties, without handling `char *` allocation / de-allocation manually.
=> Change PropertyInfo members to String.

include/godot_cpp/classes/wrapped.hpp
`_get` was using `_set` internally, and should be `const`. `_get_property_list` should be `const`.
=> Fix issues with `_get` and `_get_property_list`

include/godot_cpp/variant/vector4.hpp, src/variant/vector4.cpp
Attempt to fix [#65997](https://github.com/godotengine/godot/issues/65997). Solves the compile errors, but instead crashes on project load.
=> Add missing Vector4 function bindings

binding_generator.py, include/godot_cpp/core/object.hpp
Before it wasn't possible to use `Object::cast_to(obj)` if `obj` was a `const T*`. Godot does the same thing: https://github.com/godotengine/godot/blob/908795301b9e4fcf24b115329a48d7d295c13a1a/core/object/object.h#L734-L764
=> Add `Object::cast_to` for `const Object*`

include/godot_cpp/variant/basis.hpp, src/variant/basis.cpp, src/variant/transform3d.cpp
To reflect documented names.
https://docs.godotengine.org/en/latest/classes/class_basis.html#class-basis
=> Use `quaternion` instead of `quat` in method names

.github/workflows/ci.yml, SConstruct, tools/android.py, tools/ios.py, tools/linux.py, tools/macos.py, tools/targets.py, tools/windows.py
`optimize = auto|none|debug|speed|size|0|1|2|3`
`debug_symbol = True|False`
optimize == "auto" will produce:
- "debug" for `target="debug"` builds
- "speed" for `target="release"` builds
- ~Add a release_debug target.~ Dropped, should be moved to a separate PR after discussion on: https://github.com/godotengine/godot-proposals/issues/3371
~Depends on: #836~ Merged
=> [SCons] Add "optimize" and "debug_symbols" options.

.github/actions/godot-cache/action.yml, .github/workflows/ci.yml
Followup on #838 .
Should make @akien-mga happy that we don't needlessly clog CI anymore :wink:
=> [CI] Add concurrency and scons caching.

include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/transform2d.hpp, include/godot_cpp/variant/transform3d.hpp, src/variant/basis.cpp, src/variant/projection.cpp, src/variant/rect2.cpp, src/variant/transform2d.cpp
This PR is the same as https://github.com/godotengine/godot/pull/60627 but for godot-cpp.
There are still more changes needed to sync these types with the engine, but this rename is the single largest/noisiest change, so I think it deserves a PR of its own.
=> Rename Transform2D and Basis `elements` to `columns` and `rows` respectively

include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4.hpp, include/godot_cpp/variant/vector4i.hpp, src/variant/vector2.cpp, src/variant/vector3.cpp, src/variant/vector3i.cpp, src/variant/vector4.cpp, src/variant/vector4i.cpp
This PR updates godot-cpp with recent changes to Vector2/2i/3/3i/4/4i in the engine.
=> Update Vector2/2i/3/3i/4/4i to match the engine

binding_generator.py, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, src/core/class_db.cpp
=> Fix deriving a custom class with virtual methods

binding_generator.py, include/godot_cpp/core/defs.hpp, include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/color.hpp, include/godot_cpp/variant/plane.hpp, include/godot_cpp/variant/projection.hpp, include/godot_cpp/variant/quaternion.hpp, include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/rect2i.hpp, include/godot_cpp/variant/transform2d.hpp, include/godot_cpp/variant/transform3d.hpp, include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4.hpp, include/godot_cpp/variant/vector4i.hpp, src/variant/variant.cpp
This PR does three things:
* Change `class` to `struct` for the core data structures and adjusts the bindings generator to handle this.
* Add `_NO_DISCARD_` to core data structures to match the engine.
* Remove `_native_ptr` from core data structures to match the engine (it's just a void pointer cast).
Why change `class` to `struct`? Here are several reasons:
* It matches what the core engine uses.
* `struct`'s default visibility is `public`, which all members are now that `_native_ptr` has been removed.
* `class` and `struct` are actually different things on MSVC. With godot-cpp's types defined with `class`, any forward declarations copied from an engine module like `struct Vector2;` will not work correctly on MSVC. This is actually something that I discovered after starting work on this …
=> Use `struct` instead of `class` for core structures

binding_generator.py, include/godot_cpp/core/binder_common.hpp
Fixes #868.
This issue also manifests when implementing `PhysicsServer3DExtension` due to its interface relying on `Vector3::Axis` which currently has no binding.
This PR replicates what is [already happening](https://github.com/godotengine/godot/blob/61021c08f80856f8d99dfbe9fd3d338ef5f41999/core/variant/binder_common.h#L132-L163) on the editor side of things with regards to binding global and built-in enums.
It adds a new generated file called `<godot_cpp/variant/builtin_binds.hpp>` that contains a `VARIANT_CAST_ENUM` for every enum in every _included_ built-in type. This file is then included in `binder_common.hpp` to emulate the set of hardcoded `VARIANT_CAST_ENUM` that currently exists on the editor side of things (see link above).
This PR also changes …
=> Bind enums in built-in types and expose bindings for global constants

Makefile
Fixes #882.
Adds a default `usage` target that lists the available targets. The previous default would build Windows and Linux 32-bit + 64-bit and that's pretty arbitrary (and unlikely to be what most users want by default when they start with godot-cpp).
Removed the couple arbitrary extra options which we offered, now they should be specified using `EXTRA_OPTIONS` to pass to SCons directly.
---
I really don't see the point of this Makefile so if preferred we can also just delete it.
It's literally just making it possible to call `make linux64` instead of `scons p=linux`...
=> Update Makefile after recent buildsystem changes

include/godot_cpp/core/math.hpp, include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/color.hpp, include/godot_cpp/variant/plane.hpp, include/godot_cpp/variant/projection.hpp, include/godot_cpp/variant/quaternion.hpp, include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/rect2i.hpp, include/godot_cpp/variant/transform2d.hpp, include/godot_cpp/variant/vector4i.hpp, src/variant/aabb.cpp, src/variant/basis.cpp, src/variant/color.cpp, src/variant/plane.cpp, src/variant/projection.cpp, src/variant/quaternion.cpp, src/variant/rect2.cpp, src/variant/rect2i.cpp, src/variant/transform2d.cpp, src/variant/vector4i.cpp
Here's a big PR that updates the core data structures in godot-cpp to match the engine (with several exceptions). Tentatively includes https://github.com/godotengine/godot/pull/67011. Note: The single big thing missing is Color's OKHSL methods since that requires a third-party library (I'm not sure if it's worth including in godot-cpp).
=> Update core data structures to match the engine

src/godot.cpp
Fixes #890.
Flipping the order of `ClassDB::deinitialize` and `terminate_callback` seems to fix the issue, and mirrors what's already happening in [`GDExtensionBinding::initialize_level`](https://github.com/godotengine/godot-cpp/blob/6696bebfa6b57d529172bf6ad679ed1b793fccb3/src/godot.cpp#L70-L78).
=> Fix use-after-free when deleting objects from extension terminator

godot-headers/godot/gdnative_interface.h, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/method_bind.hpp, src/core/class_db.cpp
This is related the fix for once https://github.com/godotengine/godot/pull/67138 is merged
=> Use enum type in GDExtension info structs for better readability

godot-headers/godot/gdnative_interface.h, include/godot_cpp/core/class_db.hpp, test/src/example.h, test/src/register_types.cpp
Core PR: https://github.com/godotengine/godot/pull/66979.
*Bugsquad edit:* Fixes https://github.com/godotengine/godot-cpp/issues/872
=> Add support for virtual and abstract classes

include/godot_cpp/core/method_ptrcall.hpp
Re-synced with [upstream](https://github.com/godotengine/godot/blob/master/core/variant/native_ptr.h#L127) (where we should move `AudioFrame` out of core and into servers, since that's auto-generated).
=> Add missing bindings for GDNativePtr<void>.

tools/windows.py
The c++ standard is added as part of the main SConstruct.
Fixes #906
=> [SCons] Remove bogus CCFLAGS from windows toolchain.

binding_generator.py, godot-headers/godot/gdnative_interface.h, include/godot_cpp/classes/ref.hpp, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/binder_common.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/core/object.hpp, include/godot_cpp/core/property_info.hpp, include/godot_cpp/core/type_info.hpp, src/classes/wrapped.cpp, src/core/class_db.cpp, src/core/method_bind.cpp, src/core/object.cpp, src/variant/variant.cpp
related to https://github.com/godotengine/godot/pull/67750
=> Uses `StringName` in GDExtension perf critical instance creation & method/properties setter/getter

include/godot_cpp/classes/wrapped.hpp
fix #918 
Note the second commit in this PR modify the test to remove the use of `using namespace godot;`, from my point of view this has both pros and cons:
- pros: help detect namespace isolation leak like we saw here ^^
- pros: further show the difference between macros and regular functions (given macros are totally separated from namespace), this is important for `D_METHOD` which looks like a macro but is in fact a method (hence the `GDCLASS(...)` vs `godot::D_METHOD(...)`)
- cons: the example is more verbose and less idiotic which is not great given it is the primary example one will refer to when learning Godot-CPP...
So what do you think ?
I guess the best of both worlds would be to have two separates folders: one for example and another for test (the latter typically being also …
=> Fix namespace isolation in GDCLASS macro

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/memory.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/godot.hpp, include/godot_cpp/templates/cowdata.hpp, include/godot_cpp/templates/hashfuncs.hpp, include/godot_cpp/templates/rb_set.hpp, include/godot_cpp/templates/rid_owner.hpp, include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/plane.hpp, include/godot_cpp/variant/quaternion.hpp, src/variant/basis.cpp, src/variant/projection.cpp
- remove extraneous semicolons
- use "nullptr" instead of "0"
- remove "break" after "return"
- use &lt;cstdio&gt; instead of &lt;stdio.h&gt;
=> Basic static analysis fixes

tools/targets.py, tools/windows.py
Select windows runtime in "targets" tool, use "/MDd" flag only when building with optimize="none" and optimize="debug".
Fixes #917 .
=> [SCons] Link MSVC debug runtime for optimize=none|debug only.

include/godot_cpp/classes/wrapped.hpp
fix #921
This fix makes sure the StringName don't get destroyed if they were only held by the `List<PopertyInfo>` (most of the time the StringName has been returned by `get_class_static` and hence have a global lifetime, however if `_get_property_list` return a custom list of property this is not the case... )
=> Fix lifetime of StringName objects returned by Wrapped::_get_property_list

CMakeLists.txt
- instead of setting globals which can effect other projects including this as a subdirectory, set them on the target if possible
- add "CONFIGURE_DEPENDS" to GLOBs to check for changes
- update required CMake version to 3.12 (still ancient - 2018) to support these
=> {cmake} Updates for target-based approach

test/demo/main.gd, test/demo/main.tscn, test/src/example.cpp, test/src/example.h
This changes some of the test logic to properly check `Ref<...>` scenarios.
We now check:
- return empty referenced objects
```
returned empty ref <Object#null>
```
- return an instanced object by pointer
```
ExampleRef 1 created, current instance count: 1
returned ref -9223372010229333393 , id: 1
```
- receiving an instanced object (as well as returning an instance object by reference)
```
ExampleRef 2 created, current instance count: 2
ExampleRef 3 created, current instance count: 3
Example ref checks called with value: -9223372010212556172, returning value: -9223372010195778844
sending ref:  -9223372010212556172 returned ref:  -9223372010195778844
```
We also output some id's and counts on constructing/destructing `ExampleRef` so we can see if the output is correct
```
ExampleRef 3 …
```
=> Change example code to properly test refcounted objects

include/godot_cpp/core/type_info.hpp
In Godot, Bitfields have long been updated to `int64_t`
https://github.com/godotengine/godot/blob/cd855f6516d48ff960cd904d29abbb324149f3c8/core/variant/type_info.h#L285-L296
=> Use `int64_t` for `BitField` as in Godot itself

godot-headers/godot/gdextension_interface.h, include/godot_cpp/classes/ref.hpp
The godot-cpp side of https://github.com/godotengine/godot/pull/69902
This uses the two new functions introduced in Godot so we can properly handle Godot supplied `Ref<T>` pointers and get/set our objects.
=> Fix virtual GDExtension method Ref<T> conversion

.github/workflows/ci.yml, binding_generator.py
Hello,
Currently, `build_library=no` does not work at the repository's root. (It generates a dependency cycle and scons refuses to generate anything).
To reproduce:
`scons generate_bindings=yes build_library=no` in `godot-cpp` 
Or `rm gen -r` before `scons build_library=no` in `godot-cpp`
Should give something like:
```
scons: *** Found dependency cycle(s):
gen -> gen/include/godot_cpp/classes/text_server_manager.hpp -> gen/include/godot_cpp/classes -> gen/include/godot_cpp -> gen/include -> gen
```
This PR solves this, by not stating that `gen/` is a target itself.
Also invert arguments to env.Clean, to call it as is documented in https://scons.org/doc/4.4.0/HTML/scons-user/apd.html.
I added a CI step to check this does not regress. I clean the generated sources before the actual build, …
=> Make build_library=no usable at godot-cpp's root

src/variant/char_string.cpp
This PR changes the `CharString`-producing methods of `String` to pass the correct length, which should be the size without null-terminator included, to line up with what `String::length()` returns.
This PR also addresses a (harmless) bug of these functions passing size with null-terminator included to `string_to_*_chars` when it should have been passing size without null-terminator included, since it ends up getting clamped anyway, as seen [here](https://github.com/godotengine/godot/blob/eba33c67b49905973ee7c81a709046415a41e205/core/extension/gdextension_interface.cpp#L632).
I commented about this in [#633](https://github.com/godotengine/godot-cpp/issues/633#issuecomment-1342717656), but I figured this leans more towards being a bug, so I decided to make a PR for it, so it doesn't fall …
=> Fix incorrect length passed to `CharString`

SConstruct, tools/windows.py
Create the SCons Environment with an empty PLATFORM variable to force the default tools to use the GNU toolchain.
Platform specific toolchains are then setup in our custom tools.
Fixes #937
=> [SCons] Platform agnostic default toolchain (GNU).

binding_generator.py
Fixes https://github.com/godotengine/godot/issues/62935
On the engine side, enum values are always 64-bit, so use `int64_t` temporary return variable to avoid stack corruption.
=> Fix enum return value size.

include/godot_cpp/core/binder_common.hpp, test/demo/main.gd, test/src/example.cpp, test/src/example.h
As done in upstream Godot via GH-57205.
Add a test that ensures it works also for "gdextended" objects.
See godotengine/godot#57205
=> Allow method binds to take Object subclasses as arguments

.github/workflows/ci.yml, CMakeLists.txt, SConstruct, binding_generator.py, misc/scripts/check_get_file_list.py
This makes the build system consistent with Godot again; see https://github.com/godotengine/godot/pull/67399.
~~TODO:~~
Also fixes the CMake build to define `REAL_T_IS_DOUBLE` when needed.
=> Rename `float=64` build option to `precision=double`

include/godot_cpp/classes/ref.hpp, include/godot_cpp/core/binder_common.hpp, include/godot_cpp/core/type_info.hpp
Supersedes #810
Rebased and fixed. Also added `PropertyInfo` for `Ref<T>`
#948 is required for a successful build
```
Constructor.
Notification: 18
Notification: 31
Notification: 32
Notification: 45
Notification: 10
Notification: 27
Notification: 13
Signal bind
To string
Example -->  Example:[ GDExtension::Example <--> Instance ID:26541556118 ]
ExampleMin -->  ExampleMin:[Wrapped:0]
Static method calls
static (109) 109
void static
Property list
property value  (100, 200, 300)
Instance method calls
Simple func called.
Simple const func called.
typed_ptr_parameter called: Example:[ GDExtension::Example <--> Instance ID:26541556118 ] <----------------------
typed_const_ptr_parameter called: Example:[ GDExtension::Example <--> Instance ID:26541556118 ] <----------------
Return something …
```
=> Added property info for Object's and Ref's and ported the implementation of the `check` method

include/godot_cpp/variant/variant.hpp, src/variant/variant.cpp
These conversions already exist in core but were missing from `godot-cpp`. We don't strictly need them because conversion between `ObjectID` and `uint64_t` exists, but it's a simple addition and it makes writing GDExtensions more convenient.
For example, trying to call the area monitor callback in a physics server GDExtension should look similar to [the way it is done in core](https://github.com/godotengine/godot/blob/57267709e665f1683e79bd5d3432be2be5db6c1d/servers/physics_2d/godot_area_2d.cpp#L237-L250). Before this PR that code would not compile in a GDExtension, and `E->key.instance_id` would have to be replaced by `(uint64_t)E->key.instance_id`.
=> Add conversions between `Variant` and `ObjectID`

src/variant/variant.cpp
An uninitialized value was being returned instead of the function return value.
=> Fix Variant::can_convert[_strict] returning gibberish.

include/godot_cpp/classes/wrapped.hpp
Deleting an object through a pointer to a base class is undefined behaviour unless the destructor in the base class is virtual.
=> "Wrapped" has virtual functions so it should have a virtual destructor.

README.md
See https://github.com/godotengine/godot-cpp/issues/807.
=> Add a more prominent warning about repository branches in README

include/godot_cpp/classes/wrapped.hpp
The `GDCLASS` macro requires declaration of `::godot::ClassDB` to satisfy `friend class ::godot::ClassDB`.
Currently all GDExtension/modules client code that I know of that uses this macro, needs to include `<godot_cpp/core/class_db.hpp>` on top of the wrapped object that it wishes to inherit (e.g Object with `#include <godot_cpp/classes/node.hpp>`).
I feel that this is confusing that this is required to satisfy a macro implementation detail and it is easily fixed using a forward declaration.
It is especially worse when not choosing to use `using namespace godot;` and having to forward declare in client code within the `godot` namespace.
EDIT: Could mode the declaration just above the macro definition for readability
=> Fix GDCLASS needs explicit ClassDB fwd declaration

CMakeLists.txt
From the cmake docs:
> This may have effects such as suppressing warnings or skipping the contained headers in dependency calculations (see compiler documentation). Additionally, system include directories are searched after normal include directories regardless of the order specified.
Addresses part of #999
=> {cmake} Add GODOT_CPP_SYSTEM_HEADERS option to mark includes as SYSTEM

include/godot_cpp/core/method_bind.hpp
=> Fix some sign comparison warnings

include/godot_cpp/core/math.hpp
- Fixes #551.
- Supersedes #553.
=> Change behavior of Math::sign to match Godot builtin

binding_generator.py, include/godot_cpp/core/memory.hpp
The API JSON has changed syntax for default values of typed arrays. This detects the new format and use initializer lists (currently empty since the TypedArray class does not support initializer list construction and
default values are always empty arrays).
The format is changed by https://github.com/godotengine/godot/pull/69248 **Note:** This PR works with both the old and new format, so it won't break anything even if merged before the change in Godot.
I snuck in a change in the `memory.hpp` to remove an annoying compiler warning. It just does what has been done in Godot a while ago.
=> Support typed array default values in extension API 

binding_generator.py, include/godot_cpp/core/binder_common.hpp, include/godot_cpp/core/type_info.hpp, test/demo/main.gd, test/src/example.cpp, test/src/example.h
This PR changes how `Enums` and `Bitfields` are registered, and also corrects the names of registered enums. Breaks compatibility.
Previously `VARIANT_ENUM_CAST` could be written in 3 ways:
```cpp
VARIANT_ENUM_CAST(Example, Example::Constants);
VARIANT_ENUM_CAST(Example, Constants);
VARIANT_ENUM_CAST(, Constants);
```
The first way was used throughout the generated API. At the same time, `VARIANT_BITFIELD_CAST` could only be written like this:
```cpp
VARIANT_BITFIELD_CAST(Example, Example::Flags);
```
This would not be a problem if such a way of writing would not lead to an incorrect display of enums in the editor.
I changed it to be the same as in Godot itself. Now `VARIANT_ENUM_CAST` and `VARIANT_BITFIELD_CAST` can be written like this:
```cpp
VARIANT_ENUM_CAST(Example::Constants); …
```
=> Fixed `VARIANT_ENUM/BITFIELD_CAST` to show the correct names

include/godot_cpp/core/memory.hpp
`DefaultTypedAllocator` needs to come after `memdelete`. This only is an error if you try to use `DefaultTypedAllocator` which I am currently using in my project.
=> Move DefaultTypedAllocator after memdelete

binding_generator.py
- remove unused vars
- fix a few f-strings
- remove f-string notation where not used
=> Binding generator cleanups

binding_generator.py, gdextension/gdextension_interface.h, include/godot_cpp/variant/typed_array.hpp, src/variant/packed_arrays.cpp
Part of https://github.com/godotengine/godot/pull/69248
=> Update typed array API to match "GDScript: Fix typed arrays".

CMakeLists.txt, cmake/GodotCompilerWarnings.cmake
Turns on compiler warnings based on the [SConstruct file in godot](https://github.com/godotengine/godot/blob/d93b66ad4d6b1dae42cc318c16224d03bd1a1472/SConstruct#L680-L761).
Also adds `GODOT_CPP_WARNING_AS_ERROR` option to treat warnings as errors. This is turned ON when building godot-cpp on its own (e.g. CI), but defaults to OFF if godot-cpp is being included in another project.
(CMake part of #999)
=> {cmake} Use the same compiler warnings as godot

gdextension/gdextension_interface.h, include/godot_cpp/core/error_macros.hpp, src/core/error_macros.cpp, src/variant/transform2d.cpp
Fixes #963.
Depends on godotengine/godot#71865.
This brings the error macros in line with what's available in core as of writing this.
Besides fixing the above mentioned issue, this also introduces the new `*_ED*` macros, which will create a toast notification in the editor through the newly exposed `bool p_editor_notify` parameter.
It also removes `DEBUG_STR`, which was used to remove error messages in non-debug builds, meaning error macros now log everything in non-debug builds as well.
I decided to implement `_err_flush_stdout` directly in godot-cpp instead of going through the GDExtension interface. It seemed too trivial to burden the GDExtension interface with, and the standard input/output handles should be the same inside the library as its parent process anyway.
=> Update error macros to match core

binding_generator.py
Fix another issue about compile error of missing `godot::ArgToPrt<godot::BitField<godot::PropertyUsageFlags>>` and  `godot::ArgToPrt<godot::Variant::Type>`.
Occur in `EditorInspectorPlugin::_parse_property(Object *object, Variant::Type type, const String &name, PropertyHint hint_type, const String &hint_string, BitField<PropertyUsageFlags> usage_flags, bool wide)`.
=> Fix global enum cast and add `Varint::Type`'s cast.

CMakeLists.txt
Makes all include directories consistent.
Turns `GODOT_CPP_SYSTEM_HEADERS` ON by default since that's what was already being done for `${GODOT_GDEXTENSION_DIR}`.
=> {cmake} Combine target_include_directories

src/variant/packed_arrays.cpp
Prerequesite for https://github.com/godotengine/godot/pull/72926.
=> `array_set_typed()` now called with `GDExtensionVariantType` instead of `uint32_t`

include/godot_cpp/core/object.hpp
Fixes #995 and https://github.com/godotengine/godot/issues/71332
I tried a bunch of different variations on this, including using `p_object->is_class(class_name)` to check if the object was the right type, AND making changes in the Godot engine itself in `gdextension_object_cast_to()` (which would break the GDExtension ABI, but Remi actually said that would be fine while GDExtension is experimental :-)).
However, assuming there isn't some case where this won't work that I didn't think of, I like the version in this PR the best so far!
It's switching to `dynamic_cast<T>` at the end, which means C++ will check if the final class matches the requested type using RTTI. This should be much faster than `p_object->is_class(class_name)` (since that relies on walking up the inheritance chain and …
=> Fix Object::cast_to<T>() for custom classes

include/godot_cpp/core/object.hpp
This reverts PR #1037
I think I've got a way to fix the regressions and maintain the fixes from PR #1037, but it's kind of involved (requires a change on the Godot engine side, and a new generated file in godot-cpp) and so will probably require a bunch of review and back-and-forth. With the 4.0 stable release coming soon, let's just revert this for now, and I can finish a proper fix after 4.0 :-)
Fixes #1042
Fixes #1043
Re-opens #995
Re-opens https://github.com/godotengine/godot/issues/71332
=> Revert "Fix Object::cast_to<T>() for custom classes"

.github/workflows/ci.yml, include/godot_cpp/core/memory.hpp, include/godot_cpp/templates/cowdata.hpp, src/core/memory.cpp
Fixes https://github.com/godotengine/godot-cpp/issues/842
=> Fix incorrect memory allocation in release builds.

include/godot_cpp/core/method_ptrcall.hpp
Fixes #1020, fixes #1025 (only for `Object*` parameter crash, `Ref<Object>` crash reported recently is a different issue).
`*reinterpret_cast<GDExtensionObjectPtr *>` -> `reinterpret_cast<GDExtensionObjectPtr>` as the real type of `p_ptr` is `Object*` not `Object**`.
=> Fix crash using Object* as parameter

CMakeLists.txt
`
CMake Warning (dev) at CMakeLists.txt:40 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
`
=> Moved cmake_minimum_required() call to top

README.md
Not sure if there is any procedure for PRs on this repo / template that I am missing, hopefully not.
When updating, I noticed that the implementation of the demo extension was changed with #1095 , but the corresponding README.md sections were not updated, so I figured I might as well make a PR.
=> Update Getting Started section of README.md

binding_generator.py, gdextension/gdextension_interface.h, include/godot_cpp/classes/ref.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/engine_ptrcall.hpp, include/godot_cpp/core/method_ptrcall.hpp, include/godot_cpp/core/object.hpp, include/godot_cpp/godot.hpp, src/core/class_db.cpp, src/core/object.cpp, src/godot.cpp, src/variant/variant.cpp
As discovered after merging PR #1037 (which was later reverted), when a Godot engine class is created on the Godot side and then passed to GDExtension, the GDExtension class that is created may not be of the correct type (most often it'll be created as `godot::Object` and then be unsafely cast to the correct class, which could lead to strange/incorrect behavior later).
This is explained in detail in these two comments:
- https://github.com/godotengine/godot-cpp/issues/1042#issuecomment-1432251538
- https://github.com/godotengine/godot-cpp/issues/995#issuecomment-1434345271
This PR aims to ensure that the GDExtension class that's created to wrap a Godot engine class always matches the Godot class it wraps.
This is a draft currently, because there is still more that I'd like to do:
- ~~This …
=> Ensure GDExtension class is the correct type for the Godot engine class

include/godot_cpp/classes/ref.hpp
This is the godot-cpp counterpart for godotengine/godot#64789
Fixes #693 
(pinging @akien-mga since he requested this)
=> Change Ref<T> to allow non const access to ptr

binding_generator.py, gdextension/gdextension_interface.h, include/godot_cpp/godot.hpp, src/godot.cpp
This depends on https://github.com/godotengine/godot/pull/77010
It allows adding or removing editor plugins from GDExtension, in a way that's very similar to adding them in a Godot module.
Here's some example code from a test GDExtension:
```cpp
void initialize_summator_types(ModuleInitializationLevel p_level)
{
if (p_level == MODULE_INITIALIZATION_LEVEL_SCENE) {
ClassDB::register_class<Summator>();
}
if (p_level == MODULE_INITIALIZATION_LEVEL_EDITOR) {
ClassDB::register_class<MyEditorPlugin>();
EditorPlugins::add_by_type<MyEditorPlugin>();
}
}
void uninitialize_summator_types(ModuleInitializationLevel p_level) {
if (p_level == MODULE_INITIALIZATION_LEVEL_SCENE) {
EditorPlugins::remove_by_type<MyEditorPlugin>();
}
}
```
Please let me know what you think!
Fixes #640
=> Add support for adding/removing editor plugins

gdextension/gdextension_interface.h
At the moment, the gdextension_interface.h in godot-cpp doesn't match the gdextension_interface.h in Godot.
These getting out-of-sync was my fault: with all the rebasing I did around https://github.com/godotengine/godot/pull/35813 and https://github.com/godotengine/godot/pull/76406, the version of gdextension_interface.h that ended up getting committed to godot-cpp is somehow missing the changes from https://github.com/godotengine/godot/pull/35813.
But it's an easy fix :-)
=> Synchronize gdextension_interface.h with Godot

src/godot.cpp
=> Clarify error message because there isn't a legacy Godot 4.0 mode anymore

binding_generator.py, test/project/main.gd, test/src/example.cpp, test/src/example.h
This should fix #1127 by changing the type of the return variable to match the actual type of the returned value.
=> Fixing #1127 by making return types of auto-generated functions dynamic

SConstruct
Currently if you try to use buildroot the same way you would for the engine, it will not work. It just dose not use it. After looking into it for awhile I noticed the engine prepends the os PATH to the scons env while godot-cpp does not. I tested it and this change allows the use of buildroot for godot-cpp.
=> Prepend PATH to scons env to allow use of buildroot

binding_generator.py, include/godot_cpp/classes/ref.hpp, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/core/type_info.hpp, src/core/object.cpp
https://timsong-cpp.github.io/cppwp/n3337/global.names
https://en.cppreference.com/w/cpp/language/identifiers
Identifiers appearing as a token or preprocessing token (i.e., not in user-defined-string-literal like operator ""id) (since C++11) of one of the following forms are reserved:
- identifiers with a double underscore anywhere;
- identifiers that begin with an underscore followed by an uppercase letter;
- in the global namespace, identifiers that begin with an underscore.
=> Identifiers containing double underscore are reserved according to the C++ standard

gdextension/gdextension_interface.h
A few methods in the GDExtension header construct their destination in-place, but the parameters are not declared using the `Uninitialized*` pointer types.
See Godot PR: https://github.com/godotengine/godot/pull/78419
---
Below are the relevant sections where placement new is used.
TypePtr constructors:
https://github.com/godotengine/godot/blob/116f783db73f4bf7e9e96ae54dd3d0a20337cc8a/core/variant/variant_construct.h#L45-L54
VariantPtr <-> TypePtr conversions:
https://github.com/godotengine/godot/blob/116f783db73f4bf7e9e96ae54dd3d0a20337cc8a/core/variant/variant_internal.h#L1535-L1546
=> GDExtension: `Uninitialized*Ptr` for constructors/converters using placement new

binding_generator.py
In, for example, `gen/include/godot_cpp/classes/audio_frame.hpp`, GDVIRTUAL_NATIVE_PTR cannot be found because there's a missing include for method_ptrcall.hpp. When native structures have classes, they'll include this header by way of other files, but if a structure does not include anything it's missing this header, I assume.
The final output for this example simply adds a line after the define guard:
```cpp
#include <godot_cpp/core/method_ptrcall.hpp>
```
Which removes the error.
=> Fix: Include method_ptrcall.hpp on simple structs.

include/godot_cpp/core/class_db.hpp, src/core/class_db.cpp
This should fix #914 , hopefully without any side effects.
=> Unregister custom classes in reverse registration order

src/godot.cpp
I ran across these while I was taking a look at what symbols were being exported from my extension a while back.
As best I can tell they're not actually used anywhere in godot-cpp, nor anywhere in Godot itself, and after bringing this up in the developer chat I was advised to make a pull request for removing them, so that we could explore that all together.
Everything seems to compile and run just fine without them, so I figured maybe they're some old remnants from a bygone era.
=> Remove unused free-standing `initialize_level` and `deinitialize_level`

.github/workflows/ci.yml
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
The Ubuntu 18.04 image was deprecated and removed last year. 3.x CI checks won't run without this PR.
=> [3.x] Bump Ubuntu version on CI from 18.04 to 20.04

SConstruct
This PR make it possible to import `env` and use it instead of creating one from scratch every time. 
Handy because we encourage users to use the godot-cpp SConstruct file as a base to their projects (see the test project). So, if a project want to override specific settings, (eg. make a path local to their SConstruct file, not local to the godot-cpp/SConstruct file), it can do so.
=> Import `env` if possible

.gitignore
Pretty much self-explanatory. I had issues where I had multiple new files added from ".cache", where only ".Cache" was ignored.
=> Add lower-case "*.cache" in ".gitignore"

binding_generator.py
This updates the generated method code to match what @BastiaanOlij suggested in [this comment](https://github.com/godotengine/godot-cpp/issues/1063#issuecomment-1632626552).
Currently, even though the method bind pointer itself is being cached (by virtual of being a local `static` variable), the `StringName` with the method name (which is only created as an intermediate value in order to get the method bind pointer) is still constructed every time the function is called.
With the changes in this PR, it should only be constructed the first time.
While this does probably improve performance, it will need more benchmarking to see if it sufficiently solves issue https://github.com/godotengine/godot-cpp/issues/1063, or if only helps things a little bit.
Fixes …
=> In generated methods, only allocate the method StringName the first time

include/godot_cpp/templates/cowdata.hpp, include/godot_cpp/variant/char_string.hpp, src/variant/char_string.cpp, test/project/main.gd, test/src/example.cpp, test/src/example.h
Fixes #1142
This copies `CharString` (along with `CharProxy`) from Godot, and then uses a template `CharStringT<T>` to avoid having to duplicate code for `CharString`, `Char16String`, `Char32String` and `CharWideString` (which are all essentially the same, just using a different character size).
It seems to be working, but I did only very limited testing, including adding a simple automated test that just calls `String.utf8()` and ensures it matches the expected value.
It could definitely use more testing!
=> Attempt to fully implement CharString

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, src/classes/wrapped.cpp
Fixes part of #1183
Related to https://github.com/godotengine/godot/pull/79683, the pair fixes #1183 completely.
Godot is already supposed to call `_get_property_list` of parent classes, so the binding function (`get_property_list_bind`) must really only return procedural properties of the class it belongs to, and not parent or child classes, just like core does.
So in fact, it is possible to simply pass null to Godot when `_get_property_list` is not defined in the class.
I also found out a few members of `Wrapped` weren't necessary, and was able to move some of the code away from the `GDCLASS` macro.
I believe there is a way to also not need `plist_owned` inside `Wrapped`, maybe storing it in a `thread_local`, which would also fix potential issues if `get_property_list` is called from …
=> Don't call parent _get_property_list when a class doesn't define it (for internal binding).

binding_generator.py
This fixes the third point of issue https://github.com/godotengine/godot-cpp/issues/1180 (and perhaps the second one if that was the cause all along, but havent checked that yet)
If you call `get_singleton` too early and it returns `nullptr`, it would keep returning `nullptr` forever.
=> Don't cache `null` forever if a singleton isn't available yet

tools/android.py, tools/ios.py, tools/javascript.py, tools/linux.py, tools/macos.py, tools/windows.py
Add platform macros, like `LINUX_ENABLED` and `UNIX_ENABLED` on Linux, `MACOS_ENABLED`, `UNIX_ENABLED`, ~~`COREAUDIO_ENABLED`, `COREMIDI_ENABLED`~~ on macos, and `WINDOWS_ENABLED`, ~~`WASAPI_ENABLED`, `WINMIDI_ENABLED`~~ on Windows.
=> Add platform macros

SConstruct
=> [SCons] Add option to generate a compilation database.

tools/targets.py, tools/windows.py
This builds on PR https://github.com/godotengine/godot-cpp/pull/1082, implementing the requested review, and removing some changes that seem unrelated to the goal of the PR.
This is still a draft because I haven't yet had a chance to try the MSVC-related changes. However, this is working in my testing with mingw.
Thanks to @feiyunw for making the original PR!
Fixes #1064 
Fixes #976
=> Statically link mingw/msvc runtime libraries on Windows

binding_generator.py
Generates a `core/version.hpp` file with macros similar to Godot's core `VERSION_*`. This allows to do conditional compilation in case of compatibility breakage between Godot versions.
=> Added generated version header

include/godot_cpp/templates/cowdata.hpp
It seems that Clang and GCC have different interpretations of certain builtins. So this PR fixes the "deprecated" builtins for Clang, but keeps them for GCC.
Fixes https://github.com/godotengine/godot-cpp/issues/1210
=> Fix Clang deprecated builtins

include/godot_cpp/templates/cowdata.hpp
=> Fix forgotten not operator

tools/targets.py
- Reorders existing code to match Godot.
- Adds `NDEBUG` for non-dev builds.
- Adds `-gdwarf-4` for Clang debug symbols.
- Adds strip link flag for GCC/Clang builds without debug symbols.
Follow-up to #1203.
The additions are up to discussion, if some seem unwanted in the context of GDExtension, I can remove them and document why we differ from upstream.
This syncs with:
https://github.com/godotengine/godot/blob/013e8e3afb982d4b230f0039b6dc248b48794ab9/SConstruct#L402-L437
and:
https://github.com/godotengine/godot/blob/013e8e3afb982d4b230f0039b6dc248b48794ab9/SConstruct#L574-L619
=> SCons: Sync `targets.py` fully with upstream Godot

include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4.hpp, include/godot_cpp/variant/vector4i.hpp
* See: https://github.com/godotengine/godot/pull/80223
=> Add remaining component-wise `min/max` functions to `Vector*`

SConstruct, tools/godotcpp.py
This cleans up the main SConstruct file, and should allow for more control over the build system.
This is a first pass, but by moving to a Tool we should then allow calling `env.GodotCPP` manually from extensions, giving the possibility of changing auto-detected options.
=> [SCons] Move the GodotCPP build to its own tool.

README.md, test/project/example.gdextension
Without quotes the values is parsed as a float, breaking in various cases.
* See: https://github.com/godotengine/godot-docs/issues/7864
=> Fix formatting of `compatibility_minimum` examples

binding_generator.py, include/godot_cpp/variant/variant.hpp
Implement builtin classes' vararg methods.
Need [#76047](https://github.com/godotengine/godot/pull/76047).
Now, `call()`, `call_deferred()`, `rpc()`, `rpc_id()`, `bind()` in `Callable`, and `Signal::emit()` can be called with any count of arguments.
Fixes #802
Fixes #1093
=> Implement vararg methods of builtin classes.

README.md, SConstruct, binding_generator.py, include/godot_cpp/templates/cowdata.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4.hpp, include/godot_cpp/variant/vector4i.hpp, test/project/example.gdextension, test/project/main.gd, test/project/project.godot, test/src/example.cpp, test/src/example.h, tools/godotcpp.py, tools/targets.py
The 2nd batch of PR's marked with `cherrypick:4.1`
=> Cherry-picks for the godot-cpp 4.1 branch - 2nd batch

gdextension/gdextension_interface.h, include/godot_cpp/classes/wrapped.hpp
Downstream equivalent of https://github.com/godotengine/godot/pull/81247.
=> GDExtension: fix `bool` unknown in C

include/godot_cpp/classes/wrapped.hpp
The pointer validity for casting is broken with multiple inheritance and possibly other situations, this ensures that pointers returned match the constness of the relevant functions
I'm assuming these are internal and don't affect compatibility in any way, most users likely aren't using multiple inheritance for interfaces etc. so probably why it has gone unnoticed
* Fixes: #1232
=> Ensure `const` correctness for wrappers

binding_generator.py, include/godot_cpp/core/method_ptrcall.hpp
Fixes https://github.com/godotengine/godot-cpp/issues/1207
This changes `binding_generator.py`, so that rather than forward declaring native structures (which will have their own specialization for `PtrToArg<>`), it will always make sure to include the header.
It also adds a `static_assert()` to the `PtrToArg<>` specialization for `Object`'s in order to ensure that it isn't ever used with a type that doesn't descend from `Object`. Using the MRP from https://github.com/godotengine/godot-cpp/issues/1207, if I comment out the fix in `binding_generator.py` then it will correctly fail to compile.
=> Ensure that PtrToArg specializations for native structs are used

SConstruct, tools/android.py, tools/godotcpp.py, tools/javascript.py, tools/macos.py
After moving most of the code from `SConstruct` to `godotcpp.py` (63755b2a32085fda8ab5d615264867e0c98b005a) some methods are no longer detected by the interpreter and require a call through the environment (that's how I understood it).
Also, the import of `UserError` was not moved.
Now these commands will not lead to crashes:
```
scons gdextension_dir=gdextension.file
scons custom_api_file=gdextension
scons compiledb_file=wrong/path_to.json
```
And the `generate_bindings` argument works again
```
scons generate_bindings=yes
```
Fixes #1236
The `Exit()` method should also be called from `env` and not return 0 on errors.
=> [SCons] Fixed crashes in several scripts

src/godot.cpp, test/project/project.godot
This builds on PR #1193 and adds something that we discussed on issue #1195:
That is, godot-cpp will compare the version of Godot it was built for (based on the `extension_api.json` that was used) with the version of Godot that is loading it, and ensure that they are compatible, ie. the version of Godot is equal to or greater than the version godot-cpp was built for.
In order to do this, it also:
- Updates the `extension_api.json` in the repo for Godot 4.2-dev3, since we still had the one from 4.1.1 in there.
- Fixes up the way that we're printing early error messages that happen before godot-cpp is fully initialized. In my testing, I was getting crashes, which I think were caused by the older method using `String`, because we made some small incompatible changes to `String` in 4.2. This …
=> Check that GDExtension is opened by compatible Godot version

gdextension/gdextension_interface.h, include/godot_cpp/core/class_db.hpp
Because of renaming gdnative to gdextension, I need to remake [#951](https://github.com/godotengine/godot-cpp/pull/951). Otherwise I can't keep 1 commit.
Need [#70329](https://github.com/godotengine/godot/pull/70329).
=> Implement register unexposed classes

gdextension/gdextension_interface.h, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/property_info.hpp, test/project/main.gd, test/src/example.cpp, test/src/example.h
This is the companion PR to Godot PR https://github.com/godotengine/godot/pull/81515
It allows object classes in GDExtension to implement `_validate_property()` to alter properties.
It includes a unit test that verifies that this functionality actually works!
=> Support `_validate_property()`

src/godot.cpp
I made a dumb mistake in PR https://github.com/godotengine/godot-cpp/pull/1208 :-(
We do a thing when godot-cpp is initialized, where we load the `print_error` function first, so we can show errors if any of the other functions fail to load. This means we don't need to load `print_error` later with the rest of the functions, but instead of removing the load for that, I accidentally removed the load for `print_error_with_message`, which means it was never getting loaded (and leading to a crash when triggering many of the error macros).
This PR fixes that.
=> Load 'print_error_with_message' function

binding_generator.py, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp
This works by:
- Generating a `ClassDBSingleton` class for the singleton, to avoid a conflict with the hand-written `ClassDB` that's used for registering classes, methods, etc
- Creating static methods on `ClassDB` that forward to the methods on `ClassDBSingleton`. These forward methods are generated into a preprocessor macro in `class_db_singleton.hpp` that is expanded inside the `ClassDB` class
This is an alternate way to implement PR https://github.com/godotengine/godot-cpp/pull/936 as I described in [this comment](https://github.com/godotengine/godot-cpp/pull/936#pullrequestreview-1474966855).
The primary difference between that PR and this one, is that you can call the methods statically on `ClassDB`, for example, as `ClassDB::get_class_list()` rather than …
=> Add static methods to `ClassDB` for the methods bound to the `ClassDB` singleton

gdextension/gdextension_interface.h, include/godot_cpp/core/class_db.hpp
This allows godot-cpp to continue working after merging Godot PR https://github.com/godotengine/godot/pull/80671
godot-cpp doesn't actually need the feature added in that PR; it's for languages that don't have a way to automatically generate new functions with C linkage, whereas C++ can do that just fine. But since that PR adds two new fields to the `GDExtensionClassCreationInfo2` struct, so we need to set them to `nullptr` in order to keep working with Godot `master`.
=> Update for addition of `get_virtual_call_data_func` and `call_virtual_func` to `GDExtensionClassCreationInfo2`

SConstruct
Updated version of #1196.
As explained [here](https://github.com/godotengine/godot-cpp/pull/1196#issuecomment-1682240391), the `env` passed from the parent SConstruct don't have the values from the custom files. So, in order to the custom files to be loaded in the godot-cpp project from the parent, it is essential to pass the "customs" variable.
=> Add support to import custom variables from parent SConstruct (redux)

src/core/class_db.cpp
This attempts to solve a problem that was brought up on issue https://github.com/godotengine/godot-cpp/issues/1160 (although, this PR *doesn't* solve that issue).
Basically, the problem is that we assume we'll have the instance binding callbacks for any valid wrapper class. If we don't have the wrapper class, we output an error message and use `Object`.
However, in either of these cases:
- the class is a new class that was added to Godot after the GDExtension was created (so it won't know about it), or
- the developer explicitly excluded the class from godot-cpp
... we want to do what we're already doing for unexposed classes, which is to find the closest parent class that we _do_ know about.
This will only output an error message, if we're unable to find any ancestor classes that we know …
=> Handle missing instance binding callbacks by finding the closest parent

gdextension/gdextension_interface.h, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, src/classes/wrapped.cpp, src/core/class_db.cpp, tools/godotcpp.py, tools/linux.py
These are the changes necessary to work with Godot PR https://github.com/godotengine/godot/pull/80284
=> Changes necessary for hot reload to work

gdextension/gdextension_interface.h
Updates godot-cpp to work with latest Godot master after PR https://github.com/godotengine/godot/pull/78995 which was recently merged
=> Update for `get_class_category` added to `GDExtensionScriptInstanceInfo2`

src/core/class_db.cpp
I took a stab at trying the hot-reloading system (in master) but when using my experimental/prototyping GDExtension (which exposes 2 Node types) but hit a bug:
When opening Godot (4.2-dev6) which loaded my extension (built with cd61a9bbe881b902750111eac8b02c04778f366b) my extension appears to run perfectly well. Closing Godot at any time will trigger an error due to invalid access to `std::vector` internals. Exact same issue when attempting a hot-reloading, at the moment we get the focus after changing the extension binary.
Note that this does not happen in the example provided in this project, but removing any active code or even usage in the project of my GDExtension , except the node classes registrations (2 types) systematically reproduces the issue for now (it's UB so it's random, …
=> Fixes crash in ClassDB::deinitialize due to usage of invalid iterator.

gdextension/gdextension_interface.h
The remaining changes to gdextension_interface.h that have been made in Godot 4.2 aside from what's in PR https://github.com/godotengine/godot-cpp/pull/1263
=> Miscellaneous updates to gdextension_interface.h

include/godot_cpp/variant/char_string.hpp
Related to #1150.
I'm in the process of upgrading godot-cpp from 1009da4d7e to 3b3f357de9, and when compiling with clang-cl (and maybe regular Clang as well?) I seem to end up with the following compilation error:
```
src/variant/char_string.cpp(95,32): error: explicit specialization of 'get_data' after instantiation
const char *CharStringT<char>::get_data() const {
^
include/godot_cpp/core/type_info.hpp(354,1): note: implicit instantiation first required here
MAKE_TYPED_ARRAY_INFO(bool, Variant::BOOL)
^
include/godot_cpp/core/type_info.hpp(342,128): note: expanded from macro 'MAKE_TYPED_ARRAY_INFO'
return make_property_info(Variant::Type::ARRAY, "", PROPERTY_HINT_ARRAY_TYPE, Variant::get_type_name(m_variant_type).utf8().get_data()); \
^
```
From what I can tell it seems like it gets …
=> Declare explicit specializations for `CharStringT`

binding_generator.py, include/godot_cpp/classes/editor_plugin_registration.hpp, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/godot.hpp, src/classes/editor_plugin_registration.cpp, src/classes/wrapped.cpp, src/godot.cpp
This is based on an idea from @maiself at a GDExtension meeting from a couple months ago!
In PR https://github.com/godotengine/godot-cpp/pull/1050, we added a `HashMap` that stores the binding callbacks for all engine types, in order to fix a serious bug where the wrapper class used could be an arbitrary parent class (rather than the actual engine class) leading to unexpected behavior in some situations.
Unfortunately, this led to issue https://github.com/godotengine/godot-cpp/issues/1160 where builds would be ~1-5mb bigger than previously.
This was due to the linker previously being able to optimize away any class that wasn't actually used in the GDExtension. However, if we have to reference every class in order to add their binding callbacks to the `HashMap`, they are all technically …
=> Automatically register only engine classes whose header has been included

tools/godotcpp.py
Right now, if you have a custom build of Godot to build against, you have to redundantly provide arguments for both a `gdextension_dir` and `custom_api_file`. This changes it so that, if only `gdextension_dir` is provided, it will implicitly setup a path for `custom_api_file` using the default name
=> Let `gdextension_dir` function as standalone argument

include/godot_cpp/variant/callable_method_pointer.hpp
Fixes #1272
+ clang++ (debian v16/v17) warning: destructor called on 'godot::CallableCustomMethodPointerBase' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
=> clang: Add CallableCustomMethodPointerBase virtual destructor

tools/godotcpp.py
This comment enables the possibility to build the "compile_commands.json" file by only using `scons -Q compiledb`. No need to use the argument `compiledb=yes`.
And when using the `compiledb=yes`, it will create a "compiled_commands.json" automatically.
=> Refactor compiledb implementation

src/variant/variant.cpp
Variant iteration methods were returning wrong values from GDExtension API call, never reporting that iterations were valid.
This PR makes `r_valid` be set, as well as return the result from the call instead of returning `valid`.
=> Fix return value and `r_valid` value in `Variant::iter_init` and `Variant::iter_next`

CMakeLists.txt, test/CMakeLists.txt, tools/godotcpp.py, tools/windows.py
Counterpart to https://github.com/godotengine/godot/pull/80612.
Didn't test it, neither SCons nor CMake changes.
=> SCons: Disable C++ exception handling by default

test/project/main.gd, test/src/example.cpp, test/src/example.h
I originally [posted this test](https://github.com/godotengine/godot-cpp/pull/1091#issuecomment-1585216006) in a comment on PR https://github.com/godotengine/godot-cpp/pull/1091, which has since been merged.
This tests part of the functionality added in that PR (so that we hopefully won't break it in the future :-)).
=> Add test for `Callable.bind()`

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp
This adds the same protections against registering classes that didn't use `GDCLASS()`, as were added to the engine in PR https://github.com/godotengine/godot/pull/81020
This same problem affects godot-cpp, but to a much lesser degree. I was able to reproduce the issue by making a class heirarchy like:
```c++
class Example : public Object {
GDCLASS(Example, Object);
protected:
static void _bind_methods() { };
};
class ExampleChild : public Example {
};
```
With out this PR, registering `ExampleChild` was allowed to go ahead, which meant really registering `Example` again under a different name. However, with this PR, it gives the compiler error `Class not declared properly, please use GDCLASS.`, just like in the engine.
=> Add protections against registering classes that didn't use `GDCLASS()`

test/project/main.gd, test/src/example.cpp, test/src/example.h
This is a follow up to PR https://github.com/godotengine/godot-cpp/pull/1253 which adds a limited test to see if Variant iterators are working.
Unfortunately, we won't be able to merge it until after Godot PR https://github.com/godotengine/godot/pull/83681 is merged first. Depending on if/when that gets cherry-picked into Godot 4.1, we may need to keep this test for only Godot 4.2+
=> Add an automated test using a Variant iterator

gdextension/gdextension_interface.h, src/variant/callable_method_pointer.cpp
This adapts the existing `callable_mp()` and `callable_mp_static()` implementation to use `ObjectID` after Godot PR https://github.com/godotengine/godot/pull/83800
=> Switch to using `ObjectID` in custom callables

tools/android.py
- Leverages the use of the `ANDROID_HOME` env variable as done [in core](https://github.com/godotengine/godot/pull/84316)
- Provides a fallback to the previous env variable to avoid breaking existing setups
- Aligns the ndk version with the one used in core
=> Update the environment variables used to access the Android NDK toolchain

.github/workflows/ci.yml
Works around Godot issue https://github.com/godotengine/godot/issues/84460
=> Hack adding `--quit-after 100` to ensure `extension_list.cfg` gets generated

include/godot_cpp/classes/wrapped.hpp
The current implementation of `GDCLASS` exits the define with the scope set to "public". This doesn't match the behavior utilized in the godot repository, so people working in the source repository or making a module might be confused by a differing style. The most obvious scenario is someone expecting to have their functions/values after `GDCLASS` to be implicitly private, as has normally been the case, but with gdextension they will be public. This has the potential to go unnoticed for a long stretch of time, as there's no warning for if something *should* be private; so a user could realistically continue coding as if the values were private, but as soon as that repo is passed on to someone else that guarantee is gone
The only area this change risks regression in is classes that assume …
=> `GDCLASS` synced by ending with "private:"

tools/godotcpp.py
Extracted from #1289
Fixes #1297
Fixes two variables that weren't loading their values correctly: `is_msvc` and `use_hot_reload`. The former didn't properly apply to `disable_exceptions` because it was previously evaluated before the windows target was parsed, so the expression was relocated with no further changes. The latter failed to evaluate the conditional properly, even if a value was provided via cla, so its fallback was changed to `None` & the logic was migrated to just before the variable is first used.
=> Fix `is_msvc` and `use_hot_reload` variables

.gitignore
Since python is a dependency for building this code, it seems like a `requirements.txt` file should be part of the repo.
`venv` folders should also be in the `.gitignore`, akin to https://github.com/godotengine/godot/commit/a6fda19e8520b523f41655e3dd1b94cfe9bd1f3c
=> ignoring venv in .gitignore

.github/workflows/ci.yml
We force closing the process after 10 s, which should be ample time to generate the .godot folder.
Should work around https://github.com/godotengine/godot/issues/84735.
=> CI: Workaround upstream issue with .NET editor build not exiting

.gitignore, include/godot_cpp/classes/wrapped.hpp, tools/android.py, tools/godotcpp.py
The 6th batch of PR's marked with `cherrypick:4.1`
=> Cherry-picks for the godot-cpp 4.1 branch - 6th batch

include/godot_cpp/variant/variant.hpp, src/variant/variant.cpp
Implements `int8_t`, `uint8_t`, `int16_t`, and `uint16_t` operations/constructors for Variant. This matches the implementation of the main repo (albeit using the `stdint.h` names), and allows binding methods that use these types as parameters/returns
=> Add missing int→Variant conversions

include/godot_cpp/variant/callable_method_pointer.hpp, src/variant/callable_method_pointer.cpp, test/project/main.gd
Fixes https://github.com/godotengine/godot-cpp/issues/1293
This duplicates a lot of code from `custom_method_pointer.h/cpp` in Godot. I finally understand why it does what it does in such a weird way. :-) The tl;dr version is that the size of C++ method pointers in undefined (as opposed to function pointers, which do have a defined size), so putting them in a struct and then looping over the data for comparison and hashes is the easiest, portable way to do that.
Marking this as a draft for now, because it depends on PR https://github.com/godotengine/godot-cpp/pull/1280 which isn't merged yet
=> Fix comparison of `Callable`s from `callable_mp()` of the same method

.github/workflows/ci.yml
It has just been removed from the Ubuntu 20.04 default install, breaking our CI setup.
Also, sets Emscripten version to 3.1.39, as done upstream.
Newer versions actually break dynamic library support.
=> CI: Install Android NDK r23c explicitly

tools/android.py
Godot has been using the minimum version 21 for a long time
https://github.com/godotengine/godot/pull/67610
Fixes #938
=> [Scons] Set the minimum Android API level to 21

include/godot_cpp/godot.hpp, src/godot.cpp
Fixes https://github.com/godotengine/godot/issues/85210, with a statically linked extensions this part is shared between all extensions and therefor can use static variables.
=> [iOS] Fix initialisation/termination of multiple statically linked extensions.

CMakeLists.txt
Recently, I noticed that GDExtension shared libraries using godot-cpp that were built with CMake had significantly larger file sizes than the equivalent shared libraries built with SCons.
For the SCons project, I followed [the GDExtension C++ example](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html). To enable debug symbols, I added `debug_symbols=True` to the `scons` command. When debug symbols were disabled, I also set release optimizations through `target=template_release` since I used `CMAKE_BUILD_TYPE=Release` with CMake to avoid setting debug symbols through the default Debug build type.
For the CMake project, I used the same project but with [this custom `CMakeLists.txt` file](https://github.com/godotengine/godot-cpp/files/13174115 …
=> Make CMake only include debug symbols when appropriate 

CMakeLists.txt, binding_generator.py
While attempting to build this project with meson (via its cmake module) I ran into an issue with the generated file listing having a trailing `;` and trailing whitespace, which meson doesn't handle very well. This PR fixes these issues.
=> Fix file list issues when trying to build with meson via cmake

binding_generator.py
Fixes godotengine/godot#85444.
As discussed in the issue above, this would change the underlying integer type for enums declared with `VARIANT_BITFIELD_CAST` to be `uint64_t` instead of the default `int`.
This helps resolve an issue where MSVC will currently truncate any enum values larger than 2^31 for enums that don't have an explicit underlying type, which is affecting `RenderingServer::ArrayFormat`, as seen in the issue above.
Note that this technically opens up for other potential future problems, where someone on the Godot side of things could define a regular `int`-backed enum, bind it with `VARIANT_BITFIELD_CAST` and then include it in something like a `GDREGISTER_NATIVE_STRUCT`, which would lead to an ABI difference and potentially memory corruption.
=> Change bit field enums to use `uint64_t` as underlying type

src/classes/wrapped.cpp, test/project/main.gd, test/src/example.cpp, test/src/example.h
Fixes https://github.com/godotengine/godot-cpp/issues/1269
This turned out to be a little messier to implement than I had imagined, because in godot-cpp it's `Wrapped::_postinitialize()` (rather than in Godot where it's `Object::_postinitialize()`) so it's got to cast the `Wrapped *` to `Object *` to send the notification. It's probably safe to assume that all `Wrapped *` are in fact descended from `Object *`, but I did a `dynamic_cast<Object *>()` just to be sure.
This PR includes tests that fail without the fix, and then succeed with it.
=> Send NOTIFICATION_POSTINITIALIZE to extension classes

src/godot.cpp
Fixes https://github.com/godotengine/godot-cpp/issues/1322
I don't know if this is the best fix, it does what I wish GCC would do, which is just turn `unsigned_value >= 0` into `true` :-)
FYI, I'm not personally getting this error locally, even though I am using GCC 11.4 on Ubuntu 22.04, which is the same as the issue reporter. So, someone that's actually getting this error should confirm that this fixes it.
=> Prevent `-Wtype-limits` warning on GCC 11 due to unsigned comparison

CMakeLists.txt, test/CMakeLists.txt
The CMake buildsystem should be completely reviewed to properly match what is done by SCons, instead of making its own arbitrary decisions on how godot-cpp should be compiled.
Currently the SCons setup doesn't include warning options, so CMake shouldn't either. Options similar to upstream Godot's SCons setup could be added, and then replicated for CMake.
---
This kind of issue is exactly why I'm against having multiple buildsystems. It's very difficult to keep them in sync, especially since officially we only commit to maintaining SCons, yet many users reach straight for CMake as more familiar to them (or usually more familiar to their IDE...).
If we really want to support CMake (which can make sense for something used to interface with thirdparty codebases, often using CMake), then it …
=> CMake: Remove hardcoded warnings list and forcing -Werror on library builds

include/godot_cpp/variant/variant.hpp
This PR adds PackedRealArray as an alias for PackedFloat(32/64)Array to allow you to specify that you want an array of the float size defined for `real_t`. In the core engine, it is possible to use `Vector<real_t>`, but this is not possible in GDExtension because PackedFloat(32/64)Array are explicit types and not just `Vector<T>`.
I used `using` instead of `#define` to ensure that the namespace is preserved, so that if you don't have `using namespace godot;` then you need `godot::PackedRealArray` just like you would need `godot::PackedFloat32Array`. I also tried using `typedef` and it works fine too including with the namespace, but `using` is the newer preferred syntax.
=> Add PackedRealArray as an alias for PackedFloat(32/64)Array

tools/godotcpp.py
Intended use case: I am working on a project that can be built as either an engine module or a GDExtension. I need to be able to detect whether I am building for GDExtension or not in my code, like this:
```cpp
#ifdef GDEXTENSION
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/variant/string.hpp>
#elif defined(GODOT_MODULE)
#include "core/object/class_db.h"
#include "core/string/ustring.h"
#else
#error "Must build as Godot GDExtension or Godot module."
#endif
```
See also https://github.com/godotengine/godot/pull/86269 - having at least one of these PRs is highly useful, but having both is even better, because it lets you explicitly error on invalid configurations.
Without this PR, I have to put this in my own SConstruct file. This works fine... but this would be generally …
=> Allow detecting when building as a GDExtension

tools/android.py
I had trouble figuring out why I couldn't compile for android and realized I didn't have the right NDK version installed. So I figured I would add an error message to make it more obvious.
=> Add an error message if android NDK is not installed

include/godot_cpp/core/binder_common.hpp
godot-cpp version of:
* https://github.com/godotengine/godot/pull/80844
* Fixes: https://github.com/godotengine/godot-cpp/issues/1345
Cherry picking for 4.2 as it was merged in 4.2 but not for 4.1 to match the engine where it was not cherry picked for 4.1
=> Fix expected argument count for call errors

include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4i.hpp, src/variant/vector2i.cpp
This pull request adds `distance_to` and `distance_squared_to` methods for `Vector2i`, `Vector3i` and `Vector4i`, so that [godot-cpp](https://github.com/godotengine/godot-cpp) may remain in parity with GDScript.
- Depends on https://github.com/godotengine/godot/pull/83163.
=> Add `Vector2i/3i/4i` methods: `distance_to` and `distance_squared_to`

binding_generator.py, include/godot_cpp/variant/variant.hpp
I don't think this breaks compatibility as there's no binary compatibility to maintain here, the mapping to the engine is done via the interface macros, but need verification here
* Fixes: https://github.com/godotengine/godot-cpp/issues/1348
Edit: This likely fixes `Variant::evaluate` which tries to map `Operator` to `GDExtensionVariantOperator` which doesn't line up
=> Add missing `OP_POWER` operator to `Variant`

binding_generator.py
Fix redundant prefix "godot." when binding method with godot's global constants.
=> Remove "godot" namespace when binding global constants.

include/godot_cpp/variant/aabb.hpp
See:
* https://github.com/godotengine/godot/pull/87118
=> Fix `AABB.encloses` failing on shared upper bound

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, test/src/example.h, test/src/register_types.cpp
Fixes #1287 
This PR moves the `create` and `recreate` methods out of the `GDCLASS` macro and adjusts the references in the `ClassDB` to use the new `ClassCreator` template class that provides the same functionality as the previous methods in the macro.  
Users can now freely create Godot classes with pure virtual functions, i.e. this is now possible:
```cpp
class MyTestClass : public VBoxContainer
{
GDCLASS(MyTestClass, VBoxContainer);
static void _bind_methods() {}
public:
virtual void test_function() = 0;
};
```
=> Rework GDCLASS macro to allow abstract classes

binding_generator.py, include/godot_cpp/templates/cowdata.hpp, include/godot_cpp/templates/safe_refcount.hpp, include/godot_cpp/templates/vector.hpp, include/godot_cpp/variant/char_string.hpp, src/variant/char_string.cpp, src/variant/packed_arrays.cpp
Syncing features with https://github.com/godotengine/godot/pull/86730, but since no GDExtension public API is changed, it should be compatible both ways.
=> Switch to 64-bit ints.

binding_generator.py, include/godot_cpp/core/builtin_ptrcall.hpp
Currently `Signal::get_object()` and `Callable::get_object()` will return an invalid `Object *` without converting by `internal::get_object_instance_binding()`.
This pr fix this problem by adding necessary Conversion for builtin types in binding generator.
=> Fix object return value of builtin types' methods.

tools/godotcpp.py
Use with:
`scons platform=os2 custom_tools=/path/to/tools`
(assuming you have an `os2.py` inside `/path/to/tools/`)
E.g.:
```python
def exists(env):
return True
def generate(env):
if env["arch"] not in ("x86_32", "ppc32"):
print("Only x86_32 and ppc32 are supported on OS/2. Exiting.")
env.Exit(1)
env["CC"] = "echo"
env["CXX"] = "echo"
env["AR"] = "echo"
env["LINK"] = "echo"
env["RC"] = "echo"
env["RANLIB"] = "echo"
```
=> [SCons] Add support for custom build tools and platforms

README.md, binding_generator.py, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/binder_common.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/variant.hpp, src/godot.cpp, test/src/example.h, test/src/register_types.cpp, tools/android.py, tools/godotcpp.py
The 1st batch of PR's marked with `cherrypick:4.2`
=> Cherry-picks for the godot-cpp 4.2 branch - 1st batch

.github/workflows/ci.yml, CMakeLists.txt, README.md, binding_generator.py, include/godot_cpp/godot.hpp, include/godot_cpp/variant/variant.hpp, src/classes/wrapped.cpp, src/godot.cpp, src/variant/variant.cpp, test/CMakeLists.txt, test/project/main.gd, test/src/example.cpp, test/src/example.h, tools/android.py, tools/godotcpp.py
The 7th batch of PR's marked with `cherrypick:4.1`
=> Cherry-picks for the godot-cpp 4.1 branch - 7th batch

binding_generator.py
Could do this on the engine side but as we seem to universally assume pointers are valid for these calls on the engine side, so this ensures it works correctly regardless
* Fixes: https://github.com/godotengine/godot-cpp/issues/1403
=> Fix crash on virtual method calls

include/godot_cpp/classes/wrapped.hpp, test/project/main.gd, test/project/main.tscn, test/src/example.cpp, test/src/example.h, test/src/register_types.cpp
Currently, if you have a parent and child class both defined in GDExtension, and the child class has it's own `_notification()` method, the parent `_notification()` won't be called. But, also, godot-cpp is not respecting the `p_reversed` flag, and will always run reversed, calling the child before the parent.
This PR fixes that!
It also adds an automated test to ensure that it is working correctly, and so we won't break this again.
=> Fix `_notification()` with parent and child classes

include/godot_cpp/core/type_info.hpp
* Fixes: https://github.com/godotengine/godot-cpp/issues/1406
=> Fix invalid `void` return in `BitField`

binding_generator.py
Related to [this comment](https://github.com/godotengine/godot-cpp/pull/1377#issuecomment-1989314514)
Will hopefully allow extensions to use the `GDVIRTUAL*()` macros without requiring `using namespace godot`
Unfortunately, I don't currently have a project that isn't using `using namespace godot` to test this with, so I haven't tested if this is sufficient to fix the issue, but it does still build and work on the test project in godot-cpp.
=> Use explicit `::godot` namespace in gdvirtual.gen.inc

binding_generator.py, test/project/main.gd, test/src/example.cpp, test/src/example.h
Adds missing support for the initializer lists.
=> [Packed*Array] Add support for initializer lists.

binding_generator.py, include/godot_cpp/variant/variant.hpp, src/variant/variant.cpp
This a new idea for a way to fix issue https://github.com/godotengine/godot-cpp/issues/1240
It's a less hacky alternative to PR https://github.com/godotengine/godot-cpp/pull/1378
Rather than messing around with blobs of memory, and trying to cleverly avoid calling object constructors, this just adds a new private constructor that does what we want. :-)
~~The code is generating for all the variant types, but I've only updated `Array` and `Dictionary` to use the new constructors.~~
=> Avoid creating most objects that Godot is going to use placement new to initialize (mark 2)

gdextension/gdextension_interface.h
Godot-cpp side of:
* https://github.com/godotengine/godot/pull/89050
=> Add extension support for argument count to `ScriptInstance`

CMakeLists.txt, test/CMakeLists.txt
This is because target_link_options was added in v3.13 So this wouldn't build with cmake v3.12
https://cmake.org/cmake/help/latest/release/3.13.html#commands
Likewise in CMAKE_CXX_STANDARD only supports value of 17 starting with cmake v3.9
So the test wouldn't build properly with cmake v3.6
=> Change cmake required to v3.13

include/godot_cpp/core/engine_ptrcall.hpp
The alternative method would be to change the bindings from:
https://github.com/godotengine/godot-cpp/blob/a62f633cebee4b36356dc903d00670733cd28fb1/binding_generator.py#L2054
To:
```python
function_call += "internal::_call_utility_ret_obj(_gde_function, nullptr"
```
But I don't see any reason to pass this argument here, and this is strictly internal, so I think this is the simplest and cleanest solution, I have tested both methods and they both work correctly
See:
* https://github.com/godotengine/godot-cpp/pull/1421
=> Fix incorrect utility call signature

README.md, test/src/register_types.cpp
Converts the direct use of class registration functions to their equivalent `GDREGISTER` defines.
=> Use `GDREGISTER` defines in example

.github/workflows/ci.yml, tools/godotcpp.py
Brings over the `verbose` environment variable from the main godot repo. Much like the main repo, it's disabled by default & enabling it will output logs identical to how they currently output. By leaving verbosity disabled, the outputs are **significantly** trimmed down, which causes a very real performance boost in certain environments (eg: running the build command via a VSCode task). Verbosity is enabled for GitHub Actions, both to mirror the godot repo & because those *should* be giving explicit output.
=> Implement `verbose` toggle from godot repo

src/variant/projection.cpp
=> Fix Projection create_orthogonal being incorrect

include/godot_cpp/core/property_info.hpp
This seems to stem from the old property usage flags before they were adjusted in 2022.  It's probably just best to init the value using the `PROPERTY_USAGE_DEFAULT` to avoid this in the future.
=> Fix PropertyInfo to use hint/usage default constants

.github/workflows/ci.yml, README.md, include/godot_cpp/core/property_info.hpp, src/variant/projection.cpp, test/src/register_types.cpp, tools/godotcpp.py
The 9th batch of PR's marked with `cherrypick:4.1`
=> Cherry-picks for the godot-cpp 4.1 branch - 9th batch

include/godot_cpp/core/math.hpp, include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/plane.hpp, include/godot_cpp/variant/quaternion.hpp, include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/transform2d.hpp, include/godot_cpp/variant/transform3d.hpp, include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector4.hpp, src/variant/aabb.cpp, src/variant/basis.cpp, src/variant/plane.cpp, src/variant/quaternion.cpp, src/variant/rect2.cpp, src/variant/transform2d.cpp, src/variant/transform3d.cpp, src/variant/vector2.cpp, src/variant/vector3.cpp, src/variant/vector4.cpp
Did a minor sweep for these, there are some other things to carry over and some style improvements, but the exact changes might be more disruptive than these additions so leaving them for a future set of changes (some are also exclusive to later versions so keeping this one minimal to begin with)
* Fixes: https://github.com/godotengine/godot-cpp/issues/1434
=> [Math] Add `is_finite` methods

include/godot_cpp/core/property_info.hpp, src/core/object.cpp
Others may appreciate these rather than create their own implementations.
=> Implement to/from dict helpers for PropertyInfo/MethodInfo

include/godot_cpp/core/class_db.hpp
To Fix #1425
This PR is a resubmission of #1427 , as the repository submitted that time was my master branch it looked bad. So I want to resubmit it.
=> Fix create instance func

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/type_info.hpp
It's already a compile-time error if you make a class without a `_bind_methods()` that descends from a native class (like `Node`, `Control`, etc).
But as pointed out on issue https://github.com/godotengine/godot-cpp/issues/1430, if you make a class that descends from another extension class, there won't be a compile-time error because the parent class's `_bind_methods()` will get picked up, and some things won't work correctly (ex virtual method registration, like `_ready()`, as mentioned in the issue).
This PR attempts to make it a compile-time error if the class doesn't have its own `_bind_methods()`, ignoring any `_bind_methods()` inherited from its parent class.
This seems to work in my testing on GCC!
Fixes https://github.com/godotengine/godot-cpp/issues/1430
=> Give compile-time error if registering a class without its own `_bind_methods()` function

include/godot_cpp/core/method_ptrcall.hpp, test/project/main.gd
Fixes https://github.com/godotengine/godot/issues/86478
Fixes https://github.com/godotengine/godot-cpp/issues/1056
This is an alternative to PR https://github.com/godotengine/godot/pull/87613, fixing the issue in godot-cpp rather than in Godot itself. I explained my reasons for wanting to fix it in godot-cpp in [this comment](https://github.com/godotengine/godot/pull/87613#issuecomment-1937341788).
This uses a ternary expression to match the code in the `encode()` method just below the `convert()` method this PR changes:
```c++
_FORCE_INLINE_ static void encode(T *p_var, void *p_ptr) {
*reinterpret_cast<const void **>(p_ptr) = p_var ? p_var->_owner : nullptr;
}
```
I think having the symmetry between the encode/decode methods is nice, even though it leads to a very long line of code. :-) …
=> Correctly handle `Object *` arguments that were encoded as `nullptr`

binding_generator.py, include/godot_cpp/core/class_db.hpp
This PR aims to fix godot-cpp when used with the `enum` added to `ClassDB` in PR https://github.com/godotengine/godot-proposals/issues/9526 (I tested using the `extension_api.json` from Godot built with that PR)
Since Godot's CI uses godot-cpp for version N-1, this will need to be cherry-picked to the `4.2` branch before the tests will be able to pass on that PR
=> Allow forwarding from `ClassDB` to `ClassDBSingleton` to support enumerations

include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/rect2i.hpp, include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4.hpp, include/godot_cpp/variant/vector4i.hpp, src/variant/vector2.cpp, src/variant/vector2i.cpp, src/variant/vector3.cpp, src/variant/vector3i.cpp, src/variant/vector4.cpp, src/variant/vector4i.cpp
Also added `snapped` to the integer vectors for completeness
See:
* https://github.com/godotengine/godot/pull/89114
=> Add scalar versions of `Vector*` `min/max/clamp/snap(ped)`

gdextension/gdextension_interface.h, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/godot.hpp, src/godot.cpp, test/SConstruct, test/doc_classes/Example.xml, test/project/project.godot, tools/godotcpp.py
Godot PR https://github.com/godotengine/godot/pull/83747 added support for submitting documentation to the Godot editor from a GDExtension.
This PR aims to give godot-cpp users a way to use that, ideally, in much the same way as documentation is provided by modules.
Here's how it works:
- Using PR https://github.com/godotengine/godot/pull/91518, developers can run `godot --doctool ../ --gdextension-docs` in their demo project (assuming the project is in a directory below their top-level extension code) which will generate a `doc_classes/` directory
- Edit the XML files in the `doc_classes/` directory
- Add something like this to their `SConstruct`:
```
if env["target"] in ["editor", "template_debug"]:
doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", …
```
=> Allow submitting documentation to the Godot editor

gdextension/gdextension_interface.h, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/class_db.hpp
Adds support for changes in PR https://github.com/godotengine/godot/pull/91179
Note: This doesn't change how we handle properties using the count, it sticks with the same old approach.
Keeping this as a draft until that PR is merged
=> Update `free_property_list` callback to take count

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/method_bind.hpp
PRs https://github.com/godotengine/godot-cpp/pull/1374 and https://github.com/godotengine/godot-cpp/pull/1450 can't be cherry-picked (because they are for things only in Godot 4.3), but there's two little changes that could be included in `4.2` and `4.1`.
Since we still cherry-pick so much to the `4.2` and `4.1` branches, I'd like them to remain as synchronized as possible, in order to avoid creating conflicts that make future cherry-picks harder.
So, this PR just brings these two little miscellaneous changes to `4.2`, which should cherry-pick fine to `4.1` too.
(I kind of regret not splitting these out into their own PRs so they could be cherry-picked like normal, but they are so tiny, I think this is probably fine)
=> [4.2] Backport miscellaneous changes that can't be cherry-picked

.github/workflows/ci.yml
Starting a few weeks ago, we've been getting sporadic CI failures on the `master` branch. Running the failed jobs again usually succeeds (although, I've had a couple that failed 2-3 times before finally succeeding).
The errors look like this:
<details>
<summary>Error output from the logs</summary>
```
Run chmod +x ./godot-artifacts/godot.linuxbsd.editor.x86_64.mono
4.3.dev.mono.gh.55b8724bd
SCRIPT ERROR: Parse Error: Could not find type "Example" in the current scope.
at: GDScript::reload (res://main.gd:10)
SCRIPT ERROR: Parse Error: Identifier "Example" not declared in the current scope.
at: GDScript::reload (res://main.gd:22)
SCRIPT ERROR: Parse Error: Identifier "Example" not declared in the current scope.
at: GDScript::reload (res://main.gd:24)
SCRIPT ERROR: Parse Error: Identifier …
```
=> Attempt to fix recent CI failures on `master` branch

include/godot_cpp/templates/list.hpp
Optionally kept the index operators for compatibility with code using the old syntax, which matters more than in the engine itself, though the conversion is trivial
See:
* https://github.com/godotengine/godot/pull/90705
=> [Core] Reduce and prevent unnecessary random-access to `List`

test/project/example.gdextension, tools/godotcpp.py, tools/web.py
This is relevant for the Web platform, where builds with and without threads are incompatible.
=> [SCons] Add option to build without threads

include/godot_cpp/classes/wrapped.hpp
Refer to the [commet](https://github.com/godotengine/godot-cpp/pull/1446#discussion_r1603503930) in #1446 .
=> Mark return value of `get_class_static` and `get_parent_class_static` as const.

include/godot_cpp/classes/wrapped.hpp, src/classes/wrapped.cpp
As brought up on PR https://github.com/godotengine/godot/pull/91018, we're currently sending `NOTIFICATION_POSTINITIALIZE` to the native parent class twice.
This issue was introduced by PR https://github.com/godotengine/godot-cpp/issues/1269, which was attempting to get the `NOTIFICATION_POSTINITIALIZE` to arrive to the extension class by sending it in `Wrapped::_postinitialize()`, but the way it's doing it will send the notification through the native parent class again.
This PR makes it so that `Wrapped::_postinitialize()` will only send `NOTIFICATION_POSTINITIALIZE` through the class hierarchy that exists purely on the GDExtension side. Because `NOTIFICATION_POSTINITIALIZE` is run on the parent class first, this effectively just picks up where the previous notification that went …
=> Fix NOTIFICATION_POSTINITIALIZE sent twice to native parent classes

include/godot_cpp/core/class_db.hpp
Currently, the `GDREGISTER_*_CLASS()` macros assume that user code has `using namespace godot`. This PR makes the macros explicitly refer to the `godot` namespace, so they can be used even without that.
=> Explicitly refer to `godot` namespace in `GDREGISTER_*_CLASS()` macros

include/godot_cpp/classes/ref.hpp, include/godot_cpp/core/type_info.hpp, test/src/example.cpp, test/src/example.h
Fixes https://github.com/godotengine/godot-cpp/issues/1480
This changes `const` to `constexpr` in some definitions of the `GetTypeInfo` template (we were using `constexpr` already in a few).
We should probably make the same changes to Godot itself as well, since that's where this code was copied from in the first place.
=> Fix undefined symbol error on Linux with virtual methods that take `Node *` arguments

src/core/class_db.cpp, src/core/object.cpp
Hello, I am tracking 4.2 branch of godot-cpp for my project and compiling my whole project with -Wall. I recently updated godot-cpp to pull all changes from 4.2 branch and there are some new warnings during build that this PR fixes.
The warnings that are fixed by this are:
```
src/core/object.cpp:78:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<godot::Variant>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
78 |         for (int i = 0; i < default_arguments.size(); i++) {
|                         ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/class_db.cpp:356:35: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
356 |                 for (int i = 0; i < …
```
=> Fix warnings emitted with -Wall

test/project/main.gd
Our tests are failing after Godot PR https://github.com/godotengine/godot/pull/92827 was merged
This PR fixes the tests!
=> Fix tests after upstream change to `Node::to_string()`

binding_generator.py
Cases other than `&""` were not processed correctly
See https://github.com/godotengine/godot/pull/91382#issuecomment-2165890277
=> Fix generating default values for `StringName`

binding_generator.py
Aims to fix the CI issues with Godot PR https://github.com/godotengine/godot/pull/91392 as well as allowing forwarded vararg methods to work.
This will need to be cherry-picked to the `4.2` branch before CI on that PR can pass.
=> Fix vararg methods forwarded to the `ClassDB` singleton

binding_generator.py
No bindings contain default arguments for `NodePath` currently but they would break if they were added
=> Add default argument processing for `NodePath`

include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/memory.hpp, src/classes/wrapped.cpp, test/project/main.gd, test/src/example.cpp, test/src/example.h
Fixes https://github.com/godotengine/godot-cpp/issues/1039
Refer to this [comment](https://github.com/godotengine/godot/issues/91023#issuecomment-2074129143). This is my solution to advance the timing of setting instance and instance binding.
There may be some potential problems that I haven't found, please review it carefully.
This is my test class:
```c++
class MyLineEdit : public LineEdit {
GDCLASS(MyLineEdit, LineEdit)
protected:
static void _bind_methods() {}
public:
void _on_text_submitted(const String &p_test) {
UtilityFunctions::print("Submitted: ", p_test);
}
MyLineEdit() {
connect("text_submitted", callable_mp(this, &MyLineEdit::_on_text_submitted));
}
};
```
Before this pr, it will push an error:
```
ERROR: Condition "_instance_bindings != nullptr && …
```
=> Set instance and instance binding in `Wrapped` constructor.

.github/workflows/ci.yml
Allow selecting the Godot version to run the tests with on CI.
=> Allow selecting Godot version to run the tests with

.github/workflows/ci.yml
This is the Godot 4.2 version of PR https://github.com/godotengine/godot-cpp/pull/1493
This will also be cherry-picked (with a version change) to the `4.1` branch
=> [4.2] Allow selecting Godot version to run the tests with

binding_generator.py, include/godot_cpp/core/class_db.hpp, src/core/class_db.cpp, src/core/object.cpp
The 5th batch of PR's marked with `cherrypick:4.2`
=> Cherry-picks for the godot-cpp 4.2 branch - 5th batch

.github/workflows/ci.yml, binding_generator.py, include/godot_cpp/core/class_db.hpp, src/core/class_db.cpp, src/core/object.cpp, tools/common_compiler_flags.py, tools/godotcpp.py
The 11th batch of PR's marked with `cherrypick:4.1`
=> Cherry-picks for the godot-cpp 4.1 branch - 11th batch

binding_generator.py, test/build_profile.json, tools/godotcpp.py
Allow enabling or disabling specific classes (which will not be built).
This is similar to upstream godot `build_profile`s.
Try building the test with:
```
scons build_profile='build_profile.json'
```
Partly address #1160.
=> Add support for build profiles.

tools/web.py
`SUPPORT_LONGJMP` have changed since emscripten 3.1.32 to default to `"wasm"` mode when exceptions are enabled, and `"emscripten"` mode when disabled.
While we generally don't use exception in core, linked libraries may need them, and emscripten doesn't plan to support WASM EH + Emscripten SjLj in the long term.
See godotengine/godot#93143
=> [Web] Force emcc to use "wasm" longjmp mode

binding_generator.py
Improves general readability of generated code and prevents potential collisions
=> Enforce `p_` prefixes for arguments in binds

binding_generator.py
Some minor output fixes that I came across while fixing some other bugs, this would generate things like:
```cpp
static Object  *instance_from_id(int64_t instance_id);
Object * get_object() const;
virtual Error _get_packet(const uint8_t * *r_buffer, int32_t *r_buffer_size);
```
These are all now fixed
=> Fix some style details in generation

include/godot_cpp/variant/variant.hpp, src/variant/variant.cpp
@dsnopek I think this may have been overlooked in https://github.com/godotengine/godot-cpp/pull/1456
=> Add missing enum & ctor for PackedVector4Array implementation

include/godot_cpp/templates/local_vector.hpp, test/src/tests.h
Minor syntactic tweaks to ensure all `godot_cpp/*.hpp` includes use angle brackets instead of double-quotes. Also adds `local_vector` to the `tests.h` includes, as that seems to have been overlooked when it was first added.
=> Fix `#include` formatting

tools/windows.py
Brings over the `silence_msvc` option from the main repo, which suppresses all redundant output from MSVC's `cl`/`link` tools. Additionally, any error output that *does* occur is instead rerouted to `stderr` as expected, instead of printing it in `stdout` for some reason.
Before:
```
Compiling D:\Godot\Github\godot-cpp\gen\src\classes\popup.cpp ...
animation_node_blend3.cpp
visual_shader_node_varying.cpp
Compiling D:\Godot\Github\godot-cpp\gen\src\classes\visual_shader_node_uv_func.cpp ...
shape_cast2d.cpp
Compiling D:\Godot\Github\godot-cpp\gen\src\classes\gpu_particles_collision_sdf3d.cpp ...
Compiling D:\Godot\Github\godot-cpp\gen\src\classes\gltf_camera.cpp ...
v_split_container.cpp
Compiling D:\Godot\Github\godot-cpp\gen\src\classes\script_create_dialog.cpp ...
progress_bar.cpp …
```
=> SCons: Add `silence_msvc` option for Windows

include/godot_cpp/variant/typed_array.hpp
See:
* https://github.com/godotengine/godot/pull/89197
Doesn't depend on the engine fix beyond approval of the approach, so if it looks good for this side I'm open for it being merged here first (only the compatibility expectations to consider)
* Closes: https://github.com/godotengine/godot-cpp/issues/1149
=> Fix sharing of typed arrays from constructor

src/classes/wrapped.cpp
New developers not knowing the need to use `memnew()` instead of `new` is a common cause for support requests.
After PR https://github.com/godotengine/godot-cpp/pull/1446, Godot will crash if a developer forgot to use `memnew()`.
This PR attempts to improve that message by mentioning `memnew()`, in order to help folks learn about it, and hopefully reduce the number of support requests related to it. :-)
This also removes the `ERR_PRINT()` that duplicates the message - I'm not sure why that was there, but I don't think it should be necessary.
=> Remind developers about `memnew()` in crash message when missing binding callbacks

binding_generator.py
Fixes https://github.com/godotengine/godot-cpp/issues/1390
The `is_instance_valid()` function doesn't work as developers expect, and unless used very carefully, will cause crashes. Instead, developers should use `ObjectDB::get_instance()` with object ids to ensure that an instance is still valid.
This PR unexposes `is_instance_valid()` so that folks aren't tempted to use it.
I'm unsure if we should cherry-pick this or not. Technically it breaks source compatibility, but if developers are using this function, they probably have a bug that's waiting to be exposed. :-)
Note: Bindings aside from godot-cpp may be able to expose `is_instance_valid()` in a non-problematic way. However, since we're trying to match the Godot API and allow raw pointers to objects, we are stuck with this issue. If …
=> Unexpose `UtilityFunctions::is_instance_valid()`

.github/workflows/ci.yml
The 1st batch of PR's marked with `cherrypick:4.0`
These are all CI changes, so I won't know if they work until CI runs.
=> Cherry-picks for the godot-cpp 4.0 branch - 1st batch

.github/actions/godot-cache-restore/action.yml, .github/actions/godot-cache-save/action.yml, .github/workflows/ci.yml
See:
* https://github.com/godotengine/godot/pull/94314
If desired I can make a dedicated cherry pick PR for 3.x
=> [CI] Upload build cache before running tests

CMakeLists.txt
Add support for hot reloading when building `godot-cpp` using CMake.
CMake projects can enable the reloading by setting `GODOT_ENABLE_HOT_RELOAD` to `ON` before including the `godot-cpp` subdirectory.
Example:
```cmake
set(GODOT_ENABLE_HOT_RELOAD ON)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/godot-cpp/" build-godot-cpp)
```
I believe I've done all of this correctly — I'm super new to both Godot and Scons, but from how I understand the Scons-support for hot reloading in https://github.com/godotengine/godot-cpp/pull/1200, I believe this to be correct.
* *Bugsquad edit, closes: https://github.com/godotengine/godot-cpp/issues/1542*
=> Add hot reload support to CMakeLists.txt

include/godot_cpp/classes/wrapped.hpp
@dsnopek this is in response to my question from chat.  It seems a bit odd to me that `_get_property_list` dispatches up the class hierarchy while calls to `_get` and `_set` do not and expect the developer to call the super type internally.  I'm not sure whether we want to alter this behavior or leave it as-is and document this nuance for others who may prefer to use these override methods for property management.
This change also seems to align the GDExtension behavior with C++ modules, too.
=> Make sure `_get` and `_set` dispatch up the class hierarchy

README.md
Preview: https://github.com/Calinou/godot-cpp/blob/readme-use-github-admonition-syntax/README.md
=> Use GitHub admonition syntax for the warning in README

include/godot_cpp/classes/wrapped.hpp
This change removes the warnings (unused parameters) coming from code injected by the `GDCLASS` macro. 
Contrary to warnings coming from the normal source code which can be suppressed with most compiles by specifying the include directories of this library as external or system, when the code is injected through a macro it is considered in the context of the user, which is the source code of user of the library. 
That forces the users to modify their code to hide the warnings coming from the mandatory `GDCLASS` here. That's why it's important to remove these warning from that specific macro and ideally any other macro that the user must use.
Fixes #1541
I tested it in my project and in an isolated example.
=> Removes warnings generated by GDCLASS usage

binding_generator.py
Follow-up to:
* https://github.com/godotengine/godot-cpp/pull/1423
This makes running `clang-format` on the generated files change almost nothing, the only things this does not do correctly is:
* Align continuations in `class_db_singleton.hpp`, which would be a lot of extra code to make work correctly
* Some cases with `public:` followed immediately by `private:` should have no empty line (or no `public:` in the first place), this could be fixed but only occurs in one place, so leaving it be for right now and not adding any complicating code for it
=> Make generated code mostly style compliant

binding_generator.py
The engine uses the names `int` and `float` to refer to the 64-bit types, so in the bindings generator we have a hardcoded conversion for those types.
But this type conversion should not be used for metadata. Even though the underlying type should still be 64-bit for interop, metadata is meant to specify the correct type to expose. So if metadata says `float` it means the type is really meant to be a 32-bit `float` and not `double`. Other hardcoded type conversions (`int` and `Nil`) won't ever be metadata.
This change corrects the `float` type, to use the right type in the generated C++ code. Before we were always using `double` due to this type conversion.
---
For example, the `InputEventMouseButton::get_factor` API changes with this PR to return `float` which matches the method …
=> Avoid hardcoded type conversion for metadata

binding_generator.py
Fixes #1556.
This fixes the generation of `operator!`, `operator&&` and `operator||`, as they were not being mapped correctly from their `extension_api.json` name of `not`, `and` and `or` respectively, resulting in them showing up as `operatornot`, `operatorand` and `operatoror` respectively.
Note that `operatorand` and `operatoror` never actually showed up anywhere in the generated C++ headers, as they only exist on built-in types in `extension_api.json` currently.
I also fixed another related issue, which is that the `**` operator wasn't being skipped like the `in` and `xor` operators have been until now, neither of which make no sense in C++ of course. This is now done through a new helper function called `is_valid_cpp_operator`.
I suppose this is technically a breaking change, so I'm …
=> Fix incorrect generation of some C++ operators

binding_generator.py
- Part of https://github.com/godotengine/godot/pull/95840.
=> Correct type for `char16` and `char32` meta

tools/web.py
Was using CPPFLAGS, but should use the explicit scons CCFLAGS which makes it clear they are applied to both the C and C++ compiler.
CPPFLAGS was also fine (they are preprocessor flags, also applied to both C and C++), but we should try to stay consistent with what we do in Godot.
=> [Web/SCons] Use CCFLAGS for SIDE_MODULE option

include/godot_cpp/templates/safe_refcount.hpp
As was fixed with godotengine/godot#91208
=>  Fix GCC 14 -Wtemplate-id-cdtor warning

test/project/main.gd, test/src/example.cpp, test/src/example.h
Two times now we have broken `get_library_path` such that it doesn't return an absolute path.
See:
- https://github.com/godotengine/godot/pull/84620
- https://github.com/godotengine/godot/pull/94373
This is a Godot issue, but this PR adds a test to CI that will verify that the path is absolute, in order to try and help us not break it again.
This will fail CI until PR https://github.com/godotengine/godot/pull/94373 is merged
=> Add a test to ensure that library path is absolute

CMakeLists.txt
This is a small continuation to PR #1330 which adds hot reloading options for CMake
However when compiling with GCC, the option ```-fno-gnu-unique``` must also be enabled to allow hot reloading.
This is done in the SCons script: https://github.com/godotengine/godot-cpp/blob/9b98377a62ae456b0ee082062dbe98d1a13e7bda/tools/linux.py#L20
=> Add hot reload support when building with GCC and CMake

tools/common_compiler_flags.py, tools/windows.py
Similar to the recent https://github.com/bruvzg/godot-nir-static/ and https://github.com/bruvzg/godot-angle-static/ changes for ARM64 Windows support.
- Fixes MSVC architecture detection.
- Adds MinGW-LLVM support.
- Adds `mingw_prefix` to specify custom toolchain.
Tested with:
- MSVC 2022 - (arm64, x86_64, x86_32)
- MinGW-GCC MSYS2 on Windows - (x86_64, x86_32)
- MinGW-LLVM on Windows - (arm64, x86_64, x86_32)
- MinGW-GCC cross build from macOS - (x86_64)
- MinGW-LLVM cross build from macOS - (x86_64)
=> Add support for LLVM/MinGW and ARM64 Windows builds.

CMakeLists.txt
This should make all symbols that are not marked otherwise have hidden visibility. There still may be exposed symbols if marked with respective attributes.
=> Add visibility-hidden to CMake build

.github/actions/godot-cache-restore/action.yml, .github/actions/godot-cache-save/action.yml, .github/workflows/ci.yml, CMakeLists.txt, binding_generator.py, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/templates/safe_refcount.hpp, test/project/example.gdextension, test/project/main.gd, test/src/example.cpp, test/src/example.h, tools/godotcpp.py, tools/ios.py, tools/web.py
The 7th batch of PR's marked with `cherrypick:4.2`
=> Cherry-picks for the godot-cpp 4.2 branch - 7th batch

CMakeLists.txt
Bring the 'cmake -LH' output inline with the scons output.
I dont know what the policy on adding notes in comments are.
I can ammend the commit to remove them if they are unwanted.
=> add SYMBOL_VISIBILITY cache variable to match scons interface.

CMakeLists.txt, cmake/GodotCompilerWarnings.cmake
This is after the symbol-visibility fixes, to bring the existing cache variables upto the same parity as scons.
It's extremely simple, just variable renames, docstrings, minor whitespace, and variable properties to match their expected content type. ie STRING to PATH and FILEPATH for the json api files. It makes no change to the control flow.
=> Updated all variable names to use GODOT_ prefix

tools/web.py
Required since Godot 4.3, which is also the first Godot version with wide WASM gdnative support (previous versions were Chrome-only, and very brittle).
Closes #1566 (superseded).
Fixes #1553
Fixes godotengine/godot#96492
=> [SCons] Enable WASM_BIGINT in web builds

binding_generator.py
This reverts commit 56cd3fd99eb76ca3da33dafb694828a7306b2c81 aka PR https://github.com/godotengine/godot-cpp/pull/1513.
It fixes issue https://github.com/godotengine/godot-cpp/issues/1587 (for Godot 4.3 and earlier), which pointed out that there is a use-case that can't be currently be replicated using `ObjectID` and `ObjectDB`.
(See PR https://github.com/godotengine/godot/pull/97119 for a way to keep the removal of `UtilityFunctions::is_instance_valid()` while still allowing for this use-case, but it will need to be Godot 4.4+)
=> [4.3] Revert "Unexpose `UtilityFunctions::is_instance_valid()`"

.gitignore
and also the default cmake build directory when building in clion cmake-build-*
it would be very nice if this could be added to gitignore.
=> Update .gitignore to add .idea for the Jetbrains CLion IDE

.github/workflows/ci.yml
Visual Studio projects are multi-config projects like Ninja-MultiConfig which means you can't set the configuration at configure time as there are multiple, it always chooses the first one by default when not specified in the build command.
Instead of this:
cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022" .
cmake --build . --verbose
It should be this
cmake -G"Visual Studio 17 2022" .
cmake --build . --verbose --config Release
Because the existing cmake solution does not use generator expressions for its per config configuration, we actually have to specify it in both commands :(
cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022" .
cmake --build . --verbose --config Release
Fixes https://github.com/godotengine/godot-cpp/issues/1582
=> VSProj Configure type on build command - to resolve #1582

tools/windows.py
This is consistent with Godot upstream.
As discussed in https://github.com/godotengine/godot-cpp/pull/1601#discussion_r1770526612 it seems that we have a discrepancy between [upstream Godot](https://github.com/godotengine/godot/blob/346cbc7f1f206f4540520a92bf7def97b9be0af8/platform/windows/detect.py#L384-L388) and godot-cpp which uses a special `use_clang_cl` instead of the generic `use_llvm` flag for building Windows with the clang MSVC backend.
=> [SCons] Remove use_clang_cl windows flag in favor of generic use_llvm

include/godot_cpp/variant/basis.hpp, src/variant/basis.cpp
This PR aligns the prototype and implementation of `Basis::looking_at()` with the Godot version of this function.
Fixes #1624
=> Add `p_use_model_front` to `Basis::looking_at()`

include/godot_cpp/variant/quaternion.hpp, src/variant/quaternion.cpp
Fixes https://github.com/godotengine/godot-cpp/issues/1629
I basically just copied Godot's `quaternion.h`/`.cpp` over godot-cpp's, then undid changes where the differences were necessary.
=> Sync `Quaternion` with the version in Godot

.github/actions/godot-cache-restore/action.yml, .github/actions/godot-cache-save/action.yml, .github/workflows/ci.yml, .github/workflows/runner.yml, .github/workflows/static_checks.yml
Slight organization improvement when running CIs by making the structure similar to the main repo: static checks now *always* happen first. This has the added benefit of cleaning up the Actions tab, though the benefit is less pronounced on a repo like this where only two instances were used. Beyond that, yaml syntax was reformatted for all action/workflow files, keeping them consistent with the main repo.
=> CI: Add `runner` workflow to call other workflows

include/godot_cpp/variant/vector4.hpp
Follow-up of https://github.com/godotengine/godot/pull/97487#pullrequestreview-2331113052
Fixes #1608 
As mentioned, a discussion could be had about just removing the 'components' alias, but I think there's no harm just using deprecations as is usually done.
=> Rename Vector4.components -> coords.

.github/workflows/ci.yml
See:
* https://github.com/godotengine/godot/pull/98965
=> [Web] Don't cache emsdk

tools/android.py, tools/common_compiler_flags.py, tools/godotcpp.py, tools/ios.py, tools/linux.py, tools/macos.py, tools/web.py, tools/windows.py
The behavior mimics almost the exact behavior (minus "progress" options) of Godot scons:
- [SConstruct](https://github.com/godotengine/godot/blob/master/SConstruct) (option declaration).
- [Web](https://github.com/godotengine/godot/blob/master/platform/web/detect.py)
- [Windows](https://github.com/godotengine/godot/blob/master/platform/windows/detect.py)
- [Linux](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/detect.py)
- [macOS](https://github.com/godotengine/godot/blob/master/platform/macos/detect.py)
- [Android](https://github.com/godotengine/godot/blob/master/platform/android/detect.py)
- [iOS](https://github.com/godotengine/godot/blob/master/platform/ios/detect.py)
This is an _active_ change (edit: not anymore, defaults to 'none' by default now): Once merged, …
=> Add lto scons option

include/godot_cpp/core/defs.hpp
Code in `defs.hpp` is not in namespace `godot` and I don't see any reason for that. Fixing the namesapce has no effect to the other files in the library as they are already in it. From users' perspective they will need to add prefix `godot::` to `real_t`, `IndexSequence`, `BuildIndexSequence` if they don't use `using namespace godot;` (like me). This breaks the compatibility to the old versions but the impact should be small.
=> Use namespace in defs.hpp

cmake/windows.cmake, tools/windows.py
SCons does not link to /MDd or /MTd
If needed in the future a flag can be introduced like the engine code at platforms/windows/detect.py:459
This solves issue #1459
=> CMake: Align MSVC runtime (MD[d], MT) options to engine

cmake/godotcpp.cmake
While reviewing tutorials and discussing with users, I thought of a way to mitigate breaking changes to cmake solution.
By re-adding the godot::cpp target alias as a template_debug lib it will solve a great deal of pain from users migrating.
=> CMake: fix break for build prior to modernisation PR

include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/print_string.hpp, src/core/print_string.cpp
Fixes #1596. This PR adds most of the function signatures from the engine's `print_string.h` and places them in a file called `print_string.hpp`. The implementation from the engine is not copied, instead these wrap around the functions in `UtilityFunctions`. Personally I only need the non-vararg `print_line` but I've included the rest for parity.
`print_string.hpp` is included in `class_db.hpp` just like in the engine's `class_db.h`, which means these functions are available for anywhere that includes `class_db.hpp`. For the verbose function, I had to put the OS call into a separate file since `os.hpp` depends on `class_db.hpp` so there was a circular dependency if I did not. Also, the templates need to exist in the header, so I kept them and most of the functions in the header for …
=> Add `print_line` for compatibility with engine modules

include/godot_cpp/classes/ref.hpp
Fixes https://github.com/godotengine/godot-cpp/issues/1615
It's not an error to receive a null pointer for a `Ref<T>` - that's just how null reference values are encoded - so we shouldn't print an error message. This switches away from `ERR_FAIL_NULL_V()` to just a normal `if` statement.
=> Don't print an error when decoding a null Ref<T>

cmake/windows.cmake
My last attempt at solving this was not correct, and I apologise for that.
MSVC Runtime Selection
----------------------
There are two main ways to set the msvc runtime library; Using ``target_compile_options()`` to add the flags _or_ using the ``CMAKE_MSVC_RUNTIME_LIBRARY`` property abstraction[^1], introduced in CMake version 3.15 with the policy CMP0091[^2] to
remove the flags from ``CMAKE_<LANG>_FLAGS_<CONFIG>``.
Default: ``CMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>DLL"``
This initializes each target's ``MSVC_RUNTIME_LIBRARY`` property at the time of target creation.
This creates a conundrum for us, the ``CMAKE_MSVC_RUNTIME_LIBRARY`` needs to be correct at the time the target is created, but we have no control over the consumers CMake scripts, and the per-target …
=> CMake: Fix selection of MSVC Runtime compile flags

cmake/godotcpp.cmake
This was a mistake left over from the modernise PR
Left over from when I had a default target of template_debug, but it still wanted to build even if it was not depended on.
the targets should be excluded so that they dont all build all the time.
=> CMake: Replace empty ${EXCLUDE} variable with EXCLUDE_FROM_ALL

CMakeLists.txt, cmake/common_compiler_flags.cmake, cmake/godotcpp.cmake, cmake/windows.cmake, doc/cmake.rst, test/CMakeLists.txt
When SCons has dev_build=yes enabled, there is a "dev" feature flag added to the compile artifact.
it enables debug_symbols unless otherwise specified
It changes the debug symbol generation
it sets the optimisation level to none
It sets DEV_ENABLED mutually exclusive to NDEBUG
Representing how dev_build and debug_symbols interact in CMake was harder than anticipated, I think I have struck a good balance.
debug_symbols will not be an option in CMake.
The generation of debug symbols is controlled by the build configuration. This is how it normally works in CMake and is the closest match to what the option means in SCons. For single configuration generators this is expressed by adding `-DCMAKE_BUILD_TYPE=Debug` or `RelWithDebInfo` which will generate debug symbols as expected by all software …
=> CMake: Handle GODOT_DEV_BUILD flag

CMakeLists.txt, cmake/common_compiler_flags.cmake
As listed here: #1250
clang-cl on windows installed from official llvm website fails because it emulates the msvc interface.
Prior solution assumed that because compiler is clang it uses gnu interface.
CMake offers some helper variables to account for this simulation/emulation of other compilers like:
CMAKE_CXX_COMPILER_FRONTEND_VARIANT
This PR detects the difference and sets the helper variables to match what is in use.
It isn't robust enough to mix and match compiler and linker interfaces though, so using a gnu style linker with an msvc style compiler will fail.
I've tested this on windows and mac, with windows based compilers msvc, msys-gcc msys-clang, llvm, mingw64, without issue.
Fixes https://github.com/godotengine/godot-cpp/issues/1250
=> CMake: Enable using clang-cl on windows

.github/actions/setup-godot-cpp/action.yml, .github/workflows/ci.yml
As discussed in the godot-cpp meeting. This action is specifically intended to be used by dependants of godot-cpp, to set up godot-cpp in their own github workflows. A follow-up PR will use this github action in godot-cpp-template (edit: https://github.com/godotengine/godot-cpp-template/pull/70).
There are quite a few differences to godot-cpp-template's setup steps. I don't know if they started the same but diverged later, or if godot-cpp-template has always made different decisions from godot-cpp itself. Here is [godot-cpp-template's version](https://github.com/godotengine/godot-cpp-template/blob/main/.github/actions/build/action.yml#L34-L99) for reference. 
I based my implementation mostly on godot-cpp. Here are the key differences I see:
- `actions/setup-java@v4` and …
=> Add a separate setup-godot-cpp github action.

gdextension/gdextension_interface.h, include/godot_cpp/core/class_db.hpp
Allows GDExtensions to set the icon of a class programmatically.
- Matching PR in main `godot` repo: https://github.com/godotengine/godot/pull/100193
- Example project for testing: https://github.com/raulsntos/threen/tree/set_class_icon
=> Add a method to set the class icon

.github/workflows/ci.yml, CMakeLists.txt, cmake/android.cmake, cmake/common_compiler_flags.cmake, cmake/godotcpp.cmake, cmake/ios.cmake, cmake/linux.cmake, cmake/macos.cmake, cmake/web.cmake, cmake/windows.cmake, doc/cmake.rst, test/CMakeLists.txt
This PR resolves CMake name clashes #1657, Partially resolves optionally disable targets #1650, and tidies IDE usage for VS and XCode by grouping targets under a subfolder.
* Rename CMake internal targets from <target>  to godot-cpp.<target>, Aliases will remain godot-cpp::<target>
* Simplify <platform>_generate cmake function signature, as TARGET_ALIAS and TARGET_NAME are still in scope and do not need to be passed.
* Add `GODOT_ENABLE_TESTING` option default OFF, and guard `add_subdirectory( test )` by default
* Add global property `USE_FOLDERS ON` and target property `FOLDER "godot-cpp"` to group targets in VS and XCode
=> CMake: Alleviate target name clashes, visibility, and grouping.

binding_generator.py, gdextension/gdextension_interface.h, include/godot_cpp/core/class_db.hpp, src/core/class_db.cpp
This implements the virtual method compatibility system from PR https://github.com/godotengine/godot/pull/100674
~~Marking as DRAFT until that PR is merged~~
=> Update for virtual method compatibility system

cmake/godotcpp.cmake, cmake/python_callouts.cmake
Update to the CMake scripts to implement the use of build profiles.
This is upto date with the latest changes from @Faless 
Add python_callouts.py to hold functions which call python utilities
- generate trimmed API
- generate file list
- generate bindings
if GODOT_BUILD_PROFILE is specified, a trimmed API file is created in the CMAKE_CURRENT_BINARY_DIR and used as the source for binding generation
Simplify Code Generation Variables
- use generator expressions
- use math for bits
- simplify if statements
=> CMake: Support for using build_profile.json

cmake/python_callouts.cmake, doc_source_generator.py, test/CMakeLists.txt, tools/godotcpp.py
This PR extends #1499 - [DRAFT] Add CMake support for XML documentation
which follows #1374 - Allow submitting documentation to the Godot editor
This is also built upon #1670 - CMake: Support for using build_profile.json
This PR adds the equivalent functionality to the CMake build scripts. A summary below.
The SCons implementation adds a BUILDER to the env in tools/godotcpp.py:513
```python
env.Append(
BUILDERS={
"GodotCPPBindings": Builder(action=Action(scons_generate_bindings, "$GENCOMSTR"), emitter=scons_emit_files),
"GodotCPPDocData": Builder(action=scons_generate_doc_source),
}
)
```
Which is then available for consumers to use, with the test example showing how at test/SConstruct:18
```python
if env["target"] in ["editor", "template_debug"]:
doc_data = …
```
=> CMake: Support for XML documentation

README.md
Supplements #1504
The old scripts in misc/hooks have been replaced by the Python pre-commit tool, but this was not updated in the README.md yet.
=> Update README.md with new pre-commit instructions

binding_generator.py
This replaces https://github.com/godotengine/godot/pull/101639
Bug description (copied from that issue):
the affected code receives a pointer to an enum as a void pointer, and reinterpret casts it to an int64 pointer, probably because int64 is the size used for variants. But enums are not 64 bit by default, and the majority of enums in the godot codebase use the default size, which is usually int (32 bit on most platforms), and never larger unless absolutely needed, see [C++ standard on enum size](https://timsong-cpp.github.io/cppwp/n4140/dcl.enum#7)
Since the code immediately does a truncating C-style cast of this int64 to the enum type, the 4 extra bytes will be discarded immediately and not result in any program logic errors.
I verified my changes by diffing the `gen/` directories …
=> Fix buffer overrun with enums pointers cast to int64_t* when enum is only 32-bit

.github/actions/godot-cache-restore/action.yml, .github/actions/godot-cache-save/action.yml, .github/actions/setup-godot-cpp/action.yml, .github/workflows/ci.yml, .github/workflows/runner.yml, .github/workflows/static_checks.yml, README.md, binding_generator.py, build_profile.py, include/godot_cpp/classes/ref.hpp, include/godot_cpp/core/defs.hpp, include/godot_cpp/variant/quaternion.hpp, include/godot_cpp/variant/variant.hpp, include/godot_cpp/variant/vector4.hpp, misc/scripts/check_get_file_list.py, src/variant/quaternion.cpp, test/build_profile.json, tools/android.py, tools/common_compiler_flags.py, tools/godotcpp.py, tools/ios.py, tools/linux.py, tools/macos.py, tools/web.py, tools/windows.py
The 9th batch of PR's marked with `cherrypick:4.2`
=> Cherry-picks for the godot-cpp 4.2 branch - 9th batch

cmake/godotcpp.cmake
As described in issue #1690 the expression needs to depend on TARGET_ALIAS not TARGET_NAME.
This was introduced when I was solving the naming conflict issues and I missed this usage.
=> CMake: Fix #1690 - DEBUG_FEATURES generator expression

CMakeLists.txt, cmake/GodotCPPModule.cmake, cmake/godotcpp.cmake, test/CMakeLists.txt
After @Naros pointed out that for orchestrator the doc_source.cpp file was not being generated it made me think that a more predictable and obvious method is desirable.
Changes:
* Renamed `python_callouts.cmake` to `GodotCPPModule.cmake`
* Moved the `find_package(Python3 3.4 REQUIRED)` to top of `GodotCPPModule.cmake` to guarantee its availability.
* Added `target_doc_sources` CMake function
It's typical of CMake projects to APPEND to the CMAKE_MODULES_PATH to include scripts from dependencies.
Renaming the `python_callouts.cmake` to `GodotCPPModule.cmake` creates a very clear location to place any CMake functionality which is public facing.
In consumer CMakeLists.txt it would be recommended that after including the godot-cpp project to:
```cmake
list(APPEND CMAKE_MODULE_PATH …
```
=> CMake: GodotCPPModule.cmake

cmake/godotcpp.cmake, cmake/macos.cmake
It was brought to my attention that @Naros was getting builds with the architecture name tag set to `unknown`
This is cosmetic and doesnt effect the build, but did expose an underlying problem with how I was treating the `CMAKE_SYSTEM_PROCESSOR` flag, and how I was generating the `OUTPUT_NAME`
It also made me re-examine how I was treating the `OSX_ARCHITECTURES`, in light of the recent `MSVC_RUNTIME_LIBRARIES` #1701 discussion
Changes:
* Remove `GODOT_ARCH` option, it's managed by the toolchain files, or build vars.
* Rename `godot_arch_map` to `godot_arch_name` to better describe its use
* Add the known Android architectures to the `godot_arch_name` internal lists
* Return `${CMAKE_SYSTEM_PROCESSOR}` when architecture is unknown instead of `unknown`
* Remove all reference to …
=> CMake: Fix unknown architecture and simplify OSX_ARCHITECTURES

cmake/GodotCPPModule.cmake
When compiling using 'MinGW Makefiles' the folders aren't created as needed.
This leads to a failure to generate an include doc_source.cpp via the python script with the error:
```shell
FileNotFoundError: [Errno 2] No such file or directory: 'C:/build/godot-cpp/build-cmake/test/src/gen/doc_data.gen.cpp'
```
This PR will create the directory if it doesnt exist.
=> CMake: Create destination folder for doc_source.cpp generation

include/godot_cpp/core/defs.hpp, include/godot_cpp/variant/aabb.hpp, include/godot_cpp/variant/basis.hpp, include/godot_cpp/variant/color.hpp, include/godot_cpp/variant/plane.hpp, include/godot_cpp/variant/projection.hpp, include/godot_cpp/variant/quaternion.hpp, include/godot_cpp/variant/rect2.hpp, include/godot_cpp/variant/rect2i.hpp, include/godot_cpp/variant/transform2d.hpp, include/godot_cpp/variant/transform3d.hpp, include/godot_cpp/variant/vector2.hpp, include/godot_cpp/variant/vector2i.hpp, include/godot_cpp/variant/vector3.hpp, include/godot_cpp/variant/vector3i.hpp, include/godot_cpp/variant/vector4.hpp, include/godot_cpp/variant/vector4i.hpp
- Related: godotengine/godot#90582
C++17 natively accepts the attribute syntax, so the macro was entirely vestigial.
=> Style: Replace `_NO_DISCARD_` macro with `[[nodiscard]]`

cmake/godotcpp.cmake
I was working on something today and wanted to just generate the bindings separately to compilation.
This PR adds a custom target to do just that.
Would be the same as running SCons with build_library=no
=> CMake: Add generate_bindings custom target

binding_generator.py, include/godot_cpp/classes/wrapped.hpp
In Godot PR https://github.com/godotengine/godot/pull/93311, we changed the way that required virtual methods were registered, so that the `extension_api.json` could denote which virtual methods were required.
This PR aims to bring the same changes to godot-cpp! This is important to allow the same API as used in Godot modules.
~~Unfortunately, this PR depends on PR https://github.com/godotengine/godot/pull/103302, which corrects a small mistake that I made in the original Godot PR, so this will fail CI for the moment :-/~~
**UPDATE:** The Godot PR has been merged, so this should build fine now!
=> Update `GDVIRTUAL*()` macros to match Godot 4.4

.github/workflows/ci.yml, CMakeLists.txt, cmake/GodotCPPModule.cmake, cmake/common_compiler_flags.cmake, cmake/godotcpp.cmake, cmake/windows.cmake, doc/cmake.rst, test/CMakeLists.txt
This is for discussion primarily at this stage.
While I've been working on other random projects, it comes up that they have their projects setup to build godot so that they can debug the editor and their gdextension at the same time.
This does create a sort of name clash where it ends up feeling confusing that the variables used `GODOT_` are for the bindings, and not for the engine.
So I'm just putting this out there, to see what others thoughts are.
=> CMake: Rename all GODOT_ to GODOTCPP_

.pre-commit-config.yaml, CMakeLists.txt, cmake/GodotCPPModule.cmake, cmake/android.cmake, cmake/common_compiler_flags.cmake, cmake/emsdkHack.cmake, cmake/godotcpp.cmake, cmake/ios.cmake, cmake/linux.cmake, cmake/macos.cmake, cmake/web.cmake, cmake/windows.cmake, test/CMakeLists.txt
I found an auto formatter inspired by black.
This is what would happen if it was added to the pre-commit hooks
=> CMake: Pre-Commit Hook to Gersemi for auto-formatting

CMakeLists.txt, cmake/godotcpp.cmake
People seem to want to build godot-cpp by itself, without any arguments, not even specifying a target.
So we have to detect if we are top level and make template_debug available for the all target.
This can only happen when we are the top level target, because if we enable template_debug for all when we are part of something larger than its unnecessary compilation.
This adresses #1724 and duplicate #1727
=> CMake: template_debug as default target when godot-cpp is top level

CMakeLists.txt, cmake/android.cmake, cmake/common_compiler_flags.cmake, cmake/emsdkHack.cmake, cmake/godotcpp.cmake, cmake/ios.cmake, cmake/linux.cmake, cmake/macos.cmake, cmake/web.cmake, cmake/windows.cmake, doc/cmake.rst
While I'm doing some tidying up I have these comment changes I'd like to make.
Because this PR is based on the GODOTCPP_ rename it wil have some of that intermingled in the change list, but it isnt in the actual changes of the PR.
There is a method to the madness, I aim for 80 column width for no real reason. 
Top of the files get a restructures text comment with information about the file that looks like this:
```rst
#[=======================================================================[.rst:
Title
-------
This is where all the content goes. etc.. In restructured text_ format.
.. _text :https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
]=======================================================================]
```
Functions get a header like this:
```cmake …
```
=> CMake: Comment Cleanup

cmake/web.cmake
The SCons build doesn't do this, so neither should CMake.
Excpetions are already handled by DISABLE_EXCEPTIONS option.
[And it seems to be a mistake too.](https://github.com/godotengine/godot-cpp/pull/1598#discussion_r1917417944)
=> Remove unnecessary forced -fno-exceptions for web builds

.github/workflows/ci.yml, cmake/android.cmake, cmake/common_compiler_flags.cmake, cmake/godotcpp.cmake, cmake/ios.cmake, cmake/linux.cmake, cmake/macos.cmake, cmake/web.cmake, cmake/windows.cmake, doc/cmake.rst, test/CMakeLists.txt
re-mastered:
I've had this thought stuck in my head for a day or so, and a lingering doubt that I might be able to put to rest.
When I embarked on bringing godot-cpp cmake upto a more modern approach it was hard to grasp how it might fit into a standard cmake script. The way I initially thought about it was as three separate libraries, template_debug, template_release and editor.
This is why I made the solution create the three targets, so that users could configure and link to any of the targets they choose.
The latest thought is that this was a mistake on my part, there is only one library, and target is simply a configuration variable.
The output name is just an artifact of convenience and doesnt denote a separate library, but rather a separate configuration of the same library. I …
=> CMake: Revert to single cmake target

cmake/GodotCPPModule.cmake, cmake/godotcpp.cmake, test/CMakeLists.txt
This has been rebased onto #1733
I was working on the github CI and XCode was failing to compile due to the target dependency chain not meeting their requirements.
Turns out it has other implications for dependency generation that I found when compiling a real extension.
This PR brings the dependency chain inline with XCode's expectations, and simplifies some things.
Fixes https://github.com/godotengine/godot-cpp/issues/1739
=> CMake: XCode dependency chain fixes

binding_generator.py
It should be ok when folds exist. It will fail to build without this patch,  in vs code on windows with compiler ( visual studio community 2022 amd 64) .
=> binding_generator.py: Don't error if directory already exists

cmake/common_compiler_flags.cmake
Changes:
* Made all warnings private.
* Warning as error private
* Consistency in  generator expressions
Justification:
CMake can propagate usage requirements to consumers of targets through PUBLIC, PRIVATE, INTERFACE flags on some options.
* PUBLIC - used for the target, and any dependents 
* PRIVATE - used only on the target
* INTERFACE - used only on the depedent
By having PRIVATE in all our options we were dictating to consumers a bunch of options that do not necessarily apply to their builds.
=> CMake: public/private flags

include/godot_cpp/templates/cowdata.hpp, include/godot_cpp/templates/hash_map.hpp, include/godot_cpp/templates/hash_set.hpp, include/godot_cpp/templates/hashfuncs.hpp, include/godot_cpp/templates/list.hpp, include/godot_cpp/templates/local_vector.hpp, include/godot_cpp/templates/pair.hpp, include/godot_cpp/templates/rb_map.hpp, include/godot_cpp/templates/rb_set.hpp, include/godot_cpp/templates/safe_refcount.hpp, include/godot_cpp/templates/search_array.hpp, include/godot_cpp/templates/self_list.hpp, include/godot_cpp/templates/sort_array.hpp, include/godot_cpp/templates/vector.hpp, include/godot_cpp/templates/vmap.hpp, include/godot_cpp/templates/vset.hpp
This is just like PR https://github.com/godotengine/godot-cpp/pull/1715, but instead of synchronizing the variant code, this synchronizes the template code!
The same process was followed:
1. Delete everything between `namespace godot { ... }` in godot-cpp's `.hpp` file
2. Copy the corresponding code from Godot
3. Make simple, superficial changes in order to compile. _No large-scale changes were made to the Godot code!_
I have omitted a couple of things:
- `rid_owner.hpp`: Includes some threading stuff that will need some special care
- `spin_lock.hpp`: Depends on some OS specific stuff code from within Godot (`core/os/thread.h`), which we can't just refer to
- `thread_work_pool.hpp`: Appears to be loosely based on `core/object/worker_thread_pool.h` from Godot, which we can already use via …
=> Synchronize most shared template code with Godot 4.4

include/godot_cpp/core/engine_ptrcall.hpp, include/godot_cpp/core/method_ptrcall.hpp
Fixes https://github.com/godotengine/godot-cpp/issues/1741
It looks like we were incorrectly encoding return values for functions that return `char32_t`, `char16_t` and `wchar_t` as pointers to those exact types, whereas Godot is encoding them as pointers to `int64_t`
This PR fixes that!
In a follow up, we should update both SCons and cmake to use the `-fstack-protector-strong` flag with GCC and the equivalent flag for all other compilers (at least in debug builds), so that we can catch these sort of issues quicker.
=> Fix stack smashing when Godot methods return `char32_t`, `char16_t` or `wchar_t`

include/godot_cpp/variant/projection.hpp, src/variant/projection.cpp
When GDExtension generates bindings, it creates C++ code based on the API JSON. Values are serialized into literals constructed with numbers matching the value, for example, `Vector3(0, 1, 0)`. This includes default values for function parameters. Projection default values are serialized like `Projection(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)`. However, Godot is missing a constructor for Projection, so the generated C++ code doesn't compile:
I encountered this problem when the CI checks for godot-cpp failed to compile with my 4D module, because one of the bound methods includes a Projection default value, which cannot be constructed, as seen in the above image. This wasn't a problem in the engine before because the engine doesn't have any Projection default values in parameters. …
=> Add missing Projection constructor with 16 `real_t` values

include/godot_cpp/core/type_info.hpp
Fixes https://github.com/godotengine/godot-cpp/issues/1735
=> Add method_ptrcall header include to type_info to fix compiler errors

binding_generator.py, include/godot_cpp/variant/variant.hpp, src/variant/packed_arrays.cpp
Fixes https://github.com/godotengine/godot-cpp/issues/1710
This PR adds support for range based loops for the TypedArray class.
Allowing syntax such as:
```
TypedArray<int> elements;
for (const auto& e : elements) {}
```
I wanted to get proper type inference for the element, but I had issues getting the Variant type to cast properly.
=> Add support for range based loops for Array

.github/actions/setup-godot-cpp/action.yml, .github/workflows/ci-cmake.yml, .github/workflows/ci-scons.yml, .github/workflows/runner.yml, .github/workflows/static_checks.yml, CMakeLists.txt, cmake/godotcpp.cmake, cmake/ios.toolchain.cmake
This has been rebased onto #1730
Replaced some manual shell commands to detect changes with  tj-actions/changed-files@v45
Duplicated the ci.yml into ci-scons.yml and ci-cmake.yml
conditionally run the CI depending on what files change.
This is still a WIP
=> Update CI with new CMake builds.

test/project/example.gd.uid, test/project/example.gdextension.uid, test/project/main.gd.uid, test/project/main.tscn, test/project/project.godot, test/project/test_base.gd.uid
- This closes https://github.com/godotengine/godot-cpp/issues/1749.
=> Update test project to Godot 4.4

include/godot_cpp/classes/ref.hpp, include/godot_cpp/templates/pair.hpp, include/godot_cpp/variant/typed_dictionary.hpp
Allows for the following syntax:
```
TypedDictionary<int, String> colors = {
{1, "Red"},
{2, "Green"}
};
```
=> Typed dictionary initializer support

binding_generator.py, include/godot_cpp/variant/typed_array.hpp, include/godot_cpp/variant/variant.hpp
This PR adds support for initializer_list syntax, allowing `TypedArray`s to be assigned more easily, with syntax such as: `TypedArray<int> x = { 1, 2, 3 };`
Its a nice to have feature that I've found missing while developing gdextensions, I'm also writing a gdscript to gdextension transpiler and this syntax would help to make that possible.
=> Add support for `initializer_list` to Array and TypedArray

include/godot_cpp/variant/quaternion.hpp
That happened when compiling with Clang on Linux and `-Wall` https://github.com/Zylann/godot_voxel/actions/runs/14456040422/job/40539389673
=> Use Math::abs to avoid ambiguity with integer abs

binding_generator.py
Currently, `TypedDictionary` bindings fail to generate correctly.
This issue has not been apparent so far because Godot has not exposed any API using `TypedDictionary`, but it makes CI checks fail on PRs such as godotengine/godot#104096 which do so.
This PR fixes the bindgen with two small tweaks:
- An off-by-one index is corrected
- Parenthesis are added to prevent macros from erroneously splitting arguments on the comma in `TypedDictionary<KeyType, ValueType>`
For convenience, here is an `extension_api.json` generated from the above PR. The issue is related to the `typeddictionary::` entries.
[extension_api.json](https://github.com/user-attachments/files/19658749/extension_api.json)
Fixes https://github.com/godotengine/godot/issues/100137
=> Fix TypedDictionary binding generation

.github/workflows/ci-cmake.yml
Github recenty decomissioned some cache servers:
https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
> GitHub has migrated customers to a [new cache service](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down) and will now be shutting down the old service. This process will include brownouts of the old service before turning it off completely on April 15th, 2025. If your Actions workflows are still hitting the old cache service, your workflows may fail during these brownouts.
The brownout dates and times are as follows:
> * April 1, 2025, 3 p.m. – 7 p.m. UTC
> * …
=> CI: bump of mozilla-sccache action to 0.0.9

tools/godotcpp.py, tools/windows.py
- Followup to https://github.com/godotengine/godot/pull/104893
Will enable SCons scripts to declare certain includes are external/system explicitly, for the sake of supressing warnings. Not too relevant in this isolated context, where we don't really care about warnings, but will prove useful for anything deriving from us (eg: the main repo's GDExtension text servers)
=> SCons: Add `CPPEXTPATH` for external includes

binding_generator.py, include/godot_cpp/classes/wrapped.hpp, test/project/main.gd
I couldn't find an issue for this, but it seems that the default `_to_string()` for extension classes just always returns `"[Wrapped:0]"` which is not very helpful :-)
This PR fixes it by moving the default `_to_string()` implementation to `Object`, rather than `Wrapped`. And it makes the one on `Wrapped` explicitly always return `"[Wrapped:0]"` like it did before, but without all the code that made it look like it was doing something more sophisticated.
=> Fix classes without `_to_string()` always returning `"[Wrapped:0]"`

src/core/class_db.cpp
```
godot-cpp/src/core/class_db.cpp: In static member function 'static void godot::ClassDB::_editor_get_classes_used_callback(GDExtensionTypePtr)':
godot-cpp/src/core/class_db.cpp:395:88: error: loop variable 'pair' of type 'const std::pair<godot::StringName, const GDExtensionInstanceBindingCallbacks*>&' binds to a temporary constructed from type 'std::pair<const godot::StringName, const GDExtensionInstanceBindingCallbacks*>' [-Werror=range-loop-construct]
395 | ame, const GDExtensionInstanceBindingCallbacks *> &pair : instance_binding_callbacks) {
|                                                    ^~~~
godot-cpp/src/core/class_db.cpp:395:88: note: use non-reference type 'const std::pair<godot::StringName, const GDExtensionInstanceBindingCallbacks*>' to make the copy explicit or 'const …
```
=> Fix ClassDB iterators making unintended copies

README.md
Per the discussion at the previous GDExtension meeting, we think it's time to stop saying that GDExtension is experimental :-)
While I guess we technically still reserve the right to break compatibility if there is a bug or issue serious enough, based on our track record so far, I don't think we will need to.
This PR replaces the warning about being experimental, with some of the text copied from this docs page:
https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/what_is_gdextension.html#version-compatibility
I think we should ultimately just link to that docs page, so we don't have to update this information in two places, however, I don't want to link to it with https://github.com/godotengine/godot-docs/pull/10631 still open, because that will lead to the URL …
=> Stop referring to GDExtension as experimental in the README

tools/ios.py
This is required when publishing to the App Store, and consistent with what we already do for the macOS deployment target.
See godotengine/webrtc-native#169
=> fix: Add iOS min SDK version link flags

cmake/GodotCPPModule.cmake
Double precision builds with CMake are currently broken. Since I'm contributing the fix directly I did not bother to make an issue first, but please let me know if that is required.
The `binding_generator_generate_bindings` function has erroneous commas after some of its arguments (i.e., `PRECISION,`), but this is not correct CMake syntax; the arguments should be separated by whitespace. This causes the `USE_TEMPLATE_GET_NODE`, `BITS`, and `PRECISION` arguments to not be properly received when this function is invoked. This is partially masked for the `BITS` argument as there is a `BITS` variable at a higher CMake scope that is used.
The end result is that the `PYTHON_SCRIPT` always ends up getting populated with  `precision=''` and `use_template_get_node=''`, which makes it impossible to …
=> Fix CMake double precision builds

include/godot_cpp/variant/variant.hpp
This PR fixes a runtime crash when using the Array's `initializer_list` constructor
=> Fix array constructor crash

tools/android.py
In my project, I need to bump ndk to a newer version to be able to use C++20.
It would be possible to bump it here, but that would possibly break users' CI (on update), and wouldn't be future proof either.
I think it's appropriate to just make it configurable, since I don't think it needs to be in sync with godotengine master.
Edit: I have tested this with my own GDExtension, seems to build fine! I haven't tested it will run, but given that godot itself has been ndk version 27 now, I don't think it's required to use the same version as it does, so I don't think there should be hidden caveats.
=> Make ndk version configurable as a command-like argument.

README.md
`latest` points to a different path.  
`stable` though still points to the old path
=> Fix URL to gdextension cpp example in the official docs

include/godot_cpp/core/method_bind.hpp, src/core/method_bind.cpp
Renamed and reordered variables and methods to be more consistent with `godot`, it's not 100% since there are some additional methods and some methods missing.
This PR shouldn't change any functionality, its purely refactoring.
=> Clean up the MethodBind class

binding_generator.py
See https://github.com/godotengine/godot/pull/107660
It was generating invalid `TypedDictionary<String, Font>` type, now it's `TypedDictionary<String, Ref<Font>>`. Existing bindings should not change.
=> Fix binding generation for `TypedArray`/`TypedDictionary` with refcounted elements.

.github/workflows/runner.yml
It was noticed in #1772 that after updating a header the CI was not triggered.
This was my fault when I made the detection rules.
This PR updates the rules to include the missing .hpp files.
I also double checked what other files may be valid to detect and found `include\godot_cpp\core\math.compat.inc`
I removed redundant .py detection in scons, as it was already in the sources section which triggers both builds.
=> [GitHub CI] Fix source detection, added missing include .hpp and .inc to detection rules.

.github/workflows/ci-cmake.yml, .github/workflows/ci-scons.yml
godot-cpp's CI does some double precision builds, however, it's using the `extension_api.json` in the repo which is from a single precision build, and hence shouldn't be used for this purpose.
In https://github.com/godotengine/godot-cpp/pull/1714, we added some protections to stop users from doing this, but they hadn't kicked in yet because we needed an updated `extension_api.json` that included precision information
Commit https://github.com/godotengine/godot-cpp/commit/61f52cb3280ade85000c64baadf77e159a5e11fa synchronized the `extension_api.json` with 4.5-beta1 which includes this information, and now CI is failing... And it should fail because this not a valid build!
**This PR just removes the double precision builds for now.**
I also can't ever recall these tests ever failing before, …
=> Disable double precisions builds in CI for now

.github/workflows/ci.yml, README.md, binding_generator.py, include/godot_cpp/classes/wrapped.hpp, include/godot_cpp/core/engine_ptrcall.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/core/method_ptrcall.hpp, include/godot_cpp/variant/projection.hpp, src/core/class_db.cpp, src/core/method_bind.cpp, src/variant/projection.cpp, test/project/main.gd, tools/android.py, tools/godotcpp.py, tools/ios.py, tools/windows.py
The 5th (and possibly last) batch of PR's marked with `cherrypick:4.3`
=> Cherry-picks for the godot-cpp 4.3 branch - 5th batch

SConstruct, tools/godotcpp.py
Supersedes #1439 - it's basically just a rebase. It compiles, but I haven't checked if it does what it says it does (allow godot-cpp to be included from elsewhere).
=> Add SCons variant_dir support

src/godot.cpp
Not checking the function pointer before reading it like a struct causes ubsan to detect this as a problem.
=> Only check for Godot 4.0 if the pointer is aligned how it would be for the legacy interface.

include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/method_bind.hpp, src/godot.cpp
The `<string>` header was in `class_db.hpp` and `method_bind.hpp` even though no parts of it are used in either of those files.  I also removed the `<iostream>` header from class_db.hpp because it was also unused. Both of these files ended up getting included in thousands of other cpp files so slowed down build time a lot.
There seem to be only 2 uses of code from `<string>` in godot-cpp as the code works now:
1. In src/godot.cpp it was used for printf and snprintf. Removing <string> from the class_db header broke this but just including stdio fixed it.
2. It was also used in templates/char_traits.cpp for std::char_traits::length. I left the <string> include in this file because I didn't want to change how it works and it's in a cpp file so it doesn't matter that much.
I did 2 test runs …
=> Remove <string> includes in headers to improve build time

include/godot_cpp/core/binder_common.hpp, include/godot_cpp/core/class_db.hpp, include/godot_cpp/core/method_bind.hpp, include/godot_cpp/core/object.hpp, src/core/class_db.cpp, src/core/method_bind.cpp, src/core/object.cpp
This removes (almost) all of the std::vector usage and replaces it with Godot's LocalVector.
There is still one place in `classes/wrapped.cpp` where std::vector is still used that I didn't want to mess with because it calls push_back during static initialization and the allocation function that LocalVector::push_back uses from the GDExtension API isn't registered yet. Reworking this to figure out a better time to call push_back didn't look too fun so I'm just going to leave it as is.
I tested the build time difference with ClangBuildAnalyzer and got these results:
Executed in  103.10 secs
**** Time summary:
Compilation (1025 times):
Parsing (frontend):         1640.2 s
Codegen & opts (backend):    190.6 s
Executed in  106.30 secs
**** Time summary:
Compilation (1025 times):
Parsing …
=> Use LocalVector instead of std::vector

gdextension/gdextension_interface.h, include/godot_cpp/godot.hpp, src/core/memory.cpp, src/godot.cpp
Fixes https://github.com/godotengine/godot-cpp/issues/1820
~~Marking as a DRAFT because this depends on https://github.com/godotengine/godot/pull/108725~~
UPDATE: Godot PR has been merged!
=> Update to use `mem_alloc2`, `mem_realloc2` and `mem_free2`

include/godot_cpp/core/binder_common.hpp
g++ falsely flagged `p_args` as unused. This PR applies the same fix used in the surrounding functions.
g++ -v: `g++ (Debian 12.2.0-14+deb12u1) 12.2.0`
clang (using clangd) does not report this warning at all.
=> Silenced compiler warning in godot::call_with_variant_args_ret_helper

include/godot_cpp/core/class_db.hpp, include/godot_cpp/templates/a_hash_map.hpp, src/core/class_db.cpp
std::unordered_map is used all over in the ClassDB but there doesn't seem to be any good reason for it, internally godot would normally [use HashMap for something like this](https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/core_types.html#containers).
I tested the compile time of the test project with [ClangBuildAnalyzer](https://github.com/aras-p/ClangBuildAnalyzer) and got these results showing that almost all of the slowest templates to instantiate were unordered_map, even though it is only ever use in the ClassDB. These are the full results I got:
[first.txt](https://github.com/user-attachments/files/22222937/first.txt)
The relevant parts that showed me that unorderd_map was insanely slow for compile times were here:
```cpp
**** Time summary: …
```
=> Replace unordered_map with AHashMap to improve build time
