- include/SConstruct
- Local dependency paths are now grouped in a few vars on top of SConstruct
- Added an option to generate bindings as part of the build
> Improve build usage

- include/core/Godot.hpp
Please test if it breaks any code.
> template magic

- include/core/Godot.hpp
Also makes gcc and clang happy
> Replaced 'char *' with 'const char *' for consistency with C API

- SConstruct
Just added some parameters for the paths
> Add some command line parameters to overrule default paths

- binding_generator.py
- include/core/Variant.hpp
There is fix for #31 
But it will work only after merging a PR in godot engine
> Fix bindings generation for enums

- include/core/Godot.hpp
This has been an issue from the day one,
A lot of people mentioned this on discord too
> Fix `_arg_cast`

- .gitignore
- SConstruct
- binding_generator.py
- include/core/Godot.hpp
- include/core/GodotGlobal.hpp
- include/core/Ref.hpp
- src/core/Array.cpp
- src/core/Basis.cpp
- src/core/Color.cpp
- src/core/Dictionary.cpp
- src/core/GodotGlobal.cpp
- src/core/NodePath.cpp
- src/core/Plane.cpp
- src/core/PoolArrays.cpp
- src/core/Quat.cpp
- src/core/RID.cpp
- src/core/Rect2.cpp
- src/core/Rect3.cpp
- src/core/String.cpp
- src/core/Transform2D.cpp
- src/core/Variant.cpp
- src/core/Vector3.cpp
Did a bunch of changes so cpp_bindings now work with the new api struct.
The structure is recorded as a global and then used throughout to call into Godot. 
Note that you have to trash and re-generate the classes
> Implemented using api struct

- binding_generator.py
- include/core/Godot.hpp
without this, the clang command fails
> Fixed building

- include/core/Array.hpp
- include/core/Dictionary.hpp
- src/core/Array.cpp
- src/core/Dictionary.cpp
Should partially fix https://github.com/godotengine/godot/issues/15793
Might also fix https://github.com/GodotNativeTools/godot-cpp/issues/64
PoolVectors may need some love too
> Added copy constructors and assignment operators to Array and Dictionary

- include/core/Godot.hpp
Should also partally fix https://github.com/godotengine/godot/issues/15793#issuecomment-358145338, though I didn't really proof-tested that one.
In combination with https://github.com/GodotNativeTools/godot-cpp/pull/69 it seems to completely fix the above issue.
> Fix potential malloc(0)

- include/core/AABB.hpp
- src/core/AABB.cpp
- src/core/Transform.cpp
> Renamed AABB::pos --> AABB::position

- include/core/PoolArrays.hpp
And now they can be used like in core ;)
> Added copy constructors to PoolArray Read and Write

- include/core/RID.hpp
- src/core/RID.cpp
- Also fixes default constructor
- is_valid() is worked around by comparing a default RID()
> Added RID::is_valid() and comparison operators

- .gitignore
For a nicer list of untracked changes
> Ignore Windows binaries

- include/core/Basis.hpp
- include/core/Quat.hpp
- include/core/String.hpp
- src/core/AABB.cpp
- src/core/Basis.cpp
- src/core/Color.cpp
- src/core/Quat.cpp
- src/core/String.cpp
- src/core/Transform2D.cpp
- src/core/Vector2.cpp
- src/core/Vector3.cpp
- Added missing static String constructors
- Implemented String operator for math types
- Added XYZ and YXZ euler angles methods
- Fixed wrong det checks in Basis
- Fixed operator Quat in Basis
> String and math fixes

- include/core/RID.hpp
> Fix RID::is_valid()

- README.md
> README: Enable cpp syntax highlighting

- binding_generator.py
- include/core/AABB.hpp
- include/core/Defs.hpp
- include/core/Godot.hpp
- include/core/PoolArrays.hpp
- include/core/Rect2.hpp
- include/core/Ref.hpp
- include/core/Transform2D.hpp
- src/core/GodotGlobal.cpp
https://github.com/GodotNativeTools/godot-cpp/issues/126
> C++14 syntax sugar

- include/core/String.hpp
- src/core/String.cpp
> Fix const for String operators.

- .gitmodules
> fix submodule link

- README.md
A PR (#135) and issue (#142) were already submitted related to this but they are dead in the water for other reasons. I needed this fix as well, so I assume this isn't a one-off error and that this information may be helpful to others, too. 
First time actually contributing to a project in such a fashion; I wasn't sure whether it was most appropriate to revive that PR, the pre-existing issue, or create this new PR, so I went with the one I figured would result in the quickest fix. If either was a more appropriate option I can close this and pursue those. Thanks!
> Update README.md to include compilation error fix

- include/core/Godot.hpp
Fixed up registering class as a tool class and now using new godot headers.
> Fixed up registering tool and updated godot_headers

- README.md
I've only tested compiling this on Windows and it probably could use some proof reading.
> New documentation based on nativescript 1.1

- include/core/Godot.hpp
Fixed up the GODOT_SUBCLASS macro after getting the code from Karroffel :)
> Fixed GODOT_SUBCLASS macro

- include/core/Godot.hpp
Solves this issue #168 due to not having the include of typeinfo
> Adds needed include <typeinfo>

- src/core/Vector2.cpp
Fixes this issue: https://github.com/GodotNativeTools/godot-cpp/issues/181
> Fix issue where Vector2::normalize() did not normalize correctly

- README.md
Just added link to the 3.0 and nativescript-1.0 branches
> Added info about the older branches to the README.md

- src/core/Transform.cpp
redid a fix from an earlier PR from Kirsanium
> Redid kirsanium xform fix

- include/core/Vector3.hpp
- src/core/Vector3.cpp
See https://github.com/GodotNativeTools/godot-cpp/issues/189
> Vector3: add missing methods

- include/core/Vector3.hpp
- src/core/Vector3.cpp
Just redid #190 after accidentally merging it into nativescript 1.1 branch :P
> Redid PR 190 for master now that nativescript 1.1 has been merged

- SConstruct
After reading documentation on Variables usage in scons: https://scons.org/doc/1.0.1/HTML/scons-user/x2361.html
- Modify enum parameters to support case-insensitive input (all values converted to lowercase).
- Modify existing ARGUMENTS usage into Variables usage (`use_custom_api_file`, `custom_api_file`, and `generate_bindings`).
- Add support for producing an error when unknown parameters are given.
- Remove duplicate code initializing the `json_api_file` to empty string.
> Replace ARGUMENTS with opts.Add/env and some cleanup

- SConstruct
Just a few typo fixes,
Fixes #211
> Fixing a few typos in SConstruct

- CMakeLists.txt
I have tested this on linux, windows (visual studio) and android and it works. So I thought I'd create a pull request for it if you want it =)
> Added cmake build script

- include/core/Rect2.hpp
- src/core/Rect2.cpp
- src/core/Transform2D.cpp
To match current Godot API (Changed by https://github.com/godotengine/godot/pull/9038)
> Renamed Rect2::pos to Rect2::position

- SConstruct
- binding_generator.py
- Fix automatic architecture detection
- Fix compiling with MinGW on Linux
- MinGW on Windows is still not working though
- Default to Clang on macOS
- Remove redundant `use_custom_api_file` option
- Format SConstruct using Flake8
Please test extensively on all platforms; I've done basic testing on Windows, macOS and Linux but I may not have caught edge cases.
This closes #245.
> Fix and improve the build system

- binding_generator.py
This change gets rid of the call-time method binding query, instead it queries
all method bindings up-front at initialization time so that no extra cost is
added at function call time.
In addition, also converted the "icall" code to a header-only library so one
level of unnecessary call-stack is eliminated.
Also changed binding generator to use real_t instead of double everywhere
(except at the GDNative interface where unfortunately using doubles is hard-coded
on the engine side).
All this comes at a minimal increase in binary size (for the library, as actual
native modules might not even increase in size in practice).
> Optimizations to the generated bindings

- include/core/Basis.hpp
I guess you already fixed this..!
> fix shadows template parameter

- include/core/Vector2.hpp
- src/core/Vector2.cpp
Defining the inline function in `cpp` file is not right, right?
I got function found error, so I guess yes
> Fix snapped from Vector2

- README.md
> Mention rules for using Godot classes in the readme

- include/core/Color.hpp
- src/core/Color.cpp
Fixes https://github.com/GodotNativeTools/godot-cpp/issues/405
> Added missing Color operators

- .travis.yml
- misc/travis/clang-format.sh
Cf. https://github.com/godotengine/godot/pull/36350
> Travis: Use clang-format 8.0, update script

- include/core/Vector2.hpp
- include/core/Vector3.hpp
Fixes https://github.com/godotengine/godot-cpp/issues/411
Also added to Vector2
> Add missing Vector3::direction_to() and Vector2::direction_to()

- include/core/CameraMatrix.hpp
- include/core/RID.hpp
- src/core/CameraMatrix.cpp
- src/core/RID.cpp
The ARCore plugin development is ongoing in https://github.com/GodotVR/godot_arcore
**Note:** This PR also includes the changes from #433 as the library generation code is currently broken without it.
> Additions to the library to support the ARCore plugin

- include/core/Defs.hpp
- include/core/Math.hpp
Supersedes https://github.com/godotengine/godot-cpp/pull/466
> Fix some Math warnings

- include/core/Array.hpp
- src/core/Array.cpp
These methods are supposed to be const but are missing the const qualifiers.
> Fix constness of Array::find, Array::find_last and Array::rfind

- CMakeLists.txt
> Search correct python interpeter in case missing default "python"

- .clang-format
- .github/workflows/ci.yml
- include/core/AABB.hpp
- include/core/CameraMatrix.hpp
- include/core/Color.hpp
- include/core/Godot.hpp
- include/core/GodotGlobal.hpp
- include/core/Math.hpp
- include/core/PoolArrays.hpp
- include/core/Rect2.hpp
- include/core/Ref.hpp
- include/core/String.hpp
- include/core/Vector3.hpp
- misc/ci/sources.list
- src/core/AABB.cpp
- src/core/Basis.cpp
- src/core/CameraMatrix.cpp
- src/core/Color.cpp
- src/core/GodotGlobal.cpp
- src/core/Plane.cpp
- src/core/Quat.cpp
- src/core/Rect2.cpp
- src/core/String.cpp
- src/core/TagDB.cpp
- src/core/Transform.cpp
- src/core/Transform2D.cpp
This is taken from the Godot repository, so formatting is similar. This updates the style rules as well.
Also fix style in files to conform with this version.
> Update clang-format to version 11

- README.md
- SConstruct
Includes update to `README.md` with instructions on how to build a
GDNative library for webassembly.
> Add JavaScript platform support (emcc, wasm).

- include/core/Math.hpp
Added asin, asinf, acos, acosf, atan, atanf in Math.hpp. Related issue: #556.
> added inverse trigonometric functions in Math.hpp

- include/core/String.hpp
- src/core/String.cpp
Modified `String.cpp` and `String.hpp` to implement move constructor and move assignment operator. Related issue #435.
> added String's move constructor and move assignment operator

- SConstruct
Will create smaller builds in `release`, bigger builds in `debug`.
> Add optimization flags for android and javascript.

- .github/workflows/ci.yml
Draft as it includes #617, will rebase once it's merged.
> CI: Run tests with Godot 3.3.3

- README.md
> Update godot version in README.MD

- README.md
Updating readme in preparation for new branches.
> Updating the readme with new branch info

- binding_generator.py
- include/godot_cpp/variant/array_helpers.hpp
Added support for our `Array::make` macro.
> Add `Array::make` macro

- include/godot_cpp/core/class_db.hpp
- include/godot_cpp/core/object.hpp
Normalized additional macros to ensure that everything works without  client code needing using
> Explicit namespace for macros

- README.md
This PR will update the README file with the same contents under [libraries] as in the demo project in /test
> Update README file for macos support

- include/godot_cpp/godot.hpp
- src/godot.cpp
The godot-cpp counterpart of https://github.com/godotengine/godot/pull/58629.
> Reorder native extension initialization steps

- binding_generator.py
- godot-headers/godot/gdnative_interface.h
- include/godot_cpp/core/object.hpp
Part of https://github.com/godotengine/godot/pull/59207 to work (header and json are synced with this PR).
> Sync godot-headers and fix build after "Create GDExtension clases for PhysicsServer3D".

- binding_generator.py
Depends on https://github.com/godotengine/godot/pull/59314 (including changes in my comment).
> Add support for static method bindings.

- binding_generator.py
- godot-headers/godot/gdnative_interface.h
- include/godot_cpp/core/method_bind.hpp
- test/demo/main.gd
- test/src/example.cpp
- test/src/example.h
Depends on https://github.com/godotengine/godot/pull/58436 rebase over [11a5f612fa](https://github.com/godotengine/godot/commit/11a5f612fa208a680e3c421a1c360406ec520bb2) (headers/.json synced).
> Add support for variadic method binds with the typed return.

- .github/workflows/ci.yml
- SConstruct
- binding_generator.py
Uses the same version of `black` as godot.
> [CI] Add python file format to static checks.

- SConstruct
> [SCons] Fix Android builds with modern NDKs.

- SConstruct
(cherry picked from commit b8ae658981c5f9b59889ba805290953a0b9911ed).
Ref: #765
> [3.4] [SCons] Fix Android builds with modern NDKs.

- binding_generator.py
- godot-headers/godot/gdnative_interface.h
- include/godot_cpp/core/binder_common.hpp
- include/godot_cpp/core/class_db.hpp
- include/godot_cpp/core/type_info.hpp
- src/core/class_db.cpp
- test/demo/project.godot
Implements support for the bit fields added in https://github.com/godotengine/godot/pull/62374
Depends on https://github.com/godotengine/godot/pull/62906
> Add support for BitField hint, sync API files.

- README.md
Referencing https://github.com/godotengine/godot-cpp/pull/750
- `register_scene_initializer` -> `register_initializer`
- `register_scene_terminator` -> `register_terminator`
with appropriate initialization level
> Update register initializer/terminator in README

- CMakeLists.txt
It seems `-fPIC` not work on windows.
> Fix compile fail when windows with llvm+ninja

- .github/workflows/ci.yml
- tools/android.py
See failures in https://github.com/godotengine/godot-cpp/runs/7528300926
> [CI] Fix Android builds after GH container update.

- include/godot_cpp/variant/basis.hpp
Implements
https://github.com/godotengine/godot-proposals/issues/5295
> Fix Basis constructor: row vectors -> column vectors

- misc/scripts/clang_format.sh
- test/README.md
- test/src/example.cpp
- test/src/example.h
- test/src/register_types.cpp
- test/src/register_types.h
> Relicense integration testing project under public domain/Unlicense

- include/godot_cpp/variant/transform3d.hpp
- src/variant/transform3d.cpp
Just copied from core.
https://docs.godotengine.org/en/latest/classes/class_transform3d.html#class-transform3d-method-rotated-local
https://docs.godotengine.org/en/latest/classes/class_transform3d.html#class-transform3d-method-scaled-local
https://docs.godotengine.org/en/latest/classes/class_transform3d.html#class-transform3d-method-translated-local
> Add Transform3D `translated_local`, `rotated_local`, `scaled_local`

- include/godot_cpp/core/math.hpp
- src/variant/basis.cpp
- src/variant/quaternion.cpp
This PR is split into 5 commits, each one has a description with a link to the relevant engine PRs.
> Update math functions with recent changes and additions from Godot

- binding_generator.py
- include/godot_cpp/core/type_info.hpp
- include/godot_cpp/variant/typed_array.hpp
- test/demo/main.gd
- test/src/example.cpp
- test/src/example.h
Depends on https://github.com/godotengine/godot/pull/65817
> Implement support for typed arrays.

- binding_generator.py
Part of https://github.com/godotengine/godot/pull/66492
> Add wrapper function generation for built-in module ↔ godot-cpp interoperability.

- include/godot_cpp/core/math.hpp
- include/godot_cpp/variant/basis.hpp
- include/godot_cpp/variant/quaternion.hpp
- include/godot_cpp/variant/transform3d.hpp
- src/variant/basis.cpp
- src/variant/quaternion.cpp
- src/variant/transform3d.cpp
This PR updates Basis/Transform3D/Quaternion to match the engine. I updated all 3 at once because their changes are codependent on each other, so we can't just update one.
> Update Basis/Transform3D/Quaternion to match the engine

- binding_generator.py
Fixes https://github.com/godotengine/godot-cpp/issues/787
> Fix passing null to functions taking Object parameters

- include/godot_cpp/core/class_db.hpp
- src/core/class_db.cpp
Add detail infos for binding error message.
Help GDExtension developers to locate bind errors position.
> Add detail infos for binding error message.

- binding_generator.py
Related to https://github.com/godotengine/godot/pull/66774
> Fix Variant types displayed as `Nil` in extension_api.json

- README.md
- binding_generator.py
- godot-headers/godot/gdnative_interface.h
- include/godot_cpp/classes/ref.hpp
- include/godot_cpp/classes/wrapped.hpp
- include/godot_cpp/core/binder_common.hpp
- include/godot_cpp/core/builtin_ptrcall.hpp
- include/godot_cpp/core/class_db.hpp
- include/godot_cpp/core/engine_ptrcall.hpp
- include/godot_cpp/core/method_bind.hpp
- include/godot_cpp/core/method_ptrcall.hpp
- include/godot_cpp/core/type_info.hpp
- include/godot_cpp/godot.hpp
- include/godot_cpp/variant/variant.hpp
- src/classes/wrapped.cpp
- src/core/class_db.cpp
- src/core/method_bind.cpp
- src/godot.cpp
- src/variant/variant.cpp
- test/src/register_types.cpp
see https://github.com/godotengine/godot/pull/67751
> Fix const qualifier for parameters in GDExtension api functions

- include/godot_cpp/core/method_ptrcall.hpp
fix the casting error present in #946 (but doesn't solve the runtime issue discussed there)
> Fix cast on PtrToArg::convert

- gdextension/gdextension_interface.h
- include/godot_cpp/core/binder_common.hpp
- include/godot_cpp/core/class_db.hpp
- include/godot_cpp/core/method_bind.hpp
- src/core/method_bind.cpp
godot-cpp equivalent to https://github.com/godotengine/godot/pull/70023.
> Extension header: amend const correctness of `p_args` parameters

- .github/actions/godot-cache/action.yml
- .github/workflows/ci.yml
- .gitignore
- SConstruct
- binding_generator.py
- misc/scripts/check_get_file_list.py
Backport of:
- #748 
- #838 
- #853
- #903
> [3.x] [SCons] Backport SCons generator, cache.

- .github/workflows/static_checks.yml
Seems like there's a slight inconsistency for the formatting of the `delete[](pointer)` syntax.
> CI: Use clang-format 15

- include/godot_cpp/variant/basis.hpp
- src/variant/quaternion.cpp
> Fix a shadowed enum (EulerOrder)

- binding_generator.py
- gdextension/gdextension_interface.h
- include/godot_cpp/core/math.hpp
- include/godot_cpp/templates/cowdata.hpp
- include/godot_cpp/variant/variant.hpp
- src/classes/low_level.cpp
- src/variant/char_string.cpp
- test/demo/main.gd
- test/src/example.cpp
- test/src/example.h
Part of https://github.com/godotengine/godot/pull/69288
> Expose some low level functions and String operators.

- src/core/class_db.cpp
> Fix sign comparison warnings in class_db.cpp

- include/godot_cpp/templates/local_vector.hpp
It looks to me that templates sync is not automated, unless I am mistaken?
Anyway, here is local_vector, with proper godot namespace and headers.
> Add missing local_vector.hpp template

- binding_generator.py
- gdextension/gdextension_interface.h
- src/variant/packed_arrays.cpp
- test/demo/main.gd
Part of https://github.com/godotengine/godot/pull/71989
> Move Array:set_typed to internal GDExtension structure.

- CMakeLists.txt
- cmake/GodotCompilerWarnings.cmake
Instead of specifying flags manually, use CMake.
> {cmake} Use STATIC and POSITION_INDEPENDENT_CODE

- test/project/main.gd
- test/project/project.godot
- test/src/example.cpp
- test/src/example.h
This has been on my TODO list for waaay too long!
This PR adds automated tests to verify some important bug fixes that were merged before (or around the same time as) we added the automated tests, specifically:
- https://github.com/godotengine/godot/pull/75758
- https://github.com/godotengine/godot/pull/77410
- https://github.com/godotengine/godot-cpp/pull/1050
This will hopefully prevent us from breaking those things ever again :-)
> Add automated tests to verify some previous fixes

- README.md
Also updated format for library paths
* Fixes: #1217
> Fix link to test project in readme

- include/godot_cpp/templates/cowdata.hpp
See:
* https://github.com/godotengine/godot/pull/81917
> Fix allocation size overflow check in `CowData`

- .github/workflows/ci.yml
- .github/workflows/static_checks.yml
- SConstruct
- binding_generator.py
- include/godot_cpp/classes/wrapped.hpp
- include/godot_cpp/core/class_db.hpp
- include/godot_cpp/core/method_ptrcall.hpp
- src/godot.cpp
- test/project/project.godot
- tools/android.py
- tools/godotcpp.py
- tools/javascript.py
- tools/macos.py
The 3rd batch of PR's marked with `cherrypick:4.1`
> Cherry-picks for the godot-cpp 4.1 branch - 3rd batch

- .github/workflows/ci.yml
Follow-up to #1168 which only went part of the way.
> [3.x] CI: Update all images and actions

- .github/workflows/ci.yml
Reverts PR https://github.com/godotengine/godot-cpp/pull/1299
I want to see if this passes CI, then I'll take it out of draft.
> Revert "Hack adding `--quit-after 100` to ensure extension_list.cfg gets generated"

- .github/ISSUE_TEMPLATE/bug_report.yml
See:
* https://github.com/godotengine/godot/pull/87409
> Use latest doc version in issue template

- README.md
Fixes Table of Contents entry issue introduced in commit https://github.com/godotengine/godot-cpp/commit/1588dc8437e16c33b3241e267df22555dcbc0cd7
> Fix README Examples and Templates TOC Entry

- .clang-format
- .editorconfig
- .pre-commit-config.yaml
- SConstruct
- binding_generator.py
- include/godot_cpp/classes/wrapped.hpp
- include/godot_cpp/core/method_bind.hpp
- include/godot_cpp/variant/callable_method_pointer.hpp
- include/godot_cpp/variant/char_string.hpp
- include/godot_cpp/variant/variant.hpp
- pyproject.toml
- test/src/example.cpp
- test/src/example.h
A collection of miscellaneous version bumps & the tweaks that come from them
> CI: Various version bumps; sync with main repo

- .github/workflows/ci-scons.yml
- Related godotengine/godot#105756
> CI: Ensure utf-8 support on Windows GHA

- .github/actions/setup-godot-cpp/action.yml
- .github/workflows/ci-cmake.yml
- cmake/android.cmake
- doc/cmake.rst
- tools/android.py
Sync target versions with https://github.com/godotengine/godot/pull/106148
> Sync Android SDK and NDK versions with the engine.
